Repository datalad/datalad, pull requests merged in 2018-09, with the labels that each got.

#2806 BFs and RF (Windows): more precommits etc to avoid operation on held up files/directories
  datalad/__init__.py
  datalad/distribution/tests/test_create.py
  datalad/distribution/tests/test_dataset.py
  datalad/interface/diff.py
  datalad/interface/tests/test_add_archive_content.py
  datalad/interface/tests/test_diff.py
  datalad/interface/tests/test_ls_webui.py
  datalad/interface/tests/test_run.py
  datalad/interface/tests/test_run_procedure.py
  datalad/interface/tests/test_save.py
  datalad/support/cookies.py
  datalad/support/locking.py
  datalad/support/sshconnector.py
  datalad/support/tests/test_annexrepo.py
  datalad/support/tests/test_gitrepo.py
  datalad/support/tests/test_path.py
  datalad/tests/test_auto.py
  datalad/tests/test_log.py
  datalad/tests/test_utils.py
  datalad/tests/utils.py
  datalad/utils.py
Labels: needs the best merge!, needs-review

#2842 More docs on metadata handling in DataLad
  docs/source/customization.rst
  docs/source/metadata.rst
Labels: documentation

#2835 Adding config option to set superdataset root
  CHANGELOG.md
  CONTRIBUTORS
  datalad/consts.py
  datalad/distribution/dataset.py
  datalad/distribution/tests/test_dataset.py
  datalad/interface/common_cfg.py
  datalad/metadata/search.py
  datalad/metadata/tests/test_search.py
  datalad/support/network.py
  docs/source/basics.rst
Labels: needs the best merge!, needs-review

#2861 BF: install default value for jobs should be "auto" not None
  datalad/distribution/install.py
Labels: bug

#2865 ENH: Report detailed info on git-annex in `wtf` (fixes gh-2854)
  datalad/plugin/wtf.py
Labels: needs the best merge!

#2859 Some love for `update`
  datalad/distribution/tests/test_update.py
  datalad/distribution/update.py
Labels: needs the best merge!

#2878 `search` updates for improved metadata layout
  datalad/metadata/search.py
Labels: Metadata
