Repository datalad/datalad, pull requests merged in 2018-08, with the labels that each got.

#2728 DOC: Add command summaries to datalad.api.__doc__
  datalad/__init__.py
  datalad/api.py
  datalad/cmdline/main.py
  datalad/interface/base.py
Labels: documentation

#2741 ENH: wtf returns structured data (fixes gh-2415, gh-2734)
  datalad/interface/__init__.py
  datalad/plugin/tests/test_plugins.py
  datalad/plugin/wtf.py
Labels: needs the best merge!

#2735 NF: Field-selective search in egrep mode (fixes gh-2337)
  datalad/cmdline/main.py
  datalad/metadata/search.py
  datalad/metadata/tests/test_base.py
  datalad/metadata/tests/test_search.py
Labels: needs the best merge!

#2724 A variety of enhancements and fixes for metadata search
  datalad/metadata/extractors/annex.py
  datalad/metadata/extractors/base.py
  datalad/metadata/metadata.py
  datalad/metadata/search.py
  datalad/metadata/tests/test_search.py
Labels: needs the best merge!

#2725 ENH: report absent fields reported as N/A in output instead of not rendering the record at all
  datalad/interface/base.py
  datalad/interface/tests/test_base.py
Labels: needs the best merge!

#2738 ENH progressbars for addurl
  datalad/support/annexrepo.py
  datalad/ui/progressbars.py
Labels: needs the best merge!

#2759 Accumulator for metadata handling fixes
  datalad/metadata/metadata.py
  datalad/metadata/search.py
Labels: needs the best merge!

#2708 ENH+BF: S3 and downloaders: support anonymous access + interface to add new providers
  datalad/downloaders/base.py
  datalad/downloaders/configs/crawdad.cfg
  datalad/downloaders/configs/providers.cfg
  datalad/downloaders/credentials.py
  datalad/downloaders/http.py
  datalad/downloaders/providers.py
  datalad/downloaders/s3.py
  datalad/downloaders/tests/test_http.py
  datalad/downloaders/tests/test_providers.py
  datalad/downloaders/tests/test_s3.py
  datalad/interface/ls.py
  datalad/support/exceptions.py
  datalad/support/s3.py
  datalad/tests/utils.py
  datalad/ui/base.py
  datalad/ui/dialog.py
  datalad/ui/tests/test_base.py
  datalad/ui/tests/test_dialog.py
Labels: needs-review
