Repository datalad/datalad, pull requests merged in 2018-10, with the labels that each got.

#2886 RF: Move get_git_dir() into GitRepo
  datalad/distribution/dataset.py
  datalad/distribution/tests/test_utils.py
  datalad/distribution/utils.py
  datalad/interface/clean.py
  datalad/metadata/search.py
  datalad/support/gitrepo.py
Labels: needs the best merge!

#2904 RF: Centralize submodule addition logic in GitRepo
  datalad/distribution/add.py
  datalad/distribution/get.py
  datalad/distribution/utils.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_gitrepo.py
Labels: needs the best merge!

#2932 ENH: Make core reporting ready for paths as pathlib objects
  datalad/interface/utils.py
  datalad/tests/utils.py
Labels: enhancement

#2941 ENH(TST): test that we can install/get from datasets.datalad.org (or its -tests brother)
  datalad/distribution/tests/test_install.py
Labels: bug-windows
