Repository datalad/datalad, pull requests merged in 2018-06, with the labels that each got.

#2557 BF+TST: Alternative fix to gh-2552 (with test)
  datalad/distribution/create.py
  datalad/distribution/tests/test_add.py
Labels: on hold - input required

#2603 Command to execute "prepared procedures"
  datalad/cmdline/main.py
  datalad/distribution/tests/test_create.py
  datalad/interface/__init__.py
  datalad/interface/common_cfg.py
  datalad/interface/run_procedure.py
  datalad/interface/utils.py
  datalad/resources/procedures/cfg_metadatatypes.py
  datalad/resources/procedures/cfg_text2git.py
  datalad/resources/procedures/setup_yoda_dataset.py
  datalad/tests/utils.py
  datalad/utils.py
  docs/source/cmdline.rst
  docs/source/customization.rst
  docs/source/modref.rst
  setup.py
Labels: breakthrough

#2542 NF: DATALAD_ASSERT_NO_OPEN_FILES
  CONTRIBUTING.md
  datalad/distribution/remove.py
  datalad/support/archives.py
  datalad/support/gitrepo.py
  datalad/support/tests/utils.py
  datalad/tests/test_utils.py
  datalad/utils.py
  setup.py
Labels: needs the best merge!, needs-review

#2625 Mutagen and httpretty fixups
  datalad/downloaders/tests/test_http.py
  setup.py
Labels: buildbot

#2630 Naming question
  datalad/cmdline/main.py
  datalad/distribution/tests/test_create.py
  datalad/interface/base.py
  datalad/interface/common_opts.py
  datalad/interface/run_procedure.py
  datalad/interface/tests/test_base.py
  datalad/interface/tests/test_run_procedure.py
  datalad/interface/utils.py
  datalad/plugin/tests/test_plugins.py
Labels: question

#2632 Support {dspath} as additional placeholder for `run`
  datalad/interface/run.py
  datalad/interface/tests/test_run.py
Labels: needs the best merge!
