Repository datalad/datalad, pull requests merged in 2018-02, with the labels that each got.

#2130 BF+TST: Can re-aggregate with unavailable object files (fixes gh-1971)
  datalad/interface/common_cfg.py
  datalad/metadata/aggregate.py
  datalad/metadata/extractors/bids.py
  datalad/metadata/extractors/tests/test_bids.py
  datalad/metadata/metadata.py
  datalad/metadata/search.py
  datalad/metadata/tests/test_aggregation.py
  datalad/metadata/tests/test_search.py
Labels: needs the best merge!

#2129 ENH: Alias --output-format with -o
  datalad/cmdline/main.py
  datalad/interface/utils.py
Labels: UX

#2154 BF: use GitPython for getting information about tags, get hexsha for nonannotated tags as well
  datalad/support/gitrepo.py
  datalad/support/tests/test_gitrepo.py
Labels: needs the best merge!, needs-review

#2036 Some kind of progress bar for index construction?
  datalad/metadata/metadata.py
  datalad/metadata/search.py
Labels: UX

#2157 Various small improvements to metadata aggregation
  datalad/interface/common_cfg.py
  datalad/metadata/aggregate.py
  datalad/metadata/metadata.py
  datalad/metadata/search.py
  datalad/metadata/tests/test_aggregation.py
  datalad/metadata/tests/test_base.py
Labels: Metadata, enhancement, needs the best merge!

#2151 Various bugfixes addressing some corner cases while parsing datasets.datalad.org with new extractors
  datalad/metadata/aggregate.py
  datalad/metadata/extractors/bids.py
  datalad/metadata/extractors/tests/test_bids.py
  datalad/metadata/tests/test_aggregation.py
  datalad/metadata/tests/test_search.py
  datalad/tests/test_utils.py
  datalad/utils.py
  setup.py
Labels: needs the best merge!, needs-review

#2145 -c datalad.runtime.raiseonerror=yes in command line is not passed into cfg
  datalad/cmdline/main.py
  datalad/cmdline/tests/test_main.py
  datalad/config.py
Labels: bug, fix-implemented, needs the best merge!

#2149 NF: Plugin `extract_metadata`
  datalad/metadata/metadata.py
  datalad/plugin/__init__.py
  datalad/plugin/extract_metadata.py
  datalad/plugin/tests/test_metadata.py
Labels: Metadata, do-as-plugin

#2134 BF: Tolerate files starting with -
  datalad/customremotes/tests/test_archives.py
  datalad/interface/tests/test_add_archive_content.py
  datalad/support/annexrepo.py
  datalad/tests/utils.py
Labels: WIP, bug, needs-review

#2185 intermittent test failure: 'str' does not support the buffer interface
  datalad/cmd.py
  datalad/tests/test_cmd.py
Labels: bug

#2190 ENH(TST): a humble attempt to eliminate coverage diff
  .travis.yml
  datalad/crawler/nodes/annex.py
  datalad/crawler/oldconfig/__init__.py
  datalad/crawler/oldconfig/base.py
  datalad/crawler/oldconfig/tests/__init__.py
  datalad/crawler/oldconfig/tests/test_config.py
  datalad/metadata/extractors/__init__.py
  datalad/metadata/extractors/datacite.py
  datalad/metadata/extractors/dicom.py
  datalad/metadata/extractors/tests/test_base.py
  datalad/metadata/extractors/tests/test_datacite_xml.py
  datalad/metadata/search.py
  datalad/metadata/tests/test_search.py
  datalad/support/tests/test_sshrun.py
  datalad/tests/test_base.py
  datalad/tests/test_tests_utils.py
  datalad/tests/test_utils.py
  datalad/tests/utils.py
  datalad/utils.py
  setup_support.py
Labels: needs the best merge!

#2187 Use lsfiles to obtain list of submodules (and maybe other info)
  datalad/distribution/get.py
  datalad/distribution/subdatasets.py
  datalad/distribution/tests/test_subdataset.py
  datalad/interface/tests/test_annotate_paths.py
  datalad/interface/tests/test_diff.py
Labels: needs the best merge!

#2191 UI code bug somewhere
  datalad/downloaders/base.py
  datalad/support/s3.py
Labels: UX, bug

#2207 Better error reporting of `metadata --get-aggregates`
  datalad/metadata/metadata.py
  datalad/metadata/tests/test_base.py
Labels: needs the best merge!

#2203 `aggregate-metadata` doesn't handle subdataset removal correctly
  datalad/metadata/aggregate.py
  datalad/metadata/tests/test_aggregation.py
Labels: Metadata, needs the best merge!

#2204 Merges and adjusts for use of path_startswith from 0.9.x
  datalad/distribution/get.py
  datalad/distribution/subdatasets.py
  datalad/interface/annotate_paths.py
  datalad/interface/diff.py
  datalad/interface/results.py
  datalad/interface/utils.py
  datalad/metadata/aggregate.py
  datalad/metadata/metadata.py
  datalad/metadata/tests/test_search.py
  datalad/tests/test_tests_utils.py
  datalad/tests/test_utils.py
  datalad/tests/utils.py
  datalad/utils.py
Labels: needs the best merge!

#1675 Handle subdatasets in subdirectories correctly in the web browser listing frontend
  datalad/interface/ls.py
  datalad/interface/ls_webui.py
  datalad/interface/tests/test_ls.py
  datalad/interface/tests/test_ls_webui.py
Labels: needs the best merge!

#2183 config option for --report-status (and may be others in the reporting code)
  datalad/cmdline/main.py
  datalad/interface/base.py
  datalad/interface/common_cfg.py
  datalad/interface/tests/test_base.py
Labels: WIP, needs the best merge!, needs-test
