Repository datalad/datalad, pull requests merged in 2018-03, with the labels that each got.

#2232 Fails to datalad install subdataset when dataset path has ~
  datalad/distribution/tests/test_install.py
  datalad/support/gitrepo.py
Labels: bug, needs the best merge!, needs-review

#2238 ENH: Aggregated metadata query now utilized annotated path types
  datalad/metadata/metadata.py
  datalad/metadata/search.py
Labels: Metadata, needs the best merge!

#2243 Out of source tree tests fail, files missing
  setup.py
Labels: fix-implemented

#1528 drop python 3.4 and aim for 3.5 and 3.6
  .travis.yml
  tox.ini
Labels: TERRIFIC!, needs the best merge!

#2251 ENH merge 0.9.x
  datalad/cmdline/main.py
  datalad/distribution/tests/test_install.py
  datalad/distribution/utils.py
  datalad/downloaders/base.py
  datalad/interface/ls.py
  datalad/interface/ls_webui.py
  datalad/interface/tests/test_ls.py
  datalad/interface/tests/test_ls_webui.py
  datalad/resources/website/assets/js/main.js
  datalad/support/gitrepo.py
  datalad/support/s3.py
  datalad/tests/test_s3.py
Labels: needs the best merge!

#2263 BF: Fix missing import
  datalad/distribution/uninstall.py
Labels: needs the best merge!

#2277 Accumulated doc changes
  .travis.yml
  CONTRIBUTING.md
  docs/source/basics.rst
  docs/source/metadata.rst
Labels: documentation

#2121 [WIP] ENH: Add initial implementation of addurls plugin
  datalad/plugin/addurls.py
  datalad/plugin/tests/test_addurls.py
  datalad/support/annexrepo.py
  datalad/support/network.py
  datalad/tests/utils.py
Labels: WIP

#2284 Entry-level docs improved
  docs/source/faq.rst
  docs/source/gettingstarted.rst
  docs/source/index.rst
  docs/source/metadata.rst
  docs/source/usecases/index.rst
Labels: documentation

#2286 bids2scidata is missing installed resource
  setup.py
Labels: bug, fix-implemented

#2224 No plugins -> plug-able commands
  .github/issue_template.md
  .travis.yml
  datalad/api.py
  datalad/cmdline/main.py
  datalad/cmdline/tests/test_main.py
  datalad/distribution/tests/test_create.py
  datalad/interface/__init__.py
  datalad/interface/base.py
  datalad/interface/utils.py
  datalad/metadata/aggregate.py
  datalad/plugin/__init__.py
  datalad/plugin/add_readme.py
  datalad/plugin/addurls.py
  datalad/plugin/bids2scidata.py
  datalad/plugin/export_archive.py
  datalad/plugin/export_to_figshare.py
  datalad/plugin/extract_metadata.py
  datalad/plugin/no_annex.py
  datalad/plugin/tests/test_addurls.py
  datalad/plugin/tests/test_bids2scidata.py
  datalad/plugin/tests/test_export_archive.py
  datalad/plugin/tests/test_metadata.py
  datalad/plugin/tests/test_plugins.py
  datalad/plugin/wtf.py
  datalad/utils.py
  docs/source/cmdline.rst
  docs/source/customization.rst
  docs/source/modref.rst
Labels: help wanted

#2255 ENH: Nicer search
  datalad/metadata/metadata.py
  datalad/metadata/search.py
  datalad/metadata/tests/test_base.py
  datalad/metadata/tests/test_search.py
Labels: UX, made great again

#2292 casts: Add more 'rerun' examples
  docs/casts/simple_provenance_tracking.sh
Labels: WIP

#2299 RF: do not raise if git is not configured -- just issue a warning
  datalad/distribution/tests/test_uninstall.py
  datalad/interface/tests/test_add_archive_content.py
  datalad/support/annexrepo.py
  datalad/support/gitrepo.py
  datalad/support/json_py.py
  datalad/support/tests/test_gitrepo.py
  datalad/support/tests/test_json_py.py
  datalad/tests/test_base.py
  datalad/tests/utils.py
Labels: needs-review

#2300 RF/BF: get_commit_date to return authored date by default, handle detached head as well
  datalad/interface/ls.py
  datalad/plugin/export_tarball.py
  datalad/plugin/tests/test_tarball.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_gitrepo.py
Labels: needs the best merge!

#2268 ENH/BF: --jobs got auto + fix with locking datalad-archives issue
  datalad/customremotes/archives.py
  datalad/interface/common_opts.py
  datalad/interface/tests/test_add_archive_content.py
  datalad/support/annexrepo.py
  datalad/support/archives.py
  datalad/support/locking.py
  datalad/support/tests/test_locking.py
  setup.py
Labels: needs the best merge!, needs-review

#2305 BF 2276: pass path_src into commit as well (so we commit renamed files removal as well)
  datalad/distribution/add.py
  datalad/distribution/drop.py
  datalad/distribution/get.py
  datalad/distribution/publish.py
  datalad/distribution/remove.py
  datalad/interface/annotate_paths.py
  datalad/interface/diff.py
  datalad/interface/save.py
  datalad/interface/tests/test_save.py
  datalad/interface/unlock.py
  datalad/metadata/metadata.py
Labels: needs the best merge!, needs-review

#2304 OPT: cache (lru_cache) calls to guess_ri_cls
  datalad/support/_lru_cache2.py
  datalad/support/cache.py
  datalad/support/network.py
Labels: needs the best merge!, needs-review

#2296 asciicast recording broken with asciinema 2.0
  Makefile
  docs/casts/cmdline_basic_usage.sh
  docs/source/basics.rst
  docs/source/basics_cmdline.rst.in
  docs/source/conf.py
  docs/source/usecases/index.rst
  docs/source/usecases/simple_provenance_tracking.rst
  docs/source/usecases/simple_provenance_tracking.rst.in
  docs/utils/pygments_ansi_color.py
  tools/cast2asciinema
  tools/cast2rst
Labels: bug, documentation, enhancement, needs the best merge!

#2294 bids2metadata now from aggregated metadata only
  datalad/plugin/bids2scidata.py
  datalad/plugin/tests/test_bids2scidata.py
Labels: Metadata

#2314 RF: No special casing of pybids needed anymore, but versioned dep
  requirements-devel.txt
  setup.py
  tools/Singularity.fullmaster
Labels: needs the best merge!

#2311 Extended use of demos in docs
  Makefile
  datalad/plugin/addurls.py
  datalad/tests/utils.py
  docs/examples/3rdparty_analysis_workflow.sh
  docs/source/basics.rst
  docs/source/basics_nesteddatasets.rst.in
  docs/source/customization.rst
  docs/source/modref.rst
  docs/source/usecases/index.rst
  docs/source/usecases/reproducible_analysis.rst
  docs/source/usecases/reproducible_analysis.rst.in
  docs/source/usecases/track_data_from_webpage.rst
  docs/source/usecases/track_data_from_webpage.rst.in
  tools/cast2asciinema
Labels: documentation

#2323 ENH: for a dummy egrep search to not search via "unique content properties"
  datalad/metadata/search.py
Labels: Metadata

#2334 RF: Demote log message to debug (we have progress bars now)
  datalad/support/annexrepo.py
Labels: UX

#2289 Pimp the datalad_core extractor to expose more of datalad's internal/implicit metadata
  datalad/metadata/aggregate.py
  datalad/metadata/extractors/__init__.py
  datalad/metadata/extractors/annex.py
  datalad/metadata/extractors/datalad_core.py
  datalad/metadata/extractors/tests/test_base.py
  datalad/metadata/extractors/tests/test_nidm.py
  datalad/metadata/search.py
  datalad/metadata/tests/test_search.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_gitrepo.py
Labels: Metadata

#2297 ENH: -c and -s|--sensitive=(all|some) for wtf, uniform(er) formatting, fix for __version_full__, more externals versions
  datalad/cmdline/tests/test_main.py
  datalad/plugin/tests/test_plugins.py
  datalad/plugin/wtf.py
  datalad/support/external_versions.py
  datalad/support/tests/test_external_versions.py
  datalad/version.py
  setup.py
Labels: needs the best merge!, needs-review

#2349 Metadata unique value sort broken for PY3
  datalad/metadata/metadata.py
Labels: bug

#2352 ENH: addurls: Reduce the number of metadata commits
  datalad/plugin/addurls.py
  datalad/plugin/tests/test_addurls.py
Labels: buildbot

#2346 option (or make it also automagicly enabled) to disable loading full metadata record for search result
  datalad/metadata/search.py
  datalad/metadata/tests/test_search.py
Labels: Metadata, UX, buildbot, enhancement

#2355 ENH: batched annex -- read/log stderr output if there was any
  datalad/support/annexrepo.py
Labels: WIP

#2363 BF: run/rerun: Don't use ok_clean_git
  datalad/interface/rerun.py
  datalad/interface/run.py
Labels: buildbot

#2365 `wtf()` only works with git version of datalad
  datalad/version.py
Labels: bug

#2360 RF: Define and use entrypoints for metadata extractors (fixes gh-2356)
  datalad/metadata/extractors/__init__.py
  datalad/metadata/metadata.py
  datalad/plugin/tests/test_metadata.py
  setup.py
Labels: needs the best merge!
