Repository datalad/datalad, pull requests merged in 2018-04, with the labels that each got.

#2370 NF: `test` can pick up extension test suites and run them too
  datalad/interface/test.py
Labels: needs the best merge!

#2344 `extract-metadata` command does not need to use `--file` anymore
  datalad/plugin/extract_metadata.py
Labels: needs the best merge!

#2371 DOC: on extensions
  docs/source/conf.py
  docs/source/customization.rst
Labels: documentation

#2377 Change test setup to run *installed* datalad
  .travis.yml
Labels: needs the best merge!

#2387 NF: Switch to select type of metadata aggregation update (fixes gh-2378)
  datalad/crawler/nodes/annex.py
  datalad/metadata/aggregate.py
  datalad/metadata/tests/test_aggregation.py
  datalad/metadata/tests/test_base.py
Labels: Metadata, needs the best merge!

#2008 save does not work within subdirectory of a subdataset: given reference dataset is not a dataset
  datalad/interface/save.py
Labels: bug, fix-implemented, needs the best merge!

#2397 ENH: addurls: Add an option to version S3 buckets URLs
  datalad/plugin/addurls.py
  datalad/plugin/tests/test_addurls.py
Labels: buildbot

#2399 DOC: Frontpage acknowledgements
  README.md
  docs/source/acknowledgements.rst
Labels: documentation

#2398 DOC: Documentation on `metadata` behavior and common use case examples
  datalad/metadata/metadata.py
  datalad/metadata/tests/test_aggregation.py
Labels: documentation

#2406 Gets confused by symbolic links in the path
  datalad/distribution/dataset.py
  datalad/interface/tests/test_save.py
  datalad/tests/test_utils.py
  datalad/utils.py
Labels: annex-v6, needs the best merge!, needs-review

#2407 some times fails to annex get data (locally I think) in our example
  docs/examples/3rdparty_analysis_workflow.sh
  tools/testing/run_doc_examples
Labels: annex-v6, bug, fails-on-travis, needs the best merge!

#1886 Symlink annotation issue; is a link to a dataset a type='dataset?
  datalad/interface/annotate_paths.py
  datalad/interface/tests/test_save.py
Labels: bug, fix-implemented

#2388 `aggregate_metadata` is not incremental
  datalad/metadata/aggregate.py
  datalad/metadata/tests/test_aggregation.py
Labels: Metadata, bug, fix-implemented

#2043 `save` update, fix bug, test intended behavior, improve docs
  datalad/interface/save.py
  datalad/interface/tests/test_save.py
  datalad/tests/test_utils.py
  datalad/tests/utils.py
Labels: UX, bug, fix-implemented

#2429 (re)run doc polish
  datalad/interface/rerun.py
  docs/source/modref.rst
Labels: documentation

#2351 Use lgr.info() to get UNIFORM progress reporting
  datalad/log.py
  datalad/metadata/search.py
  datalad/utils.py
Labels: UX, breakthrough

#2431 Add progress logging to any metadata extractor when #2351 is merged
  datalad/metadata/extractors/annex.py
  datalad/metadata/extractors/audio.py
  datalad/metadata/extractors/datalad_core.py
  datalad/metadata/extractors/exif.py
  datalad/metadata/extractors/image.py
  datalad/metadata/extractors/xmp.py
  datalad/metadata/metadata.py
Labels: UX, enhancement

#2223 0.10.0 Release notes
  CHANGELOG.md
Labels: documentation, help wanted

#2445 Fixes from #2083 without the actual appveyor setup
  datalad/cmd.py
  setup.py
Labels: bug-windows, made great again

#2453 Fixes from the appveyor explorations
  datalad/distribution/subdatasets.py
  datalad/tests/test_cmd.py
  datalad/utils.py
Labels: made great again, needs the best merge!

#2455 `search` documentation
  datalad/metadata/aggregate.py
  datalad/metadata/search.py
Labels: documentation
