Repository datalad/datalad, pull requests merged in 2018-05, with the labels that each got.

#2463 coverage for (all) plugins code is reported at 0%
  datalad/plugin/__init__.py
  datalad/tests/test_utils.py
  datalad/utils.py
Labels: buildbot, needs the best merge!

#2478 datalad run causes 100% CPU utilization by datalad
  datalad/cmd.py
Labels: buildbot, needs the best merge!, needs-review

#2439 Inappropriate message: [WARNING] Metadata query results might be incomplete
  datalad/cmdline/tests/test_main.py
  datalad/metadata/metadata.py
  datalad/metadata/tests/test_aggregation.py
  datalad/metadata/tests/test_base.py
  datalad/plugin/wtf.py
  datalad/version.py
Labels: Metadata, bug

#2417 Kill *Repo.add(commit=True)
  datalad/customremotes/tests/test_archives.py
  datalad/distribution/add.py
  datalad/distribution/create_test_dataset.py
  datalad/distribution/tests/test_install.py
  datalad/distribution/tests/test_publish.py
  datalad/distribution/tests/test_update.py
  datalad/interface/save.py
  datalad/interface/tests/test_ls_webui.py
  datalad/interface/tests/test_run.py
  datalad/plugin/tests/test_check_dates.py
  datalad/support/annexrepo.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_annexrepo.py
  datalad/support/tests/test_gitrepo.py
  datalad/support/tests/utils.py
  datalad/tests/utils.py
Labels: come in and sing along

#2489 Failing test: Should have managed to find at least the core extractor extractor
  datalad/metadata/extractors/tests/test_base.py
Labels: bug, fix-implemented

#2491 entry_points in extensions -- not in effect whatsoever? (tests do not run, not available within datalad namespace)
  datalad/interface/test.py
Labels: bug, question

#2495 OPT: delay import of pkg_resources until use, adjust log messages to differ
  datalad/api.py
  datalad/cmdline/main.py
  datalad/metadata/metadata.py
Labels: performance

#2497 datacite extractor requires file at .datalad/meta.datacite.xml
  datalad/metadata/extractors/datacite.py
  datalad/metadata/extractors/tests/test_datacite_xml.py
Labels: Metadata, UX

#2496 OPT: cmdline
  datalad/cmdline/main.py
  datalad/cmdline/tests/test_formatters.py
  datalad/cmdline/tests/test_main.py
  datalad/distribution/dataset.py
  datalad/interface/__init__.py
  datalad/interface/results.py
  datalad/plugin/__init__.py
  datalad/support/tests/test_sshrun.py
Labels: needs the best merge!

#2507 Web UI: "External link" icon for repos with external URL
  datalad/interface/ls_webui.py
  datalad/interface/tests/test_ls_webui.py
  datalad/resources/website/assets/css/main.css
  datalad/resources/website/assets/images/external-link-symbol.svg
  datalad/resources/website/assets/js/main.js
  datalad/resources/website/assets/js/showdown-1.8.5-33-g0c6ce94.js
  datalad/resources/website/index.html
  datalad/support/tests/test_network.py
Labels: needs the best merge!, needs-review

#2517 ENH merge 0.9.x
  datalad/interface/ls_webui.py
  datalad/interface/tests/test_ls_webui.py
  datalad/resources/website/assets/css/main.css
  datalad/resources/website/assets/images/external-link-symbol.svg
  datalad/resources/website/assets/js/main.js
  datalad/resources/website/assets/js/showdown-1.8.5-33-g0c6ce94.js
  datalad/resources/website/index.html
  datalad/support/tests/test_network.py
Labels: buildbot

#1921 Still issues with unicode file names
  .travis.yml
  datalad/__init__.py
  datalad/cmd.py
  datalad/customremotes/archives.py
  datalad/customremotes/base.py
  datalad/distribution/tests/test_add.py
  datalad/interface/diff.py
  datalad/interface/utils.py
  datalad/metadata/extractors/datalad_core.py
  datalad/plugin/wtf.py
  datalad/support/annexrepo.py
  datalad/support/archives.py
  datalad/support/gitrepo.py
  datalad/support/locking.py
  datalad/support/network.py
  datalad/support/path.py
  datalad/tests/test_archives.py
  datalad/tests/test_cmd.py
  datalad/tests/test_config.py
  datalad/tests/test_utils.py
  datalad/tests/utils.py
  datalad/utils.py
Labels: bug, buildbot, git-annex, needs the best merge!, needs-review
