Repository datalad/datalad, pull requests merged in 2019-03, with the labels that each got.

#3186 BF: Add switch to avoid pointless warnings (fixes gh-3185)
  datalad/metadata/aggregate.py
  datalad/metadata/metadata.py
Labels: needs the best merge!

#3197 BF: Repo.dirty will not report on nested empty datasets (fixes gh-3196)
  datalad/support/gitrepo.py
  datalad/support/tests/test_gitrepo.py
Labels: needs the best merge!

#3215 BF: Fix PWD to match provided cwd in Runner
  datalad/cmd.py
  datalad/tests/test_cmd.py
Labels: needs the best merge!, needs-review

#3220 BF: specify correctly dependency on pylibzma as prior python 3.3
  setup.py
Labels: needs the best merge!

#3226 Changes from master applicable to 0.11.x
  datalad/support/digests.py
  datalad/support/tests/test_gitrepo.py
  datalad/utils.py
Labels: needs the best merge!

#3184 ENH: duecredit support for citing datalad itself AND datasets it opens
  CONTRIBUTING.md
  datalad/distribution/dataset.py
  datalad/support/due.py
  datalad/support/due_utils.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_due_utils.py
  datalad/support/tests/test_gitrepo.py
  datalad/tests/test_utils.py
  datalad/utils.py
  setup.py
Labels: needs the best merge!, needs-review

#3252 RF: Eliminate the use of `add/save/create` outside of then obsolete code
  benchmarks/api.py
  datalad/core/local/create.py
  datalad/core/local/tests/test_save.py
  datalad/customremotes/tests/test_archives.py
  datalad/distribution/create_test_dataset.py
  datalad/distribution/subdatasets.py
  datalad/distribution/tests/test_add.py
  datalad/distribution/tests/test_create.py
  datalad/distribution/tests/test_create_github.py
  datalad/distribution/tests/test_create_sibling.py
  datalad/distribution/tests/test_dataset.py
  datalad/distribution/tests/test_get.py
  datalad/distribution/tests/test_install.py
  datalad/distribution/tests/test_publish.py
  datalad/distribution/tests/test_subdataset.py
  datalad/distribution/tests/test_uninstall.py
  datalad/distribution/tests/test_update.py
  datalad/distribution/update.py
  datalad/interface/download_url.py
  datalad/interface/tests/test_annotate_paths.py
  datalad/interface/tests/test_diff.py
  datalad/interface/tests/test_download_url.py
  datalad/interface/tests/test_ls.py
  datalad/interface/tests/test_ls_webui.py
  datalad/interface/tests/test_run_procedure.py
  datalad/interface/tests/test_save.py
  datalad/interface/tests/test_utils.py
  datalad/metadata/aggregate.py
  datalad/metadata/extractors/tests/test_audio.py
  datalad/metadata/extractors/tests/test_base.py
  datalad/metadata/extractors/tests/test_datacite_xml.py
  datalad/metadata/extractors/tests/test_exif.py
  datalad/metadata/extractors/tests/test_frictionless_datapackage.py
  datalad/metadata/extractors/tests/test_image.py
  datalad/metadata/extractors/tests/test_rfc822.py
  datalad/metadata/extractors/tests/test_xmp.py
  datalad/metadata/tests/test_aggregation.py
  datalad/metadata/tests/test_base.py
  datalad/metadata/tests/test_extract_metadata.py
  datalad/metadata/tests/test_search.py
  datalad/plugin/add_readme.py
  datalad/plugin/no_annex.py
  datalad/plugin/tests/test_addurls.py
  datalad/plugin/tests/test_export_archive.py
  datalad/plugin/tests/test_plugins.py
  datalad/resources/procedures/cfg_metadatatypes.py
  datalad/resources/procedures/cfg_text2git.py
  datalad/resources/procedures/setup_yoda_dataset.py
  datalad/tests/utils_testdatasets.py
Labels: I-wish-revolution-was-here, performance

#3271 Make local doc builds less painful
  CHANGELOG.md
  datalad/cmdline/main.py
  docs/Makefile
  docs/source/changelog.rst
  docs/source/conf.py
  setup_support.py
Labels: documentation

#3258 Provide a warning when a regex in a provider isn't valid
  datalad/downloaders/providers.py
  datalad/downloaders/tests/test_providers.py
Labels: pick up to 0.11.x
