Repository datalad/datalad, pull requests merged in 2019-12, with the labels that each got.

#3897 BF: auto - if empty list is returned by get, do not try to treat it as dict record
  datalad/auto.py
Labels: bug

#3863 BF: Perform result rendering prior error handling
  datalad/interface/utils.py
Labels: UX, bug

#3906 BF: Make sure to not issue an install-ok result, before the repo state is final
  datalad/distribution/get.py
Labels: bug

#3898 BF: Reintroduce 'notneeded' results for existing datasets in get()
  datalad/distribution/get.py
  datalad/distribution/tests/test_get.py
  datalad/distribution/tests/test_install.py
Labels: on hold - input required

#3903 NF: Result hooks
  datalad/config.py
  datalad/core/local/resulthooks.py
  datalad/core/local/tests/test_resulthooks.py
  datalad/interface/utils.py
Labels: It's huge!, enhancement

#3620 Debian packaging update
  debian/control
Labels: debian-packaging

#3959 BF: Always report absolute location of discovered procedures
  datalad/interface/run_procedure.py
Labels: merge-if-ok

#3960 BF: Provide indication which procedure is (to be) execut(ed/able)
  datalad/interface/run_procedure.py
  datalad/interface/tests/test_run_procedure.py
Labels: merge-if-ok
