Repository datalad/datalad, pull requests merged in 2019-04, with the labels that each got.

#3294 Speedier `rev-create`
  datalad/core/local/create.py
  datalad/core/local/status.py
  datalad/support/gitrepo.py
Labels: TERRIFIC!

#3304 ENH: Record a dataset's ID in a superdataset on `add/save` (fixes gh-3303)
  datalad/core/local/tests/test_create.py
  datalad/support/gitrepo.py
Labels: Metadata

#3314 OPT: status/diff performance on dataset hierarchies
  datalad/support/gitrepo.py
Labels: TERRIFIC!, performance

#3324 NF: status(eval_subdataset_state={'no'|'commit'|'full'}
  datalad/core/local/status.py
  datalad/support/annexrepo.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_fileinfo.py
  datalad/support/tests/test_repo_save.py
Labels: performance

#3326 DOC: Auto-set metavar for parameters with value choices
  datalad/distribution/create_sibling.py
  datalad/interface/base.py
  datalad/interface/run.py
  datalad/plugin/add_readme.py
  datalad/plugin/addurls.py
  datalad/plugin/check_dates.py
  datalad/plugin/export_archive.py
  datalad/plugin/export_to_figshare.py
  datalad/plugin/wtf.py
Labels: UX

#3329 Make XMP extractor faster (fixes gh-3328)
  datalad/metadata/extractors/xmp.py
Labels: TERRIFIC!, performance

#3322 OPT: do not bother sleeping when not output was received in the Runner processing of output
  datalad/cmd.py
Labels: needs the best merge!

#3343 NF: GitRepo._diffstatus() internal helper for global state evaluation (fixes gh-3342)
  datalad/support/gitrepo.py
Labels: performance

#3362 ENH: Add low-level switch to prevent file type evaluation
  datalad/support/gitrepo.py
Labels: performance
