Repository datalad/datalad, pull requests merged in 2020-08, with the labels that each got.

#4790 Use a fully random UUID as dataset ID
  datalad/core/local/create.py
Labels: metadata

#4806 OPT: Faster approach to GitRepo.get_hexsha()
  datalad/support/gitrepo.py
Labels: performance

#4834 RF: replace wrapped "new_?func" with meaningful "_wrap_<wrappedfunction>"
  datalad/distributed/ora_remote.py
  datalad/distributed/tests/ria_utils.py
  datalad/distributed/tests/test_create_sibling_ria.py
  datalad/support/gitrepo.py
  datalad/tests/test_utils.py
  datalad/tests/utils.py
  datalad/tests/utils_cached_dataset.py
  datalad/utils.py
Labels: UX

#4831 BF(TST): Define NOSE_OPTS as an array to start with
  .travis.yml
Labels: merge-if-ok

#4837 Benchmarks: disable track overhead
  benchmarks/core.py
Labels: DX
