Repository datalad/datalad, pull requests merged in 2020-03, with the labels that each got.

#3727 NF: a prototype for ext special remote to store files in git/objects of a remote
  CONTRIBUTING.md
  sandbox/git-annex-remote-gitobjects
Labels: merge-if-ok

#4172 No GitPython
  .travis.yml
  datalad/__init__.py
  datalad/auto.py
  datalad/cmdline/helpers.py
  datalad/distribution/dataset.py
  datalad/distribution/publish.py
  datalad/distribution/tests/test_create_sibling.py
  datalad/distribution/tests/test_create_test_dataset.py
  datalad/distribution/tests/test_dataset.py
  datalad/distribution/tests/test_get.py
  datalad/distribution/tests/test_install.py
  datalad/distribution/tests/test_publish.py
  datalad/distribution/tests/test_uninstall.py
  datalad/distribution/tests/test_update.py
  datalad/interface/ls.py
  datalad/interface/tests/test_add_archive_content.py
  datalad/interface/tests/test_annotate_paths.py
  datalad/interface/tests/test_diff.py
  datalad/interface/tests/test_utils.py
  datalad/metadata/extractors/tests/test_audio.py
  datalad/metadata/extractors/tests/test_base.py
  datalad/metadata/extractors/tests/test_exif.py
  datalad/metadata/extractors/tests/test_image.py
  datalad/metadata/extractors/tests/test_xmp.py
  datalad/metadata/tests/test_aggregation.py
  datalad/metadata/tests/test_base.py
  datalad/metadata/tests/test_extract_metadata.py
  datalad/metadata/tests/test_search.py
  datalad/plugin/check_dates.py
  datalad/plugin/tests/test_plugins.py
  datalad/plugin/wtf.py
  datalad/support/annexrepo.py
  datalad/support/exceptions.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_annexrepo.py
  datalad/support/tests/test_gitrepo.py
  datalad/support/tests/utils.py
  datalad/tests/test_utils_testrepos.py
  datalad/tests/utils.py
  setup.py
Labels: merge-if-ok

#4239 BF: Allow to explicitly specify host to aws-s3 resource
  datalad/downloaders/s3.py
  datalad/downloaders/tests/test_s3.py
Labels: merge-if-ok

#4258 RF: Reduce use of "ria" label
  datalad/distributed/create_sibling_ria.py
  datalad/distributed/tests/test_create_sibling_ria.py
Labels: UX, documentation

#4261 Reversed conditional in AnnexRepo.localsync()
  datalad/support/annexrepo.py
Labels: :woman_facepalming:

#4264 TST: Pin git-annex version to 7.20191107 for windows CI runs
  .github/workflows/test_win2019.yml
  appveyor.yml
Labels: annex, windows

#4285 ENH: extend message for a NoDatasetArgumentFound in require_dataset
  datalad/core/local/tests/test_diff.py
  datalad/core/local/tests/test_run.py
  datalad/core/local/tests/test_status.py
  datalad/distribution/dataset.py
  datalad/interface/download_url.py
  datalad/interface/run_procedure.py
  datalad/interface/tests/test_unlock.py
  datalad/metadata/search.py
  datalad/metadata/tests/test_base.py
  datalad/metadata/tests/test_search.py
  datalad/plugin/wtf.py
  datalad/support/exceptions.py
Labels: UX, enhancement

#4290 DOC: Rephrase save(to_git=) docs to indicate lack of choice persistence
  datalad/core/local/save.py
Labels: documentation

#4319 ENH(UX): provide a hint on a deprecated add command
  datalad/cmdline/main.py
  datalad/interface/__init__.py
Labels: UX

#4332 BF: Avoid spurious backslashes in manpage double-dash option listings
  _datalad_build_support/formatters.py
Labels: UX, documentation

#4331 ENH: Warn when provided dataset to wtf does not exist
  datalad/plugin/wtf.py
Labels: UX

#4316 annexrepo: Tell caller that annex is scanning for unlocked files
  datalad/cmd.py
  datalad/support/annexrepo.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_annexrepo.py
Labels: merge-if-ok

#4337 RF: Suppress similar repeated messages in the default result renderer
  datalad/interface/utils.py
Labels: UX

#4341 OPT: use locally bound variables instead of dataset.repo and .config
  datalad/core/local/create.py
  datalad/distribution/dataset.py
  datalad/utils.py
Labels: merge-if-ok, performance

#4342 BF: set LC_ALL=C while running git
  .travis.yml
  datalad/cmd.py
Labels: merge-if-ok

#4353 Fixes for recent "suppressed similar messages" feature
  datalad/interface/tests/test_utils.py
  datalad/interface/utils.py
Labels: UX
