Repository datalad/datalad, pull requests merged in 2020-07, with the labels that each got.

#4692 OPT: Avoid multiple calls to `git-push` with multiple refspecs
  datalad/core/distributed/push.py
  datalad/support/gitrepo.py
Labels: documentation, performance

#4693 OPT: Consolidate on a single `git-push` call in `push()`
  datalad/core/distributed/push.py
  datalad/core/distributed/tests/test_push.py
  datalad/support/gitrepo.py
Labels: performance

#4682 ENH(UX): explicitly disallow empty string for --since in push
  datalad/core/distributed/push.py
  datalad/core/distributed/tests/test_push.py
Labels: merge-if-ok

#4696 RF/OPT: just assign None to linux_distribution*, and False to on_debian_wheezy
  datalad/support/annexrepo.py
  datalad/support/tests/test_annexrepo.py
  datalad/utils.py
Labels: merge-if-ok

#4729 BF: Readable SSH error messages
  datalad/support/sshconnector.py
Labels: UX

#4768 ENH+OPT(TST): annotate more of @slow tests, provide rule-of-thumb doc for @slow/turtle/..., fail if any non @slow exceeds 30 sec on travis
  .travis.yml
  datalad/__init__.py
  datalad/core/distributed/tests/test_clone.py
  datalad/core/distributed/tests/test_push.py
  datalad/core/local/tests/test_run.py
  datalad/distributed/tests/test_create_sibling_ria.py
  datalad/distributed/tests/test_ria_basics.py
  datalad/distributed/tests/test_ria_git_remote.py
  datalad/distribution/tests/test_create_sibling.py
  datalad/distribution/tests/test_publish.py
  datalad/distribution/tests/test_update.py
  datalad/interface/common_cfg.py
  datalad/interface/tests/test_add_archive_content.py
  datalad/interface/tests/test_ls_webui.py
  datalad/interface/tests/test_rerun_merges.py
  datalad/interface/tests/test_unlock.py
  datalad/local/tests/test_copy_file.py
  datalad/local/tests/test_subdataset.py
  datalad/metadata/tests/test_aggregation.py
  datalad/plugin/tests/test_addurls.py
  datalad/support/tests/test_annexrepo.py
  datalad/support/tests/test_fileinfo.py
  datalad/support/tests/test_repo_save.py
  datalad/tests/utils.py
Labels: merge-if-ok
