Repository datalad/datalad, pull requests merged in 2020-01, with the labels that each got.

#3975 Enabled testrepo-based tests on Windows
  appveyor.yml
  datalad/core/local/tests/test_run.py
  datalad/core/local/tests/test_save.py
  datalad/distribution/tests/test_clone.py
  datalad/distribution/tests/test_dataset.py
  datalad/distribution/tests/test_get.py
  datalad/distribution/tests/test_install.py
  datalad/distribution/tests/test_publish.py
  datalad/distribution/tests/test_uninstall.py
  datalad/distribution/tests/test_update.py
  datalad/interface/tests/test_unlock.py
  datalad/local/tests/test_subdataset.py
  datalad/support/network.py
  datalad/support/tests/test_annexrepo.py
  datalad/support/tests/test_gitrepo.py
  datalad/support/tests/test_network.py
  datalad/tests/test_auto.py
  datalad/tests/test_testrepos.py
  datalad/tests/test_utils_testrepos.py
  datalad/tests/utils.py
  datalad/tests/utils_testrepos.py
Labels: bug-windows

#3979 BF: Implement workaround for file:// URL compatibility on Windows
  datalad/distribution/clone.py
  datalad/support/gitrepo.py
  datalad/support/network.py
  datalad/support/tests/test_gitrepo.py
  datalad/support/tests/test_network.py
  datalad/tests/utils_testrepos.py
Labels: merge-if-ok

#3978 NF: ConfigManager.???(where='override')
  datalad/config.py
  datalad/tests/test_config.py
Labels: UX, enhancement, merge-if-ok

#3993 Prepare 0.12 release
  CHANGELOG.md
  datalad/version.py
Labels: It's huge!

#4013 BF: Properly handle directory separators on Windows (fixes gh-2566)
  appveyor.yml
  datalad/tests/test_utils.py
  datalad/utils.py
Labels: bug-windows, merge-if-ok

#4022 Towards supporting access to RIA stores in clone()
  datalad/core/distributed/clone.py
  datalad/core/distributed/tests/test_clone.py
  datalad/distribution/tests/test_install.py
  datalad/distribution/utils.py
Labels: merge-if-ok

#4036 NF: Support cloning of specific repository versions (fixes gh-2109)
  datalad/core/distributed/clone.py
  datalad/core/distributed/tests/test_clone.py
  datalad/support/gitrepo.py
Labels: merge-if-ok

#4039 RF: Move all patool code into a dedicated code file
  datalad/support/archive_utils_patool.py
  datalad/support/archives.py
  datalad/tests/test_archives.py
Labels: merge-if-ok

#4037 NF: Clone of subdatasets uses reckless mode of superdataset (fixes gh-4030)
  datalad/core/distributed/clone.py
  datalad/core/distributed/tests/test_clone.py
  datalad/interface/common_opts.py
Labels: merge-if-ok

#4041 7z-based (optional) replacement for patool
  .github/workflows/docbuild.yml
  .travis.yml
  appveyor.yml
  datalad/interface/download_url.py
  datalad/interface/tests/test_download_url.py
  datalad/support/archive_utils_7z.py
  datalad/support/archives.py
  datalad/support/external_versions.py
  datalad/tests/test_archives.py
Labels: merge-if-ok

#4064 NF: Helper to support Git-style URL rewriting
  datalad/config.py
  datalad/core/distributed/clone.py
  datalad/core/distributed/tests/test_clone.py
  datalad/tests/test_config.py
Labels: merge-if-ok

#4095 OPT: tried to be "clever" AKA "smart" and reuse .repo (and .config)
  datalad/config.py
  datalad/core/local/create.py
  datalad/distribution/dataset.py
Labels: performance, severity-minor
