Repository datalad/datalad, pull requests merged in 2020-02, with the labels that each got.

#4106 BF: Don't be silent in default renderer when everything is clean
  datalad/core/local/status.py
Labels: UX, merge-if-ok

#4046 NF: Intersphinx mapping to link to handbook content (fixes gh-4034)
  datalad/core/distributed/clone.py
  datalad/interface/base.py
  docs/Makefile
  docs/source/conf.py
Labels: documentation, merge-if-ok

#4080 WitlessRunner() to replace gitpy.Repo.clone_from() with plain `git-clone` call, but keep progress reporting
  appveyor.yml
  datalad/cmd.py
  datalad/core/distributed/clone.py
  datalad/log.py
  datalad/support/exceptions.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_annexrepo.py
  datalad/tests/test_witless_runner.py
Labels: merge-if-ok

#4122 RF: Turn GitRepo non-method into standalone function
  datalad/cmd.py
  datalad/support/annexrepo.py
  datalad/support/gitrepo.py
Labels: DX

#4123 RF: Make runner code (subjectively) more readable
  datalad/cmd.py
Labels: DX

#4081 BF/ENH: get_size_from_key to match specification
  datalad/support/annexrepo.py
  datalad/support/tests/test_annexrepo.py
Labels: merge-if-ok

#4099 NF: clone: --reckless='ephemeral'
  datalad/core/distributed/clone.py
  datalad/core/distributed/tests/test_clone.py
  datalad/interface/common_opts.py
  datalad/tests/utils.py
  datalad/utils.py
Labels: merge-if-ok

#4140 BF: export-to-figshare - make default title include #id@version, ask for the title in UI
  datalad/plugin/export_to_figshare.py
  datalad/plugin/tests/test_export_to_figshare.py
Labels: external-integration, merge-if-ok

#4087 GitRepo.fetch/pull/push() without GitPython
  datalad/core/distributed/clone.py
  datalad/distribution/publish.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_gitrepo.py
Labels: merge-if-ok

#4160 tests: Improve display of results in assertion messages
  datalad/tests/utils.py
Labels: DX

#4065 Bits to make bare repositories a more recognized use case
  datalad/core/local/create.py
  datalad/tests/test_config.py
Labels: bare-mode, merge-if-ok

#4158 Removal of obsolete add/save (2nd attempt)
  benchmarks/api.py
  benchmarks/core.py
  benchmarks/usecases.py
  datalad/core/local/tests/test_save.py
  datalad/distribution/add.py
  datalad/distribution/tests/test_add.py
  datalad/interface/__init__.py
  datalad/interface/save.py
  datalad/interface/tests/test_run_procedure.py
  datalad/interface/tests/test_save.py
  datalad/metadata/aggregate.py
  datalad/support/annexrepo.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_gitrepo.py
  docs/casts/heudiconv_dicom_to_bids.sh
  docs/casts/reproducible_analysis.sh
  docs/examples/3rdparty_analysis_workflow.sh
  docs/source/basics_cmdline.rst.in
  docs/source/cmdline.rst
  docs/source/modref.rst
Labels: merge-if-ok

#4124 NF: create-sibling-ria command
  .travis.yml
  datalad/core/distributed/clone.py
  datalad/distributed/create_sibling_ria.py
  datalad/distributed/ria_utils.py
  datalad/distributed/tests/test_create_sibling_ria.py
  datalad/distribution/publish.py
  datalad/interface/__init__.py
  docs/source/cmdline.rst
Labels: do-in-datalad

#4156 RF: GitRepo.commit() based on WitlessRunner
  datalad/support/gitrepo.py
  datalad/support/tests/test_gitrepo.py
Labels: merge-if-ok

#4147 ENH: safe-guard --existing-replace for cases of populated directories
  datalad/distribution/create_sibling.py
  datalad/distribution/tests/test_create_sibling.py
Labels: UX, feedback-desired, fix-implemented, merge-if-ok, severity-critical, severity-important

#4168 CLN: Remove obsolete AnnexRepo.commit()
  datalad/support/annexrepo.py
  datalad/support/tests/test_annexrepo.py
Labels: merge-if-ok

#4177 ENH: add "DataLad extension" to terms glossary
  docs/source/customization.rst
  docs/source/glossary.rst
Labels: documentation

#4157 ENH: Prefer structured over rendered CommandError info
  datalad/cmd.py
  datalad/cmdline/main.py
  datalad/distribution/siblings.py
  datalad/support/exceptions.py
  datalad/support/gitrepo.py
  datalad/utils.py
Labels: UX

#4189 ENH: Disable `siblings` output for freshly created sibling
  datalad/distribution/create_sibling.py
Labels: UX, merge-if-ok

#4212 BF(workaround): position --debug AFTER other annex_options
  datalad/support/annexrepo.py
Labels: merge-if-ok

#4200 BF: allow for fetch to fail due to HEAD not yet been available on a remote for annex
  datalad/distribution/publish.py
  datalad/distribution/tests/test_publish.py
Labels: merge-if-ok
