Repository datalad/datalad, pull requests merged in 2020-09, with the labels that each got.

#4699 RF: Use WitlessRunner for config manager
  datalad/cmd.py
  datalad/config.py
  datalad/support/external_versions.py
  datalad/support/tests/test_external_versions.py
Labels: merge-if-ok

#4793 OPT: Bypass `submodule add` when adding subdatasets
  datalad/config.py
  datalad/support/gitrepo.py
  datalad/tests/test_config.py
Labels: merge-if-ok, performance

#4867 OPT: addurls - no add per file, mock.patch once per dataset
  benchmarks/plugins/__init__.py
  benchmarks/plugins/addurls.py
  datalad/plugin/addurls.py
Labels: performance

#4869 ENH: Add separate asv compare step within Benchmarks
  .github/workflows/benchmarks.yml
Labels: DX, enhancement

#4764 ENH: provide INFO level logging for an action about to be reran
  datalad/interface/rerun.py
Labels: merge-if-ok

#4824 BF: fix authentication + download from S3 for NDA
  datalad/downloaders/credentials.py
  datalad/downloaders/s3.py
  datalad/downloaders/tests/test_s3.py
  datalad/interface/common_cfg.py
  datalad/support/s3.py
  datalad/support/third/nda_aws_token_generator.py
Labels: merge-if-ok

#4683 RF: make publish understand --since=^ and deprecate --since=
  datalad/distribution/publish.py
  datalad/distribution/tests/test_publish.py
Labels: UX, merge-if-ok

#4853 RF: Bypass `git-submodule update --init` when getting subdatasets
  datalad/distribution/get.py
  datalad/distribution/tests/test_get.py
Labels: merge-if-ok, performance

#4886 Make it a bit easier to see cruft when doing large-scale sweeps through the code
  datalad/interface/ls.py
  datalad/support/gitrepo.py
  datalad/support/stats.py
  datalad/support/tests/test_external_versions.py
  datalad/tests/test_utils.py
  datalad/utils.py
Labels: DX

#4879 RF: Require Python >=3.6
  .github/workflows/test_crippled.yml
  .travis.yml
  CONTRIBUTING.md
  appveyor.yml
  datalad/utils.py
  setup.py
  tox.ini
Labels: conference agenda item

#4448 ENH: add ..HEAD to since statement if defined upon publish
  datalad/distribution/publish.py
  datalad/distribution/tests/test_publish.py
Labels: merge-if-ok

#4628 CONTRIBUTING.md: tune up to section formatting + release etc workflow draft
  CONTRIBUTING.md
Labels: DX, merge-if-ok

#4939 BF: declare minimal version of fasteners to be 0.14
  setup.py
Labels: merge-if-ok

#4937 ENH: make it possible to debug batched annex
  datalad/cmd.py
  datalad/support/annexrepo.py
Labels: DX

#4931 ENH+RF: @try_multiple_dec_s3 to retry interaction with S3 upon "retriable" errors
  datalad/downloaders/base.py
  datalad/downloaders/credentials.py
  datalad/downloaders/s3.py
  datalad/downloaders/tests/test_credentials.py
  datalad/downloaders/tests/test_s3.py
  datalad/support/annexrepo.py
  datalad/support/exceptions.py
  datalad/support/s3.py
  datalad/utils.py
Labels: merge-if-ok

#4952 downloader: handle non-utf8 files being downloaded
  datalad/downloaders/base.py
  datalad/downloaders/http.py
  datalad/downloaders/s3.py
  datalad/downloaders/tests/test_http.py
  datalad/utils.py
Labels: merge-if-ok

#4965 Don't move .coverage out of __testhome__
  .travis.yml
Labels: merge-if-ok

#4960 ENH(DX): Make DATALAD_LOG_OUTPUTS trigger logging of swallowed ouputs as well
  datalad/utils.py
Labels: DX, merge-if-ok
