Repository datalad/datalad, pull requests merged in 2020-12, with the labels that each got.

#5194 BF: drop: Adjust annex's "use --force" message to avoid confusion
  datalad/distribution/drop.py
  datalad/distribution/tests/test_drop.py
Labels: UX

#5070 OPT+BF: annotate read_only git/annex invocations, thread lock read-write git/annex and git-config invocations
  datalad/config.py
  datalad/support/annexrepo.py
  datalad/support/gitrepo.py
Labels: do-in-parallel, merge-if-ok, performance

#5195 RF: remove hardcoded mapping to jobs=0 in get._recursive_install_subds_underneath
  datalad/distribution/get.py
Labels: do-in-parallel, performance

#5218 RF+BF: github - remove user/password authentication, use only tokens
  datalad/consts.py
  datalad/distribution/create_sibling_github.py
  datalad/distribution/tests/test_create_github.py
  datalad/distribution/tests/vcr_cassettes/github_datalad_tester.yaml
  datalad/distribution/tests/vcr_cassettes/github_datalad_tester_org.yaml
  datalad/distribution/tests/vcr_cassettes/github_yarikoptic.yaml
  datalad/support/github_.py
  datalad/support/tests/test_github_.py
Labels: merge-if-ok

#5223 Reincarnate appveyor coverage
  appveyor.yml
Labels: merge-if-ok

#5247 Few fixes that address runner behavior
  datalad/support/annexrepo.py
  datalad/support/tests/test_annexrepo.py
Labels: merge-if-ok

#5246 Make diffstatus decision making more accessible
  datalad/core/local/tests/test_save.py
  datalad/support/gitrepo.py
Labels: merge-if-ok

#5241 Proper handling of nested datasets in save/push/clone cycle
  datalad/config.py
  datalad/core/distributed/clone.py
  datalad/core/distributed/tests/test_clone.py
  datalad/core/distributed/tests/test_push.py
  datalad/core/local/save.py
  datalad/core/local/tests/test_save.py
  datalad/distribution/get.py
  datalad/distribution/tests/test_update.py
  datalad/metadata/tests/test_base.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_annexrepo.py
  datalad/tests/utils.py
Labels: adjusted-branches, severity-critical
