Repository datalad/datalad, pull requests merged in 2020-11, with the labels that each got.

#4843 ENH: add exception_traceback ("unlimited") to the status dict if exception is passed into get_status_dict
  datalad/dochelpers.py
  datalad/interface/download_url.py
  datalad/interface/results.py
  datalad/tests/test_dochelpers.py
Labels: DX

#5119 BF: workarounds to tests on Windows
  datalad/customremotes/tests/test_archives.py
  tools/which.py
Labels: windows

#5136 Fix path and URL handling in ORA remote and associated tests
  datalad/core/distributed/tests/test_clone.py
  datalad/distributed/ora_remote.py
Labels: windows

#5002 RF: Stop using old-Runner in `run`
  datalad/core/local/run.py
Labels: merge-if-ok

#5005 ENH: Allow experimenting with interactive commit-message entry
  datalad/interface/common_cfg.py
  datalad/support/gitrepo.py
Labels: UX, merge-if-ok

#4917 Enh wtf short
  datalad/plugin/tests/test_plugins.py
  datalad/plugin/wtf.py
Labels: enhancement, merge-if-ok

#5156 ENH: datalad.locations.extra-procedures to provide extra location(s) for procedures
  datalad/interface/common_cfg.py
  datalad/interface/run_procedure.py
  datalad/interface/tests/test_run_procedure.py
Labels: enhancement, merge-if-ok
