Repository datalad/datalad, pull requests merged in 2020-10, with the labels that each got.

#4972 ENH: add shellcheck run on shell scripts which ATM are shellcheck kosher
  .github/workflows/shellcheck.yml
Labels: DX, enhancement

#4955 OPT: gen_URLS (to replace get_URLS) - query schemes in order of prior "successes"
  datalad/customremotes/archives.py
  datalad/customremotes/base.py
  datalad/customremotes/datalad.py
Labels: merge-if-ok, performance

#4982 ENH: Show info on credential setup in wtf()
  datalad/plugin/wtf.py
Labels: UX

#4957 ENH: more obscurity - add ', ", and {} to obscure filenames
  datalad/interface/run_procedure.py
  datalad/metadata/metadata.py
  datalad/tests/utils.py
  datalad/utils.py
Labels: merge-if-ok

#5011 RF: Strip `AnnotatePaths` from `create_sibling()`
  datalad/distribution/create_sibling.py
  datalad/distribution/tests/test_publish.py
Labels: corpse-in-basement

#5012 RF: Strip `AnnotatePaths` from `drop()`
  datalad/distribution/drop.py
Labels: merge-if-ok

#4996 Runner -- shot of mercy
  datalad/cmd.py
  datalad/core/distributed/clone.py
  datalad/core/distributed/tests/test_clone.py
  datalad/core/local/tests/test_diff.py
  datalad/distributed/ora_remote.py
  datalad/distributed/tests/test_ria_basics.py
  datalad/distribution/create_sibling.py
  datalad/distribution/tests/test_publish.py
  datalad/interface/diff.py
  datalad/interface/tests/test_base.py
  datalad/interface/tests/test_diff.py
  datalad/interface/tests/test_ls_webui.py
  datalad/interface/tests/test_run_procedure.py
  datalad/plugin/tests/test_addurls.py
  datalad/plugin/wtf.py
  datalad/support/annexrepo.py
  datalad/support/archive_utils_7z.py
  datalad/support/gitrepo.py
  datalad/support/sshconnector.py
  datalad/support/tests/test_annexrepo.py
  datalad/support/tests/test_gitrepo.py
  datalad/support/tests/test_sshrun.py
  datalad/tests/test_installed.py
  datalad/tests/test_testrepos.py
  datalad/tests/test_utils.py
  datalad/tests/test_witless_runner.py
  datalad/tests/utils.py
Labels: merge-if-ok

#5051 BF: push - do not call localsync unless annex
  datalad/core/distributed/push.py
  datalad/core/distributed/tests/test_push.py
Labels: merge-if-ok

#5025 BF: RIA clone HTTP403 handling and support authenticated access
  datalad/core/distributed/clone.py
  datalad/downloaders/tests/test_http.py
  datalad/support/network.py
Labels: merge-if-ok

#4963 NF: add infrastructure for specialized indexers
  datalad/metadata/indexers/__init__.py
  datalad/metadata/indexers/base.py
  datalad/metadata/search.py
  datalad/metadata/tests/test_search.py
  datalad/plugin/wtf.py
Labels: metadata

#5060 OPT: Rate limit result suppression message update
  datalad/interface/tests/test_utils.py
  datalad/interface/utils.py
Labels: UX, performance

#4868 OPT: Speedup of per-subdataset "contains?" matching
  datalad/distribution/dataset.py
  datalad/distribution/update.py
  datalad/local/subdatasets.py
  datalad/local/tests/test_subdataset.py
  datalad/support/gitrepo.py
Labels: performance

#5076 OPT: Delay Dataset.repo access until necessary
  datalad/local/subdatasets.py
Labels: performance

#5052 ENH: added pragma to allow for no test coverage in case of ftp downloader on url which at times 503s
  datalad/downloaders/http.py
  datalad/downloaders/tests/test_http.py
Labels: merge-if-ok

#5090 NF: create-sibling-ria --storage-sibling only
  datalad/distributed/create_sibling_ria.py
  datalad/distributed/tests/test_create_sibling_ria.py
Labels: enhancement, merge-if-ok

#5022 NF+OPT+ENH: a helper to parallelize operations (via threads)
  datalad/core/distributed/tests/test_push.py
  datalad/core/local/save.py
  datalad/core/local/tests/test_save.py
  datalad/distribution/get.py
  datalad/interface/common_cfg.py
  datalad/log.py
  datalad/metadata/metadata.py
  datalad/plugin/addurls.py
  datalad/plugin/tests/test_addurls.py
  datalad/support/annexrepo.py
  datalad/support/collections.py
  datalad/support/itertools.py
  datalad/support/parallel.py
  datalad/support/sshconnector.py
  datalad/support/tests/test_parallel.py
  datalad/tests/test_log.py
  tools/ci/bisect-python.sh
Labels: UX, do-in-parallel, enhancement, merge-if-ok, performance

#5013 Revert "ENH: When closing batched processes avoid waiting forever"
  datalad/cmd.py
  datalad/interface/common_cfg.py
Labels: merge-if-ok
