Repository datalad/datalad, pull requests merged in 2020-05, with the labels that each got.

#4503 ENH: Overall progressbar for AnnexJsonProtocol
  datalad/core/distributed/push.py
  datalad/support/annexrepo.py
Labels: UX

#4524 RF: dissolve GitRepo._diffstatus by absorbing into diffstatus
  datalad/support/gitrepo.py
Labels: DX, enhancement

#4549 ENH: Disable full submodule evaluation for diff(to=!None)
  datalad/core/local/diff.py
Labels: merge-if-ok, performance

#4545 ENH: Delay query of `get_content_annex_info()` in `push()`
  datalad/core/distributed/push.py
Labels: merge-if-ok, performance

#4546 ENH: Give insight in push progress with a step-based progress bar
  datalad/core/distributed/push.py
  datalad/log.py
Labels: UX, merge-if-ok

#4547 ENH: Only evaluate and warn about content availability with explicit paths
  datalad/core/distributed/push.py
  datalad/core/distributed/tests/test_push.py
Labels: UX, merge-if-ok, performance

#4544 ENH: Avoid needless calls with diff(fr=None, annex=!None)
  datalad/core/distributed/push.py
  datalad/core/local/diff.py
  datalad/core/local/tests/test_diff.py
Labels: merge-if-ok, performance

#4553 RF: throw dedicated RuntimeError with information about question in case of SilentConsoleLog
  datalad/ui/dialog.py
  datalad/ui/tests/test_dialog.py
Labels: DX, UX, enhancement

#4555 BF: Prevent ugly interaction or result and progress reporting
  datalad/log.py
  datalad/ui/dialog.py
Labels: UX
