Repository datalad/datalad, pull requests merged in 2021-10, with the labels that each got.

#6013 Harmonize usage of --dry-run vs --dryrun in create-sibling-gitlab
  datalad/distributed/create_sibling_gitlab.py
  datalad/distributed/tests/test_create_sibling_gitlab.py
Labels: patch

#6023 BF: start global test_http_server only if not running already
  datalad/__init__.py
Labels: merge-if-ok, tests

#6010 Enable GitRepo method moves to -deprecated
  datalad/distribution/remove.py
  datalad/local/tests/test_subdataset.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_annexrepo.py
  datalad/support/tests/test_gitrepo.py
  datalad/tests/utils.py
Labels: merge-if-ok, minor

#6027 BF: disable outdated SSL root certificate breaking chain on older/buggy clients
  .appveyor.yml
  .travis.yml
  tools/ci/debians_disable_outdated_ssl_cert
Labels: merge-if-ok, tests

#6028 BF(TST): filter away warning from coverage from analysis of stderr of --help
  datalad/tests/test_installed.py
Labels: tests

#6032 Discontinue usage of deprecated (public) helper
  datalad/cmd.py
Labels: merge-if-ok, patch

#6033 Honor datalad.runtime.use-patool if set regardless of OS (was Windows only)
  datalad/support/archives.py
Labels: merge-if-ok, patch, release

#6037 Align installation setup with Travis
  .appveyor.yml
  datalad/metadata/tests/test_extract_metadata.py
Labels: tests

#6035 BF: Don't suppress datalad subdatasets output
  datalad/distribution/get.py
  datalad/local/subdatasets.py
Labels: patch

#6042 TST: Add test to ensure functionality with subdatasets starting with a hyphen (-)
  datalad/local/tests/test_subdataset.py
Labels: tests, release

#6128 Replace AnnotatePaths in metadata commands
  datalad/interface/annotate_paths.py
  datalad/metadata/aggregate.py
  datalad/metadata/metadata.py
  datalad/metadata/tests/test_aggregation.py
Labels: minor

#6120 TST: Enable all disabled tests listed in #5126 and more
  datalad/core/local/tests/test_run.py
  datalad/distribution/tests/test_dataset.py
  datalad/distribution/tests/test_get.py
  datalad/distribution/tests/test_install.py
  datalad/interface/tests/test_rerun.py
  datalad/interface/tests/test_rerun_merges.py
  datalad/interface/tests/test_run_procedure.py
Labels: internal

#6127 BF(TST): remove reuse of the same tape across unrelated tests
  datalad/core/distributed/tests/test_clone.py
  datalad/distribution/tests/test_install.py
Labels: tests

#6116 BF: Don't make create-sibling recursive by default
  datalad/distribution/create_sibling.py
  datalad/distribution/tests/test_create_sibling.py
Labels: patch, release
