Repository datalad/datalad, pull requests merged in 2021-04, with the labels that each got.

#5416 BF/RF: push - get diff depth-first not breadth-first
  datalad/core/distributed/push.py
  datalad/core/distributed/tests/test_push.py
  datalad/core/local/diff.py
Labels: cmd-push, merge-if-ok

#5543 ENH: Make --version output just version, and CMD --version output module and its version
  datalad/cmdline/common_args.py
  datalad/cmdline/helpers.py
  datalad/cmdline/main.py
  datalad/cmdline/tests/test_main.py
  datalad/core/local/tests/test_run.py
  datalad/customremotes/main.py
  datalad/interface/tests/test_base.py
Labels: merge-if-ok

#5554 Dissolve plugins
  .appveyor.yml
  .github/workflows/test_win2019_disabled
  datalad/api.py
  datalad/cmdline/tests/test_main.py
  datalad/distributed/export_to_figshare.py
  datalad/distributed/tests/test_export_to_figshare.py
  datalad/interface/__init__.py
  datalad/interface/base.py
  datalad/local/add_readme.py
  datalad/local/addurls.py
  datalad/local/check_dates.py
  datalad/local/export_archive.py
  datalad/local/no_annex.py
  datalad/local/tests/test_add_readme.py
  datalad/local/tests/test_addurls.py
  datalad/local/tests/test_check_dates.py
  datalad/local/tests/test_export_archive.py
  datalad/local/tests/test_no_annex.py
  datalad/local/tests/test_wtf.py
  datalad/local/wtf.py
  datalad/plugin/__init__.py
  datalad/plugin/add_readme.py
  datalad/plugin/addurls.py
  datalad/plugin/check_dates.py
  datalad/plugin/export_archive.py
  datalad/plugin/export_to_figshare.py
  datalad/plugin/no_annex.py
  datalad/plugin/wtf.py
  datalad/support/path.py
  datalad/tests/test_api.py
  docs/source/customization.rst
  docs/source/metadata.rst
  docs/source/modref.rst
Labels: corpse-in-basement, merge-if-ok

#5559 RF: Deprecate GitRepo.*_submodule() methods
  datalad/support/gitrepo.py
Labels: corpse-in-basement

#5555 RF: Move web UI into an extension
  .github/workflows/test_extensions.yml
  datalad/consts.py
  datalad/distribution/create_sibling.py
  datalad/distribution/tests/test_create_sibling.py
  datalad/resources/website/assets/css/jquery.dataTables-1.10.12.css
  datalad/resources/website/assets/css/main.css
  datalad/resources/website/assets/images/external-link-symbol.svg
  datalad/resources/website/assets/images/favicon-16x16.png
  datalad/resources/website/assets/images/favicon.ico
  datalad/resources/website/assets/images/favicon.svg
  datalad/resources/website/assets/images/logo_wide.svg
  datalad/resources/website/assets/images/sort_asc.png
  datalad/resources/website/assets/images/sort_both.png
  datalad/resources/website/assets/images/sort_desc.png
  datalad/resources/website/assets/js/jquery-2.2.4.js
  datalad/resources/website/assets/js/jquery.dataTables-1.10.12.js
  datalad/resources/website/assets/js/main.js
  datalad/resources/website/assets/js/md5-2.3.0.js
  datalad/resources/website/assets/js/showdown-1.8.5-33-g0c6ce94.js
  datalad/resources/website/index.html
  datalad/resources/website/tests/qunit/qunit-2.0.1.css
  datalad/resources/website/tests/qunit/qunit-2.0.1.js
  datalad/resources/website/tests/qunit/sinon-1.17.5.js
  datalad/resources/website/tests/qunit/sinon-qunit-1.0.0.js
  datalad/resources/website/tests/test.html
Labels: corpse-in-basement, merge-if-ok

#5551 Bring create-sibling-github to the modern age
  datalad/distribution/create_sibling_github.py
  datalad/distribution/tests/test_create_github.py
  datalad/interface/base.py
  datalad/support/github_.py
  datalad/support/tests/test_github_.py
Labels: cmd-create-sibling-github, corpse-in-basement

#5544 ENH: datalad shell-completion helper
  datalad/interface/__init__.py
  datalad/interface/shell_completion.py
  datalad/interface/tests/test_shell_completion.py
  docs/source/cmdline.rst
Labels: merge-if-ok

#5558 RF: Remove GitRepo.pull()
  datalad/support/gitrepo.py
  datalad/support/tests/test_gitrepo.py
Labels: corpse-in-basement

#5560 RF: Deprecate AnnexRepo.copy_to()
  datalad/support/annexrepo.py
Labels: corpse-in-basement

#5605 ENH: external_versions - add lookup table for github -> pygithub
  datalad/support/external_versions.py
  datalad/support/tests/test_external_versions.py
Labels: DX

#5575 RF: centralize logic on either @eval_results used, remove need for _OLDSTYLE_COMMANDS
  datalad/distribution/create_sibling.py
  datalad/distribution/create_sibling_github.py
  datalad/distribution/create_test_dataset.py
  datalad/distribution/publish.py
  datalad/interface/base.py
  datalad/interface/test.py
  datalad/interface/tests/test_base.py
  datalad/interface/utils.py
  datalad/support/sshrun.py
Labels: DX, enhancement, feedback-desired

#5612 BF(TST): use sys.executable and not hardcoded "python"
  datalad/interface/tests/test_run_procedure.py
Labels: merge-if-ok
