Repository datalad/datalad, pull requests merged in 2021-08, with the labels that each got.

#5850 addurls Formatter - provide value repr in exception
  datalad/plugin/addurls.py
  datalad/plugin/tests/test_addurls.py
Labels: UX, patch

#5855 TST: set --allow-unrelated-histories in the mk_push_target setup for Windows
  datalad/core/distributed/tests/test_push.py
Labels: internal, platform-windows, tests

#5847 Append (not prepend) a newline character(s) to .gitattributes for prettier appearance
  datalad/support/gitrepo.py
  datalad/support/tests/test_gitrepo.py
Labels: enhancement, minor

#5852 BF: http_auth - follow redirect (just 1) to re-authenticate after initial attempt
  datalad/downloaders/configs/nsidc.cfg
  datalad/downloaders/http.py
  datalad/downloaders/tests/test_http.py
Labels: cmd-download-url, merge-if-ok, patch

#5839 UX: When two or more clone URL templates are found, error out more gracefully
  datalad/distribution/get.py
  datalad/distribution/tests/test_get.py
Labels: UX, patch, release

#5866 Add project URLs into the package metadata for convenience links on Pypi
  setup.py
Labels: documentation, internal

#5738 Dry run option for clean command
  datalad/customremotes/archives.py
  datalad/customremotes/tests/test_archives.py
  datalad/interface/clean.py
  datalad/interface/tests/test_clean.py
Labels: minor

#5708 ENH(UX): state original purpose in NoDatasetFound exception + detail it for get
  datalad/distribution/dataset.py
  datalad/distribution/get.py
Labels: enhancement, UX, merge-if-ok, patch

#5689 addurls: Improve result displayed for subdataset creation
  datalad/local/addurls.py
  datalad/local/tests/test_addurls.py
Labels: cmd-addurls

#5875 ENH(UX): warn user if keyring returned a "null" keyring
  datalad/support/keyring_.py
Labels: UX, merge-if-ok, patch

#5869 Log level design -- a start
  .appveyor.yml
  docs/source/design/index.rst
  docs/source/design/log_levels.rst
Labels: documentation

#5868 DOC: Design document for the `dataset` argument
  docs/source/basics.rst
  docs/source/design/dataset_argument.rst
  docs/source/design/index.rst
  docs/source/glossary.rst
  docs/source/index.rst
Labels: documentation

#5881 BF: take path from SSHRI, test URLs not only on Windows
  datalad/core/distributed/clone.py
  datalad/core/distributed/tests/test_clone.py
Labels: patch

#5888 .travis.yml: use python -m {nose,coverage} invocations, and always show combined report
  .travis.yml
Labels: merge-if-ok, internal

#5887 RF: use https:// for datasets*.datalad.org
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  datalad/__init__.py
  datalad/consts.py
  datalad/tests/test_tests_utils.py
  docs/casts/basic_search.sh
  docs/casts/publish_on_github.sh
  docs/casts/reproducible_analysis.sh
  docs/source/basics.rst
  docs/source/changelog.rst
  docs/source/metadata.rst
  tools/ci/appveyor_install_git-annex.bat
Labels: merge-if-ok, internal

#5894 BF(TST): Boost version of git-annex to 8.20201129 to test an error message
  datalad/cmdline/tests/test_main.py
Labels: tests

#5837 Remove `publish` from -core (placed into `datalad_deprecated`)
  datalad/core/distributed/tests/test_clone.py
  datalad/distributed/tests/test_ria.py
  datalad/distribution/publish.py
  datalad/distribution/tests/test_create_sibling.py
  datalad/distribution/tests/test_install.py
  datalad/distribution/tests/test_publish.py
  datalad/distribution/tests/test_update.py
  datalad/interface/__init__.py
  datalad/metadata/tests/test_aggregation.py
  docs/source/cmdline.rst
  docs/source/metadata.rst
  docs/source/modref.rst
Labels: merge-if-ok, minor

#5459 Overhaul ORA remote's HTTP access to RIA stores
  datalad/distributed/ora_remote.py
  datalad/distributed/tests/test_ora_http.py
Labels: minor

#5441 RM: deprecated no_annex Python API option
  datalad/core/local/create.py
Labels: severity-minor, blocked

#5867 Design proposal for dropping content
  docs/source/design/drop.rst
  docs/source/design/index.rst
Labels: documentation, cmd-drop, cmd-uninstall

#5897 Fixup after #5441 which only removed half of `no_annex`
  datalad/core/local/create.py
  datalad/core/local/tests/test_save.py
Labels: internal

#5899 Use platform-appropriate "echo" calls in tests
  datalad/tests/test_nonasyncrunner.py
  datalad/tests/test_witless_runner.py
Labels: internal

#5904 Limit use of default annex.retry=3 to `get` and `copy` operations
  datalad/core/distributed/push.py
  datalad/support/annexrepo.py
Labels: merge-if-ok, patch

#5902 Support username, password and port specification in RIA URLs
  datalad/customremotes/ria_utils.py
  datalad/customremotes/tests/test_ria_utils.py
Labels: merge-if-ok, patch

#5907 Clarify error message re unspecified gitlab project
  datalad/distributed/create_sibling_gitlab.py
Labels: patch

#5913 Fix argument-spec for `siblings` and improve usage synopsis
  datalad/distribution/siblings.py
Labels: patch

#5892 BF: do not crash, just skip whenever trying to delete non existing field in the underlying keyring
  datalad/downloaders/tests/test_credentials.py
  datalad/support/keyring_.py
Labels: UX, merge-if-ok, credentials, patch

#5915 Render siblings()'s non-ok results with the default renderer
  datalad/distribution/siblings.py
Labels: UX, patch

#5884 Download session/credentials locking -- inform user if locking is "failing" to be obtained, fail upon ~5min timeout
  datalad/downloaders/base.py
  datalad/support/locking.py
  datalad/support/tests/test_locking.py
Labels: UX, merge-if-ok, credentials, patch

#5917 MNT: Merge `maint` into `master`
  datalad/distribution/siblings.py
  datalad/downloaders/base.py
  datalad/downloaders/tests/test_credentials.py
  datalad/support/keyring_.py
  datalad/support/locking.py
  datalad/support/tests/test_locking.py
Labels: internal

#5909 Write down implicit rules for import statements in the code base
  docs/source/design/index.rst
  docs/source/design/python_imports.rst
Labels: documentation

#5921 Some love and fixes for `siblings`
  datalad/distribution/siblings.py
  datalad/distribution/tests/test_siblings.py
  datalad/support/gitrepo.py
Labels: patch

#5920 BF(TST): Skip testing for having PID listed if no psutil
  datalad/support/tests/test_locking.py
Labels: tests

#5923 Add isort config to match current convention + run isort via pre-commit (if configured)
  .pre-commit-config.yaml
  pyproject.toml
Labels: internal

#5916 Provide a few more hints whenever user just runs `datalad`
  datalad/cmdline/helpers.py
Labels: documentation, UX, merge-if-ok

#5924 RF: minor - define only common worker kwargs in a reused dict
  datalad/distribution/siblings.py
Labels: internal
