Repository datalad/datalad, pull requests merged in 2021-02, with the labels that each got.

#5431 NF: run, rerun: Add --assume-ready option
  datalad/core/local/run.py
  datalad/core/local/tests/test_run.py
  datalad/interface/rerun.py
  datalad/interface/tests/test_rerun.py
Labels: cmd-run/rerun

#5433 BF(TST,workaround): skip stalling on travis NFS test
  datalad/support/tests/test_annexrepo.py
Labels: merge-if-ok

#5438 ENH(UX): set "smoothing=0" for any progress bar with "total" in its label
  datalad/ui/progressbars.py
Labels: UX
