Repository datalad/datalad, pull requests merged in 2021-12, with the labels that each got.

#6262 ENH: enable recursive glob (**) for `run`
  datalad/core/local/run.py
  datalad/support/globbedpaths.py
  datalad/support/tests/test_globbedpaths.py
Labels: semver-minor

#6251 TST: no HOME change on OSX
  datalad/__init__.py
  datalad/tests/test_base.py
  datalad/tests/test_config.py
Labels: semver-tests

#6261 DOC: positional vs kwargs design doc
  docs/source/design/index.rst
  docs/source/design/pos_vs_kw_parameters.rst
Labels: semver-documentation

#6271 Cleanup datalad/__init__.py
  datalad/__init__.py
  datalad/utils.py
Labels: semver-internal

#6267 Enable ORA remote to recover from an interupted upload
  datalad/customremotes/ria_utils.py
  datalad/distributed/ora_remote.py
Labels: semver-patch

#6244 Generator-style runner with application in BatchedCommand and AnnexRepo
  datalad/cmd.py
  datalad/runner/exception.py
  datalad/runner/gitrunner.py
  datalad/runner/nonasyncrunner.py
  datalad/runner/protocol.py
  datalad/runner/runner.py
  datalad/runner/runnerthreads.py
  datalad/runner/tests/test_exception.py
  datalad/runner/tests/test_generatormixin.py
  datalad/runner/tests/test_gitrunner.py
  datalad/runner/tests/test_nonasyncrunner.py
  datalad/runner/tests/test_utils.py
  datalad/runner/tests/test_witless_runner.py
  datalad/runner/tests/utils.py
  datalad/runner/utils.py
  datalad/support/annexrepo.py
  datalad/support/tests/test_annexrepo.py
  datalad/tests/test_cmd.py
  docs/source/design/batched_command.rst
  docs/source/design/index.rst
  docs/source/design/threaded_runner.rst
Labels: semver-minor

#6268 Discontinue use of and deprecate get_repo_instance()
  datalad/cmdline/helpers.py
  datalad/customremotes/archives.py
  datalad/tests/utils.py
Labels: semver-internal

#6213 API mode indicator and library-mode enabling switch
  datalad/__init__.py
  datalad/api.py
  datalad/cmdline/main.py
  datalad/cmdline/tests/test_main.py
  datalad/interface/base.py
  datalad/support/tests/test_sshrun.py
  docs/source/design/application_vs_library_mode.rst
  docs/source/design/index.rst
Labels: semver-minor, library-mode

#6280 Stop swallowing to-be-rendered results based on prior logging assumption
  datalad/core/local/status.py
  datalad/local/run_procedure.py
  datalad/metadata/metadata.py
Labels: semver-patch

#6277 UX: When calling uninstall without nocheck, strip hints for drops reckless parameter
  datalad/distribution/uninstall.py
Labels: semver-patch

#6279 ENH: Add parallel jobs options for `run` and `rerun` (applies to get, save)
  datalad/core/local/run.py
  datalad/local/rerun.py
Labels: semver-minor

#6278 Generator-based GitRepo.call_git_items_()
  datalad/dataset/gitrepo.py
  datalad/dataset/tests/test_gitrepo.py
  datalad/runner/runner.py
  datalad/runner/utils.py
  datalad/support/annexrepo.py
  datalad/support/tests/test_gitrepo.py
  datalad/utils.py
Labels: semver-internal

#6286 Bump the python version used for mac os tests
  .github/workflows/test_macos.yml
Labels: semver-tests

#6288 bump the python version used for mac os tests
  .github/workflows/test_macos.yml
Labels: semver-tests

#6283 Add a missing import of CapturedException
  datalad/support/annexrepo.py
  datalad/support/tests/test_annexrepo.py
Labels: semver-internal

#5517 NF: foreach-dataset
  datalad/core/distributed/tests/test_clone.py
  datalad/core/distributed/tests/test_push.py
  datalad/core/local/tests/test_create.py
  datalad/distributed/create_sibling_ghlike.py
  datalad/distributed/create_sibling_gitlab.py
  datalad/distributed/create_sibling_ria.py
  datalad/distributed/drop.py
  datalad/distribution/create_sibling.py
  datalad/distribution/get.py
  datalad/distribution/siblings.py
  datalad/distribution/tests/test_create_sibling.py
  datalad/distribution/tests/test_dataset.py
  datalad/distribution/tests/test_get.py
  datalad/distribution/tests/test_install.py
  datalad/distribution/uninstall.py
  datalad/distribution/update.py
  datalad/interface/__init__.py
  datalad/interface/annotate_paths.py
  datalad/interface/common_opts.py
  datalad/local/clean.py
  datalad/local/foreach_dataset.py
  datalad/local/subdatasets.py
  datalad/local/tests/test_foreach_dataset.py
  datalad/local/tests/test_subdataset.py
  datalad/support/constraints.py
  datalad/support/parallel.py
  datalad/tests/test_constraints.py
  datalad/tests/utils.py
  docs/source/cmdline.rst
Labels: semver-minor

#6292 CI: Update environment for windows CI builds
  .appveyor.yml
  tools/ci/appveyor_install_git-annex.bat
Labels: semver-tests

#6293 Fix invalid escape sequences
  datalad/cmdline/tests/test_main.py
  datalad/customremotes/tests/test_archives.py
  datalad/customremotes/tests/test_base.py
  datalad/customremotes/tests/test_datalad.py
  datalad/downloaders/tests/test_http.py
  datalad/downloaders/tests/test_providers.py
  datalad/interface/tests/test_add_archive_content.py
  datalad/metadata/tests/test_search.py
  datalad/support/tests/test_captured_exception.py
  datalad/support/tests/test_network.py
  datalad/support/tests/test_versions.py
  datalad/tests/test_archives.py
  datalad/tests/test_log.py
Labels: semver-patch

#6289 DOC: Update examples in create_sibling_gin
  datalad/distributed/create_sibling_gin.py
Labels: semver-documentation

#6287 BF: RIARemote - set UI backend to annex to make it interactive
  datalad/distributed/ora_remote.py
Labels: semver-patch

#6276 Allow other URLs than local file as dataset parameter
  datalad/interface/utils.py
Labels: semver-internal

#6176 ENH/RF: Interface-s - add * to explicitly separate posargs from kwargs
  benchmarks/plugins/addurls.py
  datalad/core/distributed/clone.py
  datalad/core/distributed/push.py
  datalad/core/local/create.py
  datalad/core/local/diff.py
  datalad/core/local/run.py
  datalad/core/local/save.py
  datalad/core/local/status.py
  datalad/distributed/create_sibling_gin.py
  datalad/distributed/create_sibling_gitea.py
  datalad/distributed/create_sibling_github.py
  datalad/distributed/create_sibling_gitlab.py
  datalad/distributed/create_sibling_gogs.py
  datalad/distributed/create_sibling_ria.py
  datalad/distributed/drop.py
  datalad/distributed/export_archive_ora.py
  datalad/distributed/export_to_figshare.py
  datalad/distribution/create_sibling.py
  datalad/distribution/create_test_dataset.py
  datalad/distribution/dataset.py
  datalad/distribution/get.py
  datalad/distribution/install.py
  datalad/distribution/siblings.py
  datalad/distribution/tests/test_dataset_binding.py
  datalad/distribution/tests/test_install.py
  datalad/distribution/uninstall.py
  datalad/distribution/update.py
  datalad/interface/base.py
  datalad/interface/test.py
  datalad/local/add_archive_content.py
  datalad/local/add_readme.py
  datalad/local/addurls.py
  datalad/local/check_dates.py
  datalad/local/clean.py
  datalad/local/copy_file.py
  datalad/local/download_url.py
  datalad/local/export_archive.py
  datalad/local/no_annex.py
  datalad/local/remove.py
  datalad/local/rerun.py
  datalad/local/run_procedure.py
  datalad/local/subdatasets.py
  datalad/local/tests/test_addurls.py
  datalad/local/tests/test_export_archive.py
  datalad/local/unlock.py
  datalad/local/wtf.py
  datalad/metadata/aggregate.py
  datalad/metadata/extract_metadata.py
  datalad/metadata/metadata.py
  datalad/metadata/search.py
  datalad/support/param.py
  datalad/support/sshrun.py
  datalad/tests/test_api.py
  datalad/tests/test_utils.py
  datalad/utils.py
Labels: semver-minor

#6304 BF: add positional args delimiter to `foreach_dataset`
  datalad/local/foreach_dataset.py
Labels: semver-internal

#6112 UX: If a clean repo is dirty after a failed run, give clean-up hints
  datalad/core/local/run.py
Labels: semver-internal

#6309 Minor enhancement to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: release, semver-documentation

#6311 Fix runner timeout test in windows
  datalad/runner/tests/test_nonasyncrunner.py
Labels: semver-tests

#6320 BF: autorc - replace incorrect releaseTypes with "none"
  .autorc
Labels: semver-internal, release

#6323 Free GitRepo.bare of its ConfigManager-dependency
  datalad/support/gitrepo.py
Labels: bare-mode, semver-minor

#6325 Reimplement _get_dot_git() to be more efficient
  datalad/dataset/gitrepo.py
  datalad/dataset/tests/test_gitrepo.py
  datalad/distribution/tests/test_utils.py
Labels: bare-mode, semver-minor
