Repository datalad/datalad, pull requests merged in 2021-03, with the labels that each got.

#5506 BF: AnnexJsonProtocol - memoize the last line which failed to json load
  datalad/__init__.py
  datalad/support/annexrepo.py
  datalad/support/tests/test_annexrepo.py
Labels: merge-if-ok

#5512 Bump minimum git-annex version to 8.20200309
  .travis.yml
  datalad/core/local/tests/test_run.py
  datalad/core/local/tests/test_save.py
  datalad/interface/tests/test_unlock.py
  datalad/support/annexrepo.py
  datalad/support/tests/test_annexrepo.py
  datalad/tests/test_direct_mode.py
  datalad/tests/utils.py
Labels: do not merge

#5516 RM: SafeConfigParserWithIncludes
  datalad/downloaders/providers.py
  datalad/interface/ls.py
  datalad/support/configparserinc.py
  docs/source/modref.rst
Labels: corpse-in-basement

#5010 BF/RF: GitRepo.push -- push first refspec separately first for github (or if remote.{remote}.datalad-push-default-first is set)
  datalad/config.py
  datalad/distribution/create_sibling_github.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_gitrepo.py
Labels: cmd-push, merge-if-ok

#5532 DOC: download-url: Add examples of path's trailing slash behavior
  datalad/interface/download_url.py
Labels: documentation
