Repository datalad/datalad, pull requests merged in 2021-09, with the labels that each got.

#5931 Let `siblings()` report on annex special remote configuration
  datalad/distribution/siblings.py
  datalad/distribution/tests/test_siblings.py
Labels: patch

#5934 Log result record message at DEBUG level by default
  datalad/interface/common_cfg.py
  datalad/interface/utils.py
Labels: minor

#5927 0.15.0 Changelog
  CHANGELOG.md
Labels: documentation, merge-if-ok

#5958 Remove deprecated variable with best-before date
  datalad/utils.py
Labels: merge-if-ok, internal

#5956 Deprecate --pbs-runner
  datalad/cmdline/common_args.py
  datalad/cmdline/helpers.py
Labels: minor

#5952 Pass `--no-changelog` to `auto shipit` if changelog already has entry
  .github/workflows/release.yml
Labels: internal

#5945 BF: limit CMD_MAX_ARG if obnoxious value is encountered.
  datalad/utils.py
Labels: patch

#5960 BF: use `==` not `is`
  datalad/interface/utils.py
Labels: patch

#5966 Consolidate appveyor setup (fewer jobs, recent git-annex on linux)
  .appveyor.yml
Labels: internal

#5968 `Path.exist()` no longer raises OSError for non-existing malformed paths p…
  datalad/core/distributed/clone.py
Labels: patch

#5964 ENH: announce deprecation of datalad.version
  datalad/__init__.py
  datalad/version.py
  docs/source/conf.py
Labels: minor

#5971 Annotate datalad_core as not needing actual data -- just uses annex whereis
  datalad/metadata/extractors/datalad_core.py
Labels: patch

#5936 BF(UX): do not keep logging ERROR possibly present in progress records
  datalad/support/annexrepo.py
Labels: merge-if-ok, patch

#5930 BF?: add-archive-content on .xz and other non-.gz stream compressed files
  datalad/interface/add_archive_content.py
  datalad/interface/tests/test_add_archive_content.py
  datalad/tests/test_utils.py
  datalad/tests/utils.py
  datalad/utils.py
Labels: merge-if-ok, patch

#5944 BF: do use OBSCURE_FILENAME instead of hardcoded unicode
  datalad/support/tests/test_globbedpaths.py
  datalad/support/tests/test_network.py
Labels: merge-if-ok, tests, release

#5954 Change CapturedException's behavior and intended usage
  datalad/__init__.py
  datalad/cmdline/helpers.py
  datalad/cmdline/main.py
  datalad/core/distributed/clone.py
  datalad/core/local/run.py
  datalad/customremotes/tests/test_archives.py
  datalad/customremotes/tests/test_datalad.py
  datalad/distributed/create_sibling_gitlab.py
  datalad/distributed/export_archive_ora.py
  datalad/distribution/create_sibling.py
  datalad/distribution/update.py
  datalad/dochelpers.py
  datalad/interface/common_cfg.py
  datalad/interface/download_url.py
  datalad/interface/rerun.py
  datalad/interface/results.py
  datalad/interface/test.py
  datalad/local/addurls.py
  datalad/local/check_dates.py
  datalad/local/subdatasets.py
  datalad/local/wtf.py
  datalad/log.py
  datalad/support/exceptions.py
  datalad/support/parallel.py
  datalad/support/sshconnector.py
  datalad/support/tests/test_captured_exception.py
  datalad/support/tests/test_github_.py
  datalad/tests/test_dochelpers.py
  datalad/utils.py
  docs/source/design/exception_handling.rst
  docs/source/design/index.rst
Labels: internal

#5976 Tuned `EnsureChoice` rendering and `update` doc tuning
  datalad/distribution/update.py
  datalad/support/constraints.py
Labels: merge-if-ok, patch

#5980 Add debugging information to release step
  .github/workflows/release.yml
Labels: internal

#5981 Remove deprecated --pbs-runner cmdline option
  datalad/cmdline/common_args.py
  datalad/cmdline/helpers.py
  datalad/cmdline/main.py
  datalad/interface/base.py
  docs/source/basics_cmdline.rst.in
Labels: minor

#5986 BF(TST): use sys.executable, mark test_ria_basics.test_url_keys as requiring network
  datalad/distributed/tests/test_ria_basics.py
  datalad/tests/test_nonasyncrunner.py
Labels: tests

#5983 Close file descriptors after process exit
  datalad/nonasyncrunner.py
Labels: patch

#5988 Restructure cmdline API presentation
  _datalad_build_support/formatters.py
  docs/source/cmdline.rst
Labels: patch

#5998 Coarse description of the credential subsystem's functionality
  docs/source/design/credentials.rst
  docs/source/design/index.rst
Labels: documentation

#5949 create-sibling-{github,gogs,gitea,gin} as instances of GitHub-like platforms
  datalad/distributed/create_sibling_ghlike.py
  datalad/distributed/create_sibling_gin.py
  datalad/distributed/create_sibling_gitea.py
  datalad/distributed/create_sibling_github.py
  datalad/distributed/create_sibling_gitlab.py
  datalad/distributed/create_sibling_gogs.py
  datalad/distributed/tests/test_create_sibling_ghlike.py
  datalad/distributed/tests/test_create_sibling_gin.py
  datalad/distributed/tests/test_create_sibling_gitea.py
  datalad/distributed/tests/test_create_sibling_github.py
  datalad/distributed/tests/test_create_sibling_gitlab.py
  datalad/distributed/tests/test_create_sibling_gogs.py
  datalad/distribution/create_sibling_github.py
  datalad/distribution/tests/test_create_github.py
  datalad/downloaders/credentials.py
  datalad/interface/__init__.py
  datalad/support/github_.py
  datalad/support/tests/test_github_.py
  docs/source/cmdline.rst
  docs/source/modref.rst
  setup.py
Labels: enhancement, UX, merge-if-ok, cmd-create-sibling-github, minor

#5999 ENH: import datalad.api to bind extensions methods for discovery of dataset methods
  datalad/distribution/dataset.py
Labels: patch

#5991 BF: downloader - fail to download even on non-crippled FS if symlink exists
  datalad/downloaders/base.py
Labels: patch, release

#6007 Discontinue exc_str() in all modern parts of the code base
  datalad/core/distributed/clone.py
  datalad/core/local/resulthooks.py
  datalad/core/local/run.py
  datalad/distributed/create_sibling_gitlab.py
  datalad/distributed/export_archive_ora.py
  datalad/local/addurls.py
  datalad/local/check_dates.py
  datalad/local/copy_file.py
  datalad/local/subdatasets.py
  datalad/local/tests/test_wtf.py
  datalad/local/wtf.py
Labels: patch

#6006 RF: Promote internal status() helper with docs, and breadth-first reporting
  datalad/core/local/status.py
Labels: merge-if-ok, patch

#6008 Large code-reorganization of everything runner-related
  .appveyor.yml
  datalad/cmd.py
  datalad/consts.py
  datalad/runner/__init__.py
  datalad/runner/coreprotocols.py
  datalad/runner/exception.py
  datalad/runner/gitrunner.py
  datalad/runner/nonasyncrunner.py
  datalad/runner/protocol.py
  datalad/runner/runner.py
  datalad/runner/tests/__init__.py
  datalad/runner/tests/test_nonasyncrunner.py
  datalad/runner/tests/test_witless_runner.py
  datalad/runner/utils.py
  datalad/support/exceptions.py
  datalad/tests/test_cmd.py
Labels: merge-if-ok, patch

#6004 Ensure there's a blank line between the class `__doc__` and "Parameters" in `build_doc` docstrings
  datalad/interface/base.py
  datalad/interface/tests/test_base.py
Labels: patch

#6017 UX: Report GitLab weburl of freshly created projects in the result
  datalad/distributed/create_sibling_gitlab.py
Labels: patch

#6015 BF: Do not overwrite existing sibling configurations with create-sibling-gitlab
  datalad/distributed/create_sibling_gitlab.py
  datalad/distributed/tests/test_create_sibling_gitlab.py
Labels: patch

#6020 BF: ProgressHandler - close the other handler if was specified
  datalad/log.py
  datalad/tests/test_log.py
  datalad/utils.py
Labels: merge-if-ok, patch

#6019 Add dedicated HTTP500 error handler
  datalad/distributed/create_sibling_ghlike.py
Labels: patch
