Repository datalad/datalad, pull requests merged in 2021-07, with the labels that each got.

#5776 ENH (UX): add python-gitlab dependency
  setup.py
Labels: patch

#5781 shell-completion: add argcomplete to 'misc' extra_depends, log an ERROR if argcomplete fails to import
  datalad/interface/shell_completion.py
  setup.py
  tools/cmdline-completion
Labels: UX, patch

#5786 Tests: Allow for version to contain + as a separator and provide more information for version related comparisons
  datalad/cmdline/tests/test_main.py
  datalad/support/tests/test_external_versions.py
Labels: tests

#5787 ENH(UX,DX): inform user with a warning if version is 0+unknown
  datalad/__init__.py
Labels: DX, UX, patch

#5777 New config `datalad.credentials.force-ask` to force interactive credential updates
  datalad/downloaders/credentials.py
  datalad/downloaders/tests/test_credentials.py
  datalad/interface/common_cfg.py
Labels: credentials, patch

#5789 BF: create-sibling-gitlab: do not skip root dataset when path is given
  datalad/distributed/create_sibling_gitlab.py
  datalad/distributed/tests/test_create_sibling_gitlab.py
Labels: UX

#5802 http downloaders: Provide custom informative User-Agent, do not claim to be "Authenticated access"
  datalad/downloaders/base.py
  datalad/downloaders/http.py
Labels: UX, merge-if-ok, patch

#5793 RF cmdline/main.py to make the main logic a bit more readable/succinct
  datalad/cmdline/helpers.py
  datalad/cmdline/main.py
  datalad/cmdline/tests/test_helpers.py
  datalad/cmdline/tests/test_main.py
  datalad/interface/__init__.py
  datalad/interface/base.py
Labels: DX, patch

#5817 RF(TST): do not test for no EASY and pkg_resources in shims
  datalad/cmdline/tests/test_main.py
Labels: patch

#5818 BF: import importlib.metadata not importlib_metadata whenever available
  _datalad_build_support/setup.py
Labels: internal

#5821 BF: Fix reported paths in ORA remote
  datalad/distributed/ora_remote.py
Labels: internal

#5809 BF: Report info from annex JSON error message in CommandError
  datalad/cmdline/tests/test_main.py
  datalad/support/exceptions.py
Labels: patch

#5853 BF(TST): no codename in CHANGELOG entries any longer
  datalad/tests/test_version.py
Labels: tests
