Repository datalad/datalad, pull requests merged in 2021-06, with the labels that each got.

#5705 BF: account for annex now "scanning for annexed" instead of "unlocked" files
  datalad/support/annexrepo.py
  datalad/support/tests/test_annexrepo.py
Labels: annex, enhancement, patch

#5718 BF: do not use .acquired - just get state from acquire()
  datalad/support/locking.py
  datalad/support/tests/test_locking.py
Labels: merge-if-ok, patch

#5727 BF(TST): skip testing for showing "Scanning for ..." since not shown if too quick
  datalad/support/tests/test_annexrepo.py
Labels: tests

#5733 ENH: harmonize "purpose" statements to imperative form
  datalad/core/distributed/clone.py
  datalad/core/distributed/push.py
  datalad/core/local/create.py
  datalad/core/local/diff.py
  datalad/core/local/run.py
  datalad/core/local/save.py
  datalad/core/local/status.py
  datalad/distributed/create_sibling_ria.py
  datalad/distributed/export_archive_ora.py
  datalad/distribution/create_sibling.py
  datalad/distribution/create_sibling_github.py
  datalad/distribution/dataset.py
  datalad/distribution/drop.py
  datalad/distribution/install.py
  datalad/distribution/publish.py
  datalad/distribution/siblings.py
  datalad/distribution/uninstall.py
  datalad/distribution/update.py
  datalad/interface/download_url.py
  datalad/interface/rerun.py
  datalad/interface/tests/test_annotate_paths.py
  datalad/interface/unlock.py
  datalad/local/copy_file.py
  datalad/local/subdatasets.py
  datalad/plugin/wtf.py
Labels: DX, UX

#5690 add --on-failure default value and document it
  .zenodo.json
  datalad/cmdline/helpers.py
  datalad/interface/common_opts.py
Labels: patch

#5740 Make lock file location configurable
  datalad/config.py
  datalad/downloaders/base.py
  datalad/interface/common_cfg.py
Labels: merge-if-ok

#5669 Switch to versioneer and auto
  .appveyor.yml
  .autorc
  .gitattributes
  .github/workflows/release.yml
  .github/workflows/test-label.yml
  CHANGELOG.md
  CONTRIBUTING.md
  MANIFEST.in
  _datalad_build_support/setup.py
  datalad/__init__.py
  datalad/_version.py
  datalad/tests/test_version.py
  datalad/version.py
  setup.cfg
  setup.py
  versioneer.py
Labels: internal, merge-if-ok

#5747 BF(TST): parallel - take longer for producer to produce
  datalad/support/tests/test_parallel.py
Labels: patch, release, tests

#5757 BF: update changelog conversion from .md to .rst (for sphinx)
  .autorc
  .github/workflows/release.yml
  .github/workflows/test-label.yml
  Makefile
  docs/source/changelog.rst
Labels: documentation, internal, release
