Repository datalad/datalad, pull requests merged in 2021-01, with the labels that each got.

#5278 RM: install - remove --nosave/save=False
  datalad/distribution/install.py
  datalad/distribution/tests/test_install.py
Labels: merge-if-ok

#5311 DOC: Include information on subdataset clone sources in `get` docs
  datalad/distribution/get.py
Labels: documentation

#5321 OPT: Speed up _check_git_annex_version()
  datalad/support/annexrepo.py
  datalad/support/tests/test_annexrepo.py
Labels: performance

#5348 BF+RF: Consistent and more "thorough" handling of fake HOMEs (including Windows) (master)
  CONTRIBUTING.md
  datalad/__init__.py
  datalad/core/distributed/tests/test_clone.py
  datalad/tests/test_base.py
  datalad/tests/test_config.py
  datalad/utils.py
Labels: merge-if-ok

#5350 RF: cmd - reuse asyncio loop if there is one, start/close new one otherwise
  datalad/cmd.py
  datalad/tests/test_witless_runner.py
Labels: merge-if-ok

#5367 BF: in a new process, test first if we can run any command, and if not - old ways
  datalad/cmd.py
  datalad/support/tests/test_parallel.py
  datalad/tests/test_witless_runner.py
  datalad/tests/utils.py
Labels: merge-if-ok, severity-important
