Repository datalad/datalad, pull requests merged in 2021-11, with the labels that each got.

#6134 git://github.com -> https://github.com
  datalad/core/distributed/tests/test_clone.py
  datalad/support/tests/test_gitrepo.py
  datalad/tests/test_testrepos.py
  datalad/tests/utils.py
  tools/testing/make_test_repo
  tools/testing/start_website_in_docker-Dockerfile.in
  tools/testing/test_README_in_docker-Dockerfile.in
Labels: tests

#6140 BF: clone tried to save new subdataset despite failing to clone
  datalad/core/distributed/clone.py
  datalad/core/distributed/tests/test_clone.py
Labels: patch

#6136 TST: Enable more Windows tests
  datalad/interface/tests/test_download_url.py
  datalad/interface/tests/test_rerun.py
  datalad/support/tests/test_locking.py
  datalad/tests/test_utils_cached_dataset.py
Labels: internal

#6137 OPT: do not deduce the ds path over and over again for files in a dir
  datalad/core/local/status.py
Labels: performance, merge-if-ok, patch

#6135 BF: obtain information about annex special remotes also from annex journal
  datalad/support/annexrepo.py
Labels: patch

#6111 Reimplementation of drop/(uninstall)/remove
  .appveyor.yml
  benchmarks/api.py
  datalad/core/distributed/tests/test_clone.py
  datalad/core/distributed/tests/test_push.py
  datalad/core/local/tests/test_create.py
  datalad/core/local/tests/test_run.py
  datalad/core/local/tests/test_save.py
  datalad/core/local/tests/test_status.py
  datalad/distributed/drop.py
  datalad/distributed/tests/test_create_sibling_ghlike.py
  datalad/distributed/tests/test_drop.py
  datalad/distribution/dataset.py
  datalad/distribution/drop.py
  datalad/distribution/remove.py
  datalad/distribution/tests/test_dataset.py
  datalad/distribution/tests/test_drop.py
  datalad/distribution/tests/test_install.py
  datalad/distribution/tests/test_uninstall.py
  datalad/distribution/tests/test_update.py
  datalad/distribution/uninstall.py
  datalad/interface/__init__.py
  datalad/interface/annotate_paths.py
  datalad/interface/common_opts.py
  datalad/interface/diff.py
  datalad/interface/tests/test_annotate_paths.py
  datalad/interface/tests/test_diff.py
  datalad/interface/tests/test_rerun.py
  datalad/local/remove.py
  datalad/local/tests/test_copy_file.py
  datalad/local/tests/test_remove.py
  datalad/local/tests/test_subdataset.py
  datalad/metadata/tests/test_aggregation.py
  datalad/support/gitrepo.py
  datalad/tests/utils.py
  datalad/utils.py
  docs/source/cmdline.rst
  docs/source/design/drop.rst
  docs/source/modref.rst
Labels: cmd-drop, cmd-uninstall, cmd-remove, minor

#6142 Remove all usage of exc_str()
  datalad/distribution/create_sibling.py
  datalad/distribution/install.py
  datalad/distribution/siblings.py
  datalad/distribution/update.py
  datalad/downloaders/base.py
  datalad/downloaders/credentials.py
  datalad/downloaders/http.py
  datalad/downloaders/s3.py
  datalad/downloaders/shub.py
  datalad/downloaders/tests/test_s3.py
  datalad/interface/base.py
  datalad/interface/download_url.py
  datalad/interface/rerun.py
  datalad/interface/results.py
  datalad/interface/shell_completion.py
  datalad/interface/utils.py
  datalad/metadata/aggregate.py
  datalad/metadata/extractors/image.py
  datalad/metadata/extractors/tests/test_image.py
  datalad/metadata/extractors/tests/test_xmp.py
  datalad/metadata/metadata.py
  datalad/metadata/search.py
  datalad/support/annexrepo.py
  datalad/support/cookies.py
  datalad/support/due_utils.py
  datalad/support/external_versions.py
  datalad/support/github_.py
  datalad/support/gitrepo.py
  datalad/support/json_py.py
  datalad/support/locking.py
  datalad/support/network.py
  datalad/support/parallel.py
  datalad/support/s3.py
  datalad/support/sshconnector.py
  datalad/support/tests/test_external_versions.py
  datalad/support/tests/test_path.py
  datalad/support/vcr_.py
  datalad/tests/test_archives.py
  datalad/tests/utils.py
  datalad/ui/dialog.py
  datalad/utils.py
Labels: internal

#6105 RF: Transform add-archive-content into a Dataset method
  datalad/customremotes/base.py
  datalad/customremotes/tests/test_archives.py
  datalad/interface/add_archive_content.py
  datalad/interface/download_url.py
  datalad/interface/tests/test_add_archive_content.py
  datalad/interface/tests/test_download_url.py
Labels: minor

#6147 Properly escape backslashes in some regexes
  datalad/tests/test_log.py
Labels: patch

#6148 RF+BF: use skip_if_no_module helper instead of try/except for libxmp and boto
  datalad/downloaders/tests/test_s3.py
  datalad/metadata/extractors/tests/test_xmp.py
  datalad/metadata/tests/test_extract_metadata.py
Labels: tests

#6146 Consolidate `master` after `maint` changes
  datalad/distribution/create_sibling.py
  datalad/distribution/install.py
  datalad/distribution/siblings.py
  datalad/distribution/update.py
  datalad/downloaders/base.py
  datalad/downloaders/credentials.py
  datalad/downloaders/http.py
  datalad/downloaders/s3.py
  datalad/downloaders/shub.py
  datalad/downloaders/tests/test_s3.py
  datalad/interface/base.py
  datalad/interface/download_url.py
  datalad/interface/rerun.py
  datalad/interface/results.py
  datalad/interface/shell_completion.py
  datalad/interface/utils.py
  datalad/metadata/aggregate.py
  datalad/metadata/extractors/image.py
  datalad/metadata/extractors/tests/test_image.py
  datalad/metadata/extractors/tests/test_xmp.py
  datalad/metadata/metadata.py
  datalad/metadata/search.py
  datalad/metadata/tests/test_extract_metadata.py
  datalad/support/annexrepo.py
  datalad/support/cookies.py
  datalad/support/due_utils.py
  datalad/support/external_versions.py
  datalad/support/gitrepo.py
  datalad/support/json_py.py
  datalad/support/locking.py
  datalad/support/network.py
  datalad/support/parallel.py
  datalad/support/s3.py
  datalad/support/sshconnector.py
  datalad/support/tests/test_external_versions.py
  datalad/support/tests/test_path.py
  datalad/support/vcr_.py
  datalad/tests/test_archives.py
  datalad/tests/utils.py
  datalad/ui/dialog.py
  datalad/utils.py
Labels: internal

#6153 More capable HTTP-serving test environment
  .appveyor.yml
  datalad/distributed/tests/test_ria_basics.py
  datalad/tests/ca/README
  datalad/tests/ca/ca-key.pem
  datalad/tests/ca/ca-root.pem
  datalad/tests/ca/ca-root.srl
  datalad/tests/ca/ca_bundle.pem
  datalad/tests/ca/certificate-key.pem
  datalad/tests/ca/certificate-pub.pem
  datalad/tests/ca/certificate.csr
  datalad/tests/test_tests_utils.py
  datalad/tests/utils.py
  tools/ci/deploy_datalad-rootca
  tox.ini
Labels: internal

#6169 New helper `tools/adhoc-httpd` to facilitate manual HTTP debugging
  datalad/tests/utils.py
  tools/adhoc-httpd
Labels: tests

#6175 RM: (re)move get_func_kwargs_doc and some python2 compat code path
  datalad/tests/test_utils.py
  datalad/utils.py
Labels: minor

#6143 BF produce an error in create and run_procedure if procedure does not exist
  .zenodo.json
  datalad/core/local/create.py
  datalad/core/local/tests/test_create.py
  datalad/interface/run_procedure.py
  datalad/interface/tests/test_run_procedure.py
Labels: patch

#6172 Yield add-archive-content results when called from download-url
  datalad/interface/download_url.py
  datalad/interface/tests/test_download_url.py
Labels: patch

#6165 Reimplement the datalad(-archives) special remotes with AnnexRemote
  datalad/cmdline/tests/test_main.py
  datalad/customremotes/archives.py
  datalad/customremotes/base.py
  datalad/customremotes/datalad.py
  datalad/customremotes/main.py
  datalad/customremotes/tests/test_archives.py
  datalad/customremotes/tests/test_base.py
  datalad/customremotes/tests/test_datalad.py
  datalad/interface/add_archive_content.py
  docs/source/modref.rst
Labels: corpse-in-basement, minor

#6151 infra: Provide custom prefix to auto-related labels
  .autorc
  .github/workflows/test-label.yml
  CONTRIBUTING.md
Labels: semver-internal

#6174 Decomplexify/document result-rendering switches
  datalad/cmdline/helpers.py
  datalad/core/distributed/tests/test_push.py
  datalad/core/local/run.py
  datalad/core/local/tests/test_diff.py
  datalad/core/local/tests/test_results.py
  datalad/core/local/tests/test_run.py
  datalad/core/local/tests/test_status.py
  datalad/distributed/create_sibling_ria.py
  datalad/distributed/tests/test_create_sibling_ghlike.py
  datalad/distributed/tests/test_create_sibling_ria.py
  datalad/distribution/create_sibling.py
  datalad/distribution/siblings.py
  datalad/distribution/tests/test_get.py
  datalad/distribution/tests/test_siblings.py
  datalad/interface/base.py
  datalad/interface/clean.py
  datalad/interface/common_opts.py
  datalad/interface/rerun.py
  datalad/interface/run_procedure.py
  datalad/interface/tests/test_base.py
  datalad/interface/tests/test_utils.py
  datalad/interface/utils.py
  datalad/local/addurls.py
  datalad/local/subdatasets.py
  datalad/local/tests/test_addurls.py
  datalad/local/tests/test_copy_file.py
  datalad/metadata/aggregate.py
  datalad/support/due_utils.py
Labels: semver-minor

#6183 Do not fail dropping an uninitialized AnnexRepo
  datalad/distributed/drop.py
  datalad/distributed/tests/test_drop.py
Labels: semver-patch

#6181 Design document on the datalad/datalad-archives special remotes
  docs/source/design/file_url_handling.rst
  docs/source/design/index.rst
Labels: semver-documentation

#6189 Bump sphinx requirement to bypass readthedocs defaults
  setup.py
Labels: semver-documentation

#6188 Move AddArchiveContent in the spirit of #3192
  datalad/customremotes/archives.py
  datalad/interface/__init__.py
  datalad/interface/add_archive_content.py
  datalad/local/add_archive_content.py
  datalad/local/tests/test_add_archive_content.py
Labels: semver-minor

#6191 Move Clean in the spirit of #3192
  datalad/interface/__init__.py
  datalad/interface/clean.py
  datalad/local/clean.py
  datalad/local/tests/test_clean.py
Labels: semver-internal

#5642 ENH: get_status_dict - add exit_code if CommandError
  datalad/interface/results.py
  datalad/interface/tests/test_results.py
  datalad/support/exceptions.py
Labels: semver-patch

#6190 RF: de-wrapt
  datalad/distribution/dataset.py
  datalad/interface/base.py
  datalad/interface/utils.py
  datalad/support/external_versions.py
  datalad/tests/test_utils.py
  datalad/utils.py
  requirements-devel.txt
  setup.py
Labels: semver-minor

#6200 TST: redistribute windows tests across workers to harmonize runtime
  .appveyor.yml
Labels: semver-tests

#6198 MNT: Replace appdirs with platformdirs
  CONTRIBUTING.md
  datalad/cmdline/helpers.py
  datalad/downloaders/tests/test_providers.py
  datalad/interface/common_cfg.py
  datalad/interface/run_procedure.py
  datalad/support/cookies.py
  datalad/support/external_versions.py
  setup.py
Labels: semver-minor

#6207 INFRA: Modernize readthedocs configuration
  readthedocs.yml
Labels: semver-documentation

#6203 Document `BatchedCommand` and `BatchedAnnex`
  datalad/tests/test_cmd.py
  docs/source/design/batched_command.rst
  docs/source/design/index.rst
Labels: semver-documentation, semver-tests

#6192 Move Unlock in the spirit of #3192
  datalad/core/local/run.py
  datalad/interface/__init__.py
  datalad/interface/unlock.py
  datalad/local/tests/test_unlock.py
  datalad/local/unlock.py
Labels: semver-internal

#6168 BF: Don't overwrite subdataset source candidates
  datalad/distribution/get.py
  datalad/distribution/tests/test_get.py
Labels: semver-patch

#6212 BF: Also catch ModuleNotFoundErrors for formatters
  datalad/cmdline/tests/test_formatters.py
Labels: semver-internal

#6218 `clone` supports passing options to `git-clone` (Replacement of #5662)
  datalad/core/distributed/clone.py
  datalad/core/distributed/tests/test_clone.py
  datalad/distribution/install.py
  datalad/distribution/tests/test_install.py
  datalad/support/gitrepo.py
  datalad/tests/test_api.py
Labels: semver-minor

#6217 Move DownloadURL in the spirit of #3192
  datalad/interface/__init__.py
  datalad/interface/download_url.py
  datalad/local/download_url.py
  datalad/local/tests/test_download_url.py
Labels: semver-internal

#6220 Move ReRun in the spirit of #3192
  datalad/interface/__init__.py
  datalad/interface/rerun.py
  datalad/local/rerun.py
  datalad/local/tests/test_rerun.py
  datalad/local/tests/test_rerun_merges.py
Labels: semver-minor

#6206 Clean up inactive BatchedCommands
  .travis.yml
  datalad/cmd.py
  datalad/interface/common_cfg.py
Labels: semver-patch

#6222 Move RunProcedure in the spirit of #3192
  datalad/interface/__init__.py
  datalad/interface/run_procedure.py
  datalad/local/rerun.py
  datalad/local/run_procedure.py
  datalad/local/tests/test_run_procedure.py
Labels: semver-minor

#6091 Report correct HTTP URL for RIA store content
  datalad/distributed/ora_remote.py
  datalad/distributed/tests/test_ora_http.py
Labels: RIA/ORA, semver-patch

#6229 Fix test for changed create-sibling-ria interface
  datalad/distribution/tests/test_get.py
Labels: semver-internal

#6228 TST: Switch to Visual Studio 2022 for Appveyor Windows setup
  .appveyor.yml
  tools/ci/appveyor_install_git-annex.bat
Labels: semver-tests

#6223 Cleanup interface list, introduce group sort, new group structure
  datalad/cmdline/helpers.py
  datalad/cmdline/tests/test_main.py
  datalad/interface/__init__.py
  datalad/interface/base.py
Labels: semver-documentation

#6224 Discontinue with_testrepo usage for all core tests
  datalad/core/distributed/tests/test_clone.py
  datalad/core/local/tests/test_run.py
  datalad/core/local/tests/test_save.py
Labels: semver-tests

#6230 Make outcome of `create-sibling-gin` readily usable for a `push` data transfer
  datalad/distributed/create_sibling_gin.py
  datalad/distributed/tests/test_create_sibling_ghlike.py
  datalad/distributed/tests/test_create_sibling_gin.py
Labels: semver-patch

#6236 DOC: Adopt the Contributor Covenant COC v2.1
  CODE_OF_CONDUCT.md
  README.md
Labels: semver-documentation

#6234 `export-archive-ora`: add options to filter files exported to the 7z archive
  datalad/distributed/export_archive_ora.py
  datalad/distributed/tests/ria_utils.py
  datalad/distributed/tests/test_ora_http.py
  datalad/distributed/tests/test_ria_basics.py
  datalad/distributed/tests/test_ria_git_remote.py
Labels: semver-minor

#6173 ENH(UX): log a hint to use ulimit command in case of "Too long" exception
  datalad/runner/nonasyncrunner.py
  datalad/runner/tests/test_witless_runner.py
Labels: UX, semver-patch

#6242 Fix special remote messaging
  datalad/customremotes/__init__.py
  datalad/customremotes/archives.py
  datalad/customremotes/base.py
  datalad/customremotes/datalad.py
  datalad/distributed/ora_remote.py
  datalad/downloaders/s3.py
  datalad/support/exceptions.py
  datalad/support/tests/test_captured_exception.py
Labels: semver-minor

#6245 TST: Enable filter.annex.process on windows to speed things up
  .appveyor.yml
Labels: semver-tests

#6249 Docstring handling upgrade
  datalad/distributed/create_sibling_gin.py
  datalad/distributed/create_sibling_gitea.py
  datalad/distributed/create_sibling_github.py
  datalad/distributed/create_sibling_gitlab.py
  datalad/distributed/create_sibling_gogs.py
  datalad/distributed/create_sibling_ria.py
  datalad/interface/base.py
  docs/source/design/docstrings.rst
  docs/source/design/index.rst
Labels: semver-documentation

#6253 BF: Keyring.delete called uninitialized attribute
  datalad/support/keyring_.py
Labels: semver-patch

#6256 BF: Properly pass result kwargs into result record of create-sibling-ria
  datalad/distributed/create_sibling_ria.py
Labels: semver-patch

#6257 Fixup remove --recursive deprecation
  datalad/local/remove.py
Labels: semver-patch

#6266 ENH(TST): add some "pragma: no cover" wherever test code is not expected to run
  datalad/tests/test_utils.py
Labels: semver-tests
