Repository datalad/datalad, pull requests merged in 2021-05, with the labels that each got.

#5655 BF(DOC)+RF: report "present" for the state of a present/installed/fulfilled (sub)dataset
  datalad/local/subdatasets.py
  datalad/local/tests/test_subdataset.py
Labels: DX, UX, documentation, enhancement, merge-if-ok

#5687 DOC: up-to-date COPYING
  COPYING
Labels: DX

#5676 RF: just pip install datalad-installer
  .appveyor.yml
  .github/workflows/test_macos.yml
  .travis.yml
Labels: merge-if-ok

#5680 Support credential query via config manager
  datalad/downloaders/credentials.py
  datalad/downloaders/tests/test_credentials.py
Labels: merge-if-ok
