Repository datalad/datalad, pull requests merged in 2022-09, with the labels that each got.

#6997 Make the manpages build reproducible via datalad.source.epoch (to be used in Debian packaging)
  .github/workflows/docbuild.yml
  _datalad_build_support/formatters.py
  changelog.d/pr-6997.md
  datalad/interface/common_cfg.py
Labels: semver-internal

#7003 BF: blacklist 23.9.0 of keyring as introduces regression
  setup.py
Labels: semver-internal, release

#7006 Fix type annotations in `cmd.py` and `runner.py`
  datalad/cmd.py
  datalad/runner/nonasyncrunner.py
  datalad/runner/runner.py
  tox.ini
Labels: semver-internal

#7009 Use scriv for CHANGELOG generation in release workflow
  .autorc
  .github/workflows/release.yml
  changelog.d/pr-7009.md
  changelog.d/scriv.ini
  changelog.d/templates/entry_title.md.j2
  changelog.d/templates/new_fragment.md.j2
  tools/ci/mkchlog-snippet.py
Labels: semver-internal, release

#7018 RST syntax fix
  docs/source/design/github_actions.rst
  docs/source/design/index.rst
Labels: semver-documentation

#7020 Revert back to non-devel neurodebian in crippledfs/extensions, add testing against -next
  .github/workflows/test_crippled.yml
  .github/workflows/test_extensions.yml
Labels: semver-tests

#7017 Make clone_dataset() patchable and less monolithic
  datalad/core/distributed/clone.py
  datalad/core/distributed/clone_ephemeral.py
  datalad/core/distributed/clone_ria.py
  datalad/core/distributed/clone_utils.py
  datalad/core/distributed/tests/test_clone.py
Labels: cmd-clone, semver-minor

#7028 Fix datalad --help to not have *Global options* empty and list options in "options:" section
  changelog.d/pr-7028.md
  datalad/cli/helpers.py
  datalad/cli/tests/test_main.py
Labels: semver-patch

#7036 Let `create` touch the dataset root, if not saving in parent dataset
  changelog.d/pr-7036.md
  datalad/core/local/create.py
Labels: enhancement, cmd-create, semver-patch

#7039 Make choices for `status|diff --annex` and `status|diff --untracked` …
  changelog.d/pr-7039.md
  datalad/core/local/status.py
Labels: UX, cmd-diff, cmd-status, semver-patch

#7044 Adapt tests to modified command group names
  datalad/cli/tests/test_main.py
Labels: semver-tests

#7035 Remove `simplejson` in favor of using `json`
  datalad/support/annexrepo.py
  datalad/support/json_py.py
  datalad/support/tests/test_json_py.py
Labels: semver-internal

#7011 UX: push - provide specific error with details if push failed due to permission issue
  changelog.d/pr-7011.md
  datalad/core/distributed/push.py
Labels: semver-patch

#7024 Stop using auto
  .autorc
  .github/workflows/add-changelog-snippet.yml
  .github/workflows/release.yml
  changelog.d/pr-7024.md
  tools/ci/release-comment.py
Labels: semver-internal

#7037 Let get_status_dict() use exception message if none is passed
  changelog.d/pr-7037.md
  datalad/interface/results.py
Labels: UX, semver-patch, release

#7046 BF: use default GITHUB_TOKEN for release workflow instead of a GITMATE one
  .github/workflows/release.yml
Labels: semver-internal, release

#7047 Give more information about used token and performed actions
  .github/workflows/release.yml
  tools/ci/release-comment.py
Labels: release

#7051 Trigger release workflow on `pull_request_target`
  .github/workflows/release.yml
Labels: semver-internal

#7049 push: Assume 0 bytes pushed if git-annex does not provide bytesize
  changelog.d/pr-7049.md
  datalad/core/distributed/push.py
Labels: cmd-push, semver-patch, release

#7057 Revert "Remove chardet version upper limit" to bring back upper limit <= 5.0.0 on chardet
  changelog.d/pr-7057.md
  setup.py
Labels: semver-internal

#7056 DATALAD_TESTS_GITCONFIG env variable to provide custom settings for git during tests
  .travis.yml
  CONTRIBUTING.md
  datalad/conftest.py
Labels: semver-tests

#7060 Make pytest to be the default tester for extensions
  .github/workflows/test_extensions.yml
Labels: semver-tests
