Repository datalad/datalad, pull requests merged in 2022-11, with the labels that each got.

#7109 Add a way to specify description when creating github-like siblings
  changelog.d/pr-7109.md
  datalad/distributed/create_sibling_ghlike.py
  datalad/distributed/create_sibling_gin.py
  datalad/distributed/create_sibling_gitea.py
  datalad/distributed/create_sibling_github.py
  datalad/distributed/create_sibling_gogs.py
Labels: semver-minor

#7126 XFAIL a check on length of results in test_gracefull_death
  changelog.d/pr-7126.md
  datalad/support/tests/test_parallel.py
Labels: semver-tests

#7118 Fix all logging to use %-interpolation and not .format, sort imports in touched files, add pylint-ing for % formatting in log messages to `tox -e lint`
  changelog.d/pr-7118.md
  datalad/cli/main.py
  datalad/customremotes/archives.py
  datalad/distributed/create_sibling_ria.py
  datalad/distribution/create_sibling.py
  datalad/interface/base.py
  datalad/local/add_archive_content.py
  datalad/metadata/metadata.py
  datalad/metadata/search.py
  datalad/support/annexrepo.py
  datalad/support/archives.py
  datalad/support/gitrepo.py
  datalad/support/network.py
  datalad/tests/utils.py
  datalad/tests/utils_pytest.py
  datalad/utils.py
  tox.ini
Labels: semver-internal

#7130 BF(TST): allow for "file" protocol
  changelog.d/pr-7130.md
  datalad/conftest.py
Labels: semver-tests

#7133 Let EnsureDataset handle Path instances
  changelog.d/pr-7133.md
  datalad/distribution/dataset.py
  datalad/distribution/tests/test_dataset.py
Labels: semver-internal

#7136 Removing traces of nose
  .github/workflows/test_extensions.yml
  changelog.d/pr-7136.md
  datalad/__init__.py
  datalad/conftest.py
  datalad/support/annexrepo.py
  docs/source/design/python_imports.rst
  docs/source/modref.rst
  setup.py
Labels: semver-dependencies

#7132 More informative AltConstraint error
  changelog.d/pr-7132.md
  datalad/support/constraints.py
Labels: semver-patch

#7142 BF: HTTP Downloader treated 429 as authentication issue
  changelog.d/pr-7142.md
  datalad/downloaders/base.py
  datalad/downloaders/http.py
  datalad/support/exceptions.py
Labels: semver-patch, release

#7150 Fix 0.17.9 release
  CHANGELOG.md
  changelog.d/pr-7111.md
  changelog.d/pr-7112.md
  changelog.d/pr-7117.md
  changelog.d/pr-7118.md
  changelog.d/pr-7119.md
  changelog.d/pr-7123.md
  changelog.d/pr-7125.md
  changelog.d/pr-7126.md
  changelog.d/pr-7130.md
  changelog.d/pr-7136.md
  changelog.d/pr-7142.md
  docs/source/changelog.rst
Labels: release

#7147 BF: read RIA config from stdin instead of temporary file
  changelog.d/pr-7147.md
  datalad/core/distributed/clone.py
Labels: semver-patch

#7153 Fix for type checking
  datalad/cmd.py
Labels: semver-internal

#7071 NF: foreach-dataset --o-s relpath - capture and pass-through prefixing with path to subds
  changelog.d/pr-7071.md
  datalad/local/foreach_dataset.py
  datalad/local/tests/test_foreach_dataset.py
  datalad/log.py
  datalad/ui/dialog.py
  datalad/ui/tests/test_dialog.py
  docs/source/design/progress_reporting.rst
Labels: semver-minor

#7154 Fix ls import in benchmarks
  benchmarks/common.py
  changelog.d/pr-7154.md
Labels: semver-internal

#7152 TST: reenable two now-passing core test on Windows CI
  datalad/core/distributed/tests/test_push.py
Labels: semver-tests

#7158 BF(TST): for older versions allow either replaced or not -
  datalad/customremotes/tests/test_datalad.py
Labels: semver-tests

#7155 Fix runner not dealing with str as stdin
  changelog.d/pr-7155.md
  datalad/runner/nonasyncrunner.py
  datalad/runner/runner.py
Labels: semver-internal

#7159 Fix test failure with old annex
  changelog.d/pr-7159.md
  datalad/distributed/ora_remote.py
  datalad/distributed/tests/test_ria_basics.py
Labels: semver-tests

#7166 BF: Prevent doomed annex calls on files we already know are untracked
  changelog.d/pr-7166.md
  datalad/core/local/status.py
  datalad/core/local/tests/test_status.py
Labels: semver-patch

#7161 RF: Specify parameter choices uniformly
  changelog.d/pr-7161.md
  datalad/local/clean.py
Labels: semver-internal

#7174 Use regular dicts instead of OrderedDicts for speedier operations
  changelog.d/pr-7174.md
  datalad/core/distributed/push.py
  datalad/core/local/diff.py
  datalad/core/local/status.py
  datalad/customremotes/archives.py
  datalad/downloaders/credentials.py
  datalad/downloaders/providers.py
  datalad/interface/base.py
  datalad/local/wtf.py
  datalad/support/annexrepo.py
  datalad/support/gitrepo.py
  datalad/support/network.py
  datalad/support/strings.py
  datalad/support/tests/test_network.py
  datalad/tests/test_utils.py
  datalad/utils.py
Labels: semver-performance

#7170 MNT: Move eval_results() into interface.base
  changelog.d/pr-7170.md
  datalad/core/distributed/clone.py
  datalad/core/distributed/push.py
  datalad/core/local/create.py
  datalad/core/local/diff.py
  datalad/core/local/run.py
  datalad/core/local/save.py
  datalad/core/local/status.py
  datalad/distributed/create_sibling_gin.py
  datalad/distributed/create_sibling_gitea.py
  datalad/distributed/create_sibling_github.py
  datalad/distributed/create_sibling_gitlab.py
  datalad/distributed/create_sibling_gogs.py
  datalad/distributed/create_sibling_ria.py
  datalad/distributed/drop.py
  datalad/distributed/export_archive_ora.py
  datalad/distributed/export_to_figshare.py
  datalad/distribution/create_sibling.py
  datalad/distribution/get.py
  datalad/distribution/install.py
  datalad/distribution/siblings.py
  datalad/distribution/uninstall.py
  datalad/distribution/update.py
  datalad/interface/base.py
  datalad/interface/shell_completion.py
  datalad/interface/tests/test_utils.py
  datalad/interface/utils.py
  datalad/local/add_archive_content.py
  datalad/local/add_readme.py
  datalad/local/addurls.py
  datalad/local/check_dates.py
  datalad/local/clean.py
  datalad/local/configuration.py
  datalad/local/copy_file.py
  datalad/local/download_url.py
  datalad/local/export_archive.py
  datalad/local/foreach_dataset.py
  datalad/local/no_annex.py
  datalad/local/remove.py
  datalad/local/rerun.py
  datalad/local/run_procedure.py
  datalad/local/subdatasets.py
  datalad/local/unlock.py
  datalad/local/wtf.py
Labels: semver-internal

#7194 Reenable now passing test_path_diff test on Windows
  changelog.d/pr-7194.md
  datalad/core/local/tests/test_diff.py
Labels: semver-tests

#7188 Bandaids for export-to-figshare to restore functionality
  changelog.d/pr-7188.md
  datalad/distributed/export_to_figshare.py
Labels: semver-patch

#7195 DOC: Add design document on Tests and CI
  CONTRIBUTING.md
  changelog.d/pr-7195.md
  docs/source/design/index.rst
  docs/source/design/testing.rst
Labels: help wanted, semver-documentation

#7176 Remove with_testrepos from core package
  datalad/conftest.py
  datalad/distribution/tests/test_siblings.py
  datalad/distribution/tests/test_update.py
  datalad/tests/test_testrepos.py
  datalad/tests/test_tests_utils.py
  datalad/tests/test_tests_utils_pytest.py
  datalad/tests/utils.py
  datalad/tests/utils_pytest.py
  datalad/tests/utils_testdatasets.py
Labels: semver-tests

#7201 Fix runner hanging, fix an error in thread handling, and serialize concurrent generator-runner invocations
  changelog.d/pr-7201.md
  datalad/cmd.py
  datalad/runner/nonasyncrunner.py
  datalad/runner/runner.py
  datalad/runner/tests/test_nonasyncrunner.py
  datalad/runner/tests/test_threadsafety.py
  datalad/runner/tests/test_witless_runner.py
  datalad/tests/test_cmd.py
Labels: semver-internal

#7189 Reimplement get_submodules_() without get_content_info() (Reincarnated 6942)
  changelog.d/pr-7189.md
  datalad/support/gitrepo.py
  datalad/support/tests/test_gitrepo.py
Labels: semver-performance

#7187 Fix broken submodule URLs generated from relative paths
  datalad/core/distributed/tests/test_clone.py
  datalad/support/gitrepo.py
Labels: semver-patch

#7204 DOC: extend/fix CONTRIBUTING.md with information on testing, changelog and releasing
  CONTRIBUTING.md
  changelog.d/pr-7204.md
Labels: semver-documentation

#7205 Mark some tests as known fails on github CI windows
  datalad/core/distributed/tests/test_push.py
  datalad/distributed/tests/test_drop.py
Labels: semver-tests

#7203 DOC: Use standard key name 'error_message' in result record design docs
  docs/source/design/result_records.rst
Labels: semver-documentation

#7206 Fix localpath handling for file-URLs on different OS, especially on Windows
  changelog.d/pr-7206.md
  datalad/support/network.py
  datalad/support/tests/test_network.py
Labels: semver-patch

#7199 Switch to test against 3.11 instead of 3.10 as the latest python to test against (travis)
  .travis.yml
  datalad/tests/test_utils.py
Labels: semver-tests

#7183 BF: Ensure that datalad urls are posix
  changelog.d/pr-7183.md
  datalad/core/distributed/clone.py
  datalad/core/distributed/tests/test_clone.py
Labels: semver-patch
