Repository datalad/datalad, pull requests merged in 2022-05, with the labels that each got.

#6667 Deprecate AnnexRepo.add_urls()
  datalad/support/annexrepo.py
Labels: semver-patch, team-gitannex

#6665 Sanitize keys before checking content availability to ensure correct value for keys with URL or custom backend
  datalad/distributed/ora_remote.py
  datalad/support/annex_utils.py
  datalad/support/annexrepo.py
  datalad/support/tests/test_fileinfo.py
Labels: semver-patch

#6670 Modernize test
  datalad/distribution/tests/test_dataset.py
Labels: semver-tests

#6671 Remove testrepo usage from `siblings` test
  datalad/distribution/tests/test_siblings.py
Labels: semver-tests

#6674 Discontinue with_testrepos in `get` tests
  datalad/distribution/tests/test_get.py
Labels: semver-tests

#6672 Remove with_testrepos from update tests
  datalad/distribution/tests/test_update.py
Labels: semver-tests

#6664 NF: Teach WTF to report the filesystem of CWD, TMP, and HOME
  datalad/local/wtf.py
  datalad/ui/utils.py
Labels: semver-patch

#6698 Replace Zenodo DOI with JOSS for due credit
  datalad/support/gitrepo.py
Labels: semver-internal

#6693 BF: require argcomplete version at least 1.12.3 to test/operate correctly
  .travis.yml
  setup.py
Labels: semver-patch

#6709 Ensure that assertion helpers in `utils_pytest.py` get rewritten by pytest
  tox.ini
Labels: semver-tests

#6701 ENH: Better feedback when create-sibling-gitlab is called with non-existing path
  datalad/distributed/create_sibling_gitlab.py
  datalad/distributed/tests/test_create_sibling_gitlab.py
Labels: semver-patch

#6716 DOC: Set language in Sphinx config to en
  docs/source/conf.py
Labels: semver-internal

#6704 ENH: Enable progress bars for unlock, fixes #6691
  datalad/local/unlock.py
Labels: semver-patch

#6722 MNT: Remove unused helper for listing sorted files
  datalad/utils.py
Labels: semver-internal

#6712 BF: Catch KeyErrors from unavailable WTF infos
  datalad/local/tests/test_wtf.py
  datalad/local/wtf.py
Labels: semver-patch
