Repository datalad/datalad, pull requests merged in 2022-07, with the labels that each got.

#6781 Upload coverage from extension tests to Codecov
  .github/workflows/test_extensions.yml
Labels: semver-tests

#6787 Merge commit '0.16.6-17-g9e147092b' into merge-maint
  .github/workflows/test_extensions.yml
  CHANGELOG.md
  datalad/dataset/gitrepo.py
  datalad/dataset/tests/test_gitrepo.py
  datalad/downloaders/credentials.py
  datalad/metadata/search.py
  datalad/runner/nonasyncrunner.py
  datalad/runner/tests/test_threadsafety.py
  datalad/runner/tests/test_utils.py
  datalad/runner/utils.py
  datalad/support/tests/test_network.py
  datalad/tests/test_config.py
  docs/source/changelog.rst
  setup.py
Labels: semver-tests

#6783 Remove superfluous `AnnexRepo.remove()` implementation
  datalad/support/annexrepo.py
  datalad/support/gitrepo.py
Labels: semver-internal

#6790 Make sure a subdataset is saved with a complete .gitmodules record
  datalad/core/local/save.py
  datalad/core/local/tests/test_save.py
  datalad/support/gitrepo.py
Labels: cherry-pick-to-maint, semver-patch

#6795 Fix broken annex symlink after git-mv before saving
  datalad/core/local/tests/test_save.py
  datalad/support/gitrepo.py
Labels: cmd-save, semver-patch

#6799 Fix a race condition in ssh copy test
  datalad/support/tests/test_sshconnector.py
Labels: tests, semver-tests

#6811 BF(TST): skip failing test on buggy (current) git-annex release
  datalad/local/tests/test_add_archive_content.py
Labels: semver-tests

#6817 Avoid import of nose-based tests.utils, make skip_if_no_module() and skip_if_no_network() allowed at module level
  datalad/runner/tests/test_threadsafety.py
  datalad/tests/utils_pytest.py
Labels: semver-tests

#6822 RM(TST): remove testing of datalad.test which was removed from 0.17.0
  datalad/tests/test_misc.py
Labels: semver-tests

#6819 Suppress DeprecationWarning to allow for distutils to be used
  tox.ini
Labels: semver-tests

#6826 Do not quote paths for ssh >= 9
  datalad/support/external_versions.py
  datalad/support/sshconnector.py
  datalad/support/tests/test_sshconnector.py
  datalad/tests/utils_pytest.py
Labels: semver-patch

#6836 Support older pytests
  datalad/conftest.py
Labels: semver-tests

#6833 DOC: Add git-annex bug report tips to contributing
  CONTRIBUTING.md
Labels: semver-documentation

#6841 BF: Make create's check for procedures work with several again
  datalad/core/local/create.py
Labels: semver-patch

#6837 XFAIL test_runner_parametrized_protocol on python3.8 when getting duplicate output
  datalad/runner/tests/test_witless_runner.py
Labels: semver-tests

#6842 Addressing problem testing against python 3.10 on Travis (skip more annex versions)
  .travis.yml
  datalad/local/tests/test_add_archive_content.py
Labels: semver-tests

#6850 BF(TST): do proceed to proper test for error being caught for recent git-annex on windows with symlinks
  datalad/core/local/tests/test_status.py
Labels: platform-windows, release, semver-tests

#6793 Improved support for saving typechanges
  datalad/support/gitrepo.py
  datalad/support/tests/test_repo_save.py
Labels: merge-if-ok, cmd-save, semver-patch

#6784 Speed up saving of removals and improve their reporting
  datalad/local/remove.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_repo_save.py
  datalad/tests/utils_pytest.py
Labels: semver-patch

#6859 Merge `maint`, resolving conflicts between typechange-related PRs
  datalad/support/gitrepo.py
  datalad/support/tests/test_repo_save.py
Labels: merge-if-ok, semver-patch

#6864 Support unsetting config via `datalad -c :<name>`
  datalad/cli/common_args.py
  datalad/cli/helpers.py
  datalad/cli/tests/test_main.py
Labels: semver-patch, cmd-config(urgation)

#6879 Protect again failing to load a command interface from an extension
  datalad/api.py
Labels: semver-patch

#6871 Clarify confusing INFO log message from get() on dataset installation
  datalad/distribution/get.py
Labels: semver-patch

#6839 RF: Replace distutils LooseVersion with looseversion
  datalad/distribution/create_sibling.py
  datalad/support/external_versions.py
  setup.py
Labels: semver-minor

#6883 BF(DOC): workaround for #10701 of sphinx in 5.1.0
  docs/source/conf.py
Labels: semver-documentation

#6886 BF: RF f-string uses in logger to %-interpolations
  datalad/cmd.py
  datalad/runner/runnerthreads.py
Labels: semver-internal

#6881 ENH(TST): test against supported git annex repo version 10 + make it a full sweep over tests
  .travis.yml
Labels: semver-internal

#6880 RF,ENH(TST): future proof testing of git annex version upgrade + test annex init on all supported versions
  datalad/support/tests/test_annexrepo.py
Labels: semver-tests

#6885 ENH: introduce typing checking and GitHub workflow
  .github/workflows/typing.yml
  tox.ini
Labels: semver-internal

#6888 ENH: upgrade versioneer from versioneer-0.20.dev0 to versioneer-0.23.dev0
  datalad/_version.py
  versioneer.py
Labels: semver-internal

#6869 Let push honor multiple publication dependencies declared via siblings
  datalad/core/distributed/push.py
  datalad/core/distributed/tests/test_push.py
Labels: semver-patch

#6892 Use pytest to test datalad-metalad in test_extensions-workflow
  .github/workflows/test_extensions.yml
Labels: semver-tests

#6893 Fix runner type annotations
  datalad/runner/exception.py
  datalad/runner/nonasyncrunner.py
  datalad/runner/protocol.py
  datalad/runner/runner.py
  datalad/runner/runnerthreads.py
  datalad/runner/tests/test_exception.py
  datalad/runner/tests/test_nonasyncrunner.py
  datalad/runner/tests/test_threadsafety.py
  datalad/runner/tests/test_utils.py
  datalad/runner/utils.py
  setup.py
  tox.ini
Labels: semver-internal

#6891 DX: Demote loglevel of message on url parameters to DEBUG while guessing RI
  datalad/support/network.py
  datalad/support/tests/test_network.py
Labels: semver-internal
