Repository datalad/datalad, pull requests merged in 2022-08, with the labels that each got.

#6907 RF: just rename internal variable from unclear "op" to "io"
  datalad/core/distributed/clone.py
Labels: semver-internal

#6898 ENH(TST): Disable coverage reporting on travis while running pytest
  .travis.yml
Labels: DX, semver-internal

#6911 BF(TST): do not expect log message for guessing Path to be possibly a URL on windows
  datalad/support/tests/test_network.py
Labels: platform-windows, semver-tests

#6912 BF(TST,workaround): just xfail failing archives test on NFS
  datalad/tests/test_archives.py
Labels: tests, semver-tests

#6902 BF: do not pretend we know what repo version git-annex would upgrade to
  datalad/support/annexrepo.py
  datalad/support/tests/test_annexrepo.py
Labels: annex, semver-patch, release

#6919 BF: travis - mark our directory as safe to interact with as root
  .travis.yml
Labels: semver-internal

#6914 RF extensions github action to centralize configuration for extensions etc, use pytest for crawler
  .github/workflows/test_extensions.yml
Labels: semver-internal

#6927 BF(TST): allow for a annex repo version to upgrade if running in adjusted branches
  datalad/support/tests/test_annexrepo.py
Labels: semver-tests

#6936 DOC: fix capitalization of some service names
  .github/ISSUE_TEMPLATE/issue_template.yml
  CONTRIBUTING.md
  datalad/core/distributed/clone.py
  datalad/distributed/create_sibling_ghlike.py
  datalad/distribution/install.py
  datalad/interface/common_cfg.py
  datalad/local/tests/test_gitcredential.py
  datalad/metadata/definitions.py
  datalad/metadata/extractors/datalad_core.py
  docs/design.rst
  docs/source/basics.rst
  docs/source/design/credentials.rst
  docs/source/design/file_url_handling.rst
  docs/source/design/python_imports.rst
  docs/source/design/threaded_runner.rst
  tools/Dockerfile.fullmaster
Labels: cherry-pick-to-maint

#6920 BF+ENH(TST): fix typo in code of wtf filesystems reports
  datalad/local/tests/test_wtf.py
  datalad/local/wtf.py
Labels: semver-patch

#6952 BF: Remove duplicate key in result record
  datalad/distributed/create_sibling_ria.py
  datalad/distributed/tests/test_create_sibling_ria.py
Labels: semver-patch

#6904 DOC: move maintenance team info from issue to CONTRIBUTING
  CONTRIBUTING.md
Labels: semver-documentation

#6956 Minor tuneups to please updated codespell
  .codespell-ignorewords
  datalad/core/local/diff.py
  datalad/core/local/run.py
  datalad/core/local/tests/test_diff.py
  datalad/core/local/tests/test_save.py
  datalad/dochelpers.py
  datalad/local/add_archive_content.py
  datalad/local/addurls.py
  datalad/metadata/search.py
  datalad/metadata/tests/test_search.py
  datalad/support/due_utils.py
  datalad/support/exceptions.py
  datalad/tests/test_dochelpers.py
  datalad/tests/test_utils.py
  datalad/tests/utils_testrepos.py
  datalad/utils.py
Labels: semver-documentation

#6944 Acknowledge git-config comment chars
  datalad/config.py
  datalad/tests/test_config.py
Labels: semver-patch

#6959 Forbid drop operation from symlink'ed annex (e.g. due to being cloned with --reckless=ephemeral) to prevent data-loss
  datalad/distributed/drop.py
  datalad/distributed/tests/test_drop.py
Labels: severity-critical, semver-patch

#6957 BF(TST): prevent auto-upgrade of "remote" test sibling, do not use local path for URL
  datalad/distribution/tests/test_create_sibling.py
Labels: release, semver-tests

#6955 BF(TST): make tests use _path_ helper for Windows "friendliness" of the tests
  datalad/tests/test_utils.py
Labels: semver-tests

#6965 BF(TEMP): use git-annex from neurodebian -devel to gain fix for bug detected with datalad-crawler
  .github/workflows/test_extensions.yml
Labels: semver-tests

#6963 ENH+BF: get_parent_paths - make / into sep option and consistently use "/" as path separator
  datalad/support/gitrepo.py
  datalad/support/path.py
  datalad/support/tests/test_path.py
Labels: semver-patch

#6932 ENH: GitRepo -- make use of --pathspec-from-file where possible and chunking needed
  .travis.yml
  datalad/dataset/gitrepo.py
  datalad/interface/common_cfg.py
  datalad/runner/gitrunner.py
  datalad/runner/tests/test_gitrunner.py
  datalad/support/gitrepo.py
Labels: semver-minor

#6958 Explain purpose of create-sibling-ria's --post-update-hook
  datalad/distributed/create_sibling_ria.py
Labels: semver-patch, semver-documentation

#6930 DOCfix: fix docstring GeneratorStdOutErrCapture to say that treats both stdout and stderr identically
  datalad/dataset/gitrepo.py
Labels: DX, semver-documentation

#6937 BF: git_ignore_check do not overload possible value of stdout/err if present
  datalad/dataset/gitrepo.py
Labels: semver-patch, release

#6978 Send one character (no newline) to stdout in protocol test to guarantee a single "message" and thus a single custom value
  datalad/runner/tests/test_witless_runner.py
  datalad/support/tests/test_annexrepo.py
Labels: semver-tests

#6980 BF: if early attempt to parse resulted in error, setup subparsers
  datalad/cli/parser.py
  datalad/cli/tests/test_main.py
Labels: UX, semver-patch

#6982 RF: call_from_parser - move code into "else" to simplify reading etc
  datalad/cli/exec.py
Labels: semver-internal

#6986 Provide "/dev/null" (b:\nul on 💾 Windows) instead of empty string as a git-repo to avoid reading local repo configuration
  datalad/config.py
  datalad/tests/test_config.py
Labels: semver-patch

#6995 TST: test_stalling -- wait x10 not just x5 time
  datalad/support/tests/test_parallel.py
Labels: spurious-test-failure, tests, semver-tests

#6981 Add workflow for autogenerating changelog snippets
  .github/workflows/add-changelog-snippet.yml
  tools/ci/mkchlog-snippet.py
Labels: semver-internal

#6987 Run pytests in parallel (-n 2) on appveyor
  .appveyor.yml
Labels: semver-tests

#6976 BF: make logic more consistent for files=[] argument (which is False but not None)
  datalad/dataset/gitrepo.py
  datalad/support/annexrepo.py
  datalad/support/gitrepo.py
Labels: semver-patch, release
