Repository datalad/datalad, pull requests merged in 2022-10, with the labels that each got.

#7066 BF: disable testing for exit code for batched process.
  datalad/tests/test_cmd.py
Labels: spurious-test-failure, semver-tests, CHANGELOG-missing

#7076 datalad-deprecated moved to pytest
  .github/workflows/test_extensions.yml
Labels: semver-tests

#7073 RF: remove unused code str-ing PurePath
  changelog.d/pr-7073.md
  datalad/dataset/repo.py
Labels: semver-internal

#7067 Let `EnsureChoice` report the value is failed validating
  changelog.d/pr-7067.md
  datalad/support/constraints.py
Labels: semver-patch

#7075 BF: lock across threads check/instantiation of Flyweight instances
  changelog.d/pr-7075.md
  datalad/dataset/repo.py
  datalad/support/tests/test_parallel.py
Labels: semver-patch

#7068 Ensure that `BatchedCommandError` is raised if the subprocesses of `BatchedCommand` fails or raises a `CommandError`
  changelog.d/pr-7068.md
  datalad/cmd.py
  datalad/support/annexrepo.py
  datalad/tests/test_cmd.py
Labels: semver-internal

#7072 BF: don't write output from within sshrun
  changelog.d/pr-7072.md
  datalad/core/distributed/tests/test_clone.py
  datalad/support/sshconnector.py
  datalad/support/sshrun.py
Labels: semver-patch

#7082 Update GitHub Actions action versions
  .github/dependabot.yml
  .github/workflows/benchmarks.yml
  .github/workflows/docbuild.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/shellcheck.yml
  .github/workflows/test-nose.yml
  .github/workflows/test_crippled.yml
  .github/workflows/test_extensions.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_win2019_disabled
  .github/workflows/typing.yml
  .github/workflows/update-contributors.yml
  changelog.d/pr-7082.md
Labels: semver-internal

#7002 Fix test helpers for results
  changelog.d/pr-7002.md
  datalad/core/distributed/tests/test_clone.py
  datalad/tests/utils_pytest.py
  datalad/utils.py
Labels: semver-tests

#7081 PR template: remove Changelog entries, refer to scriv
  .github/PULL_REQUEST_TEMPLATE.md
Labels: semver-internal, release

#7084 release template etc fixups
  CHANGELOG.md
  changelog.d/templates/new_fragment.md.j2
  docs/source/changelog.rst
  tools/ci/mkchlog-snippet.py
Labels: semver-internal

#7095 Make sure to re-initialise git repo
  changelog.d/pr-7095.md
  datalad/distributed/create_sibling_ria.py
Labels: semver-patch

#7088 Prevent adding duplicate entries to .gitmodules
  changelog.d/pr-7088.md
  datalad/core/local/tests/test_save.py
  datalad/support/gitrepo.py
Labels: semver-patch

#7085 BF: Missing import in clone
  datalad/core/distributed/clone.py
  datalad/core/distributed/clone_ria.py
  datalad/core/distributed/clone_utils.py
Labels: semver-internal

#6861 DOC: Document ria url formats in docstring
  datalad/distributed/create_sibling_ria.py
Labels: semver-documentation

#7102 RF `datalad.interface.utils.eval_results()`
  datalad/interface/utils.py
Labels: semver-internal

#7093 [BF] Prevent double yielding of impossible get result
  changelog.d/pr-7093.md
  datalad/distribution/get.py
  datalad/distribution/tests/test_get.py
Labels: semver-patch

#7103 Report repository name in `create_sibling_ghlike` dry run
  changelog.d/pr-7103
  datalad/distributed/create_sibling_ghlike.py
Labels: semver-patch

#7107 Fix `PWD` environment entry if `cwd` provided to `Runner()` or `Runner.run()` is a `Path`-object
  changelog.d/pr-7107.md
  datalad/runner/runner.py
  datalad/runner/tests/test_witless_runner.py
Labels: semver-internal, release

#7112 Various small fixups ran after looking post-release and trying to build Debian package
  CHANGELOG.md
  changelog.d/pr-7103
  changelog.d/pr-7112.md
  datalad/cli/tests/test_main.py
  datalad/metadata/tests/test_metadata.py
  docs/source/changelog.rst
Labels: semver-patch

#7111 Use datalad/release-action
  .datalad-release-action.yaml
  .github/workflows/add-changelog-snippet.yml
  .github/workflows/release.yml
  changelog.d/pr-7111.md
  changelog.d/pr-7112.md
  changelog.d/scriv.ini
  tools/ci/mkchlog-snippet.py
  tools/ci/release-comment.py
Labels: semver-internal

#7117 BF: Fix add-archive-contents try-finally statement by defining variable earlier
  changelog.d/pr-7117.md
  datalad/local/add_archive_content.py
Labels: semver-patch

#7119 Improve `datalad.support.tests.test_parallel.py::test_stalling`
  changelog.d/pr-7119.md
  datalad/support/tests/test_parallel.py
Labels: semver-tests

#7123 Fix RIA file URL reporting in exception handling
  changelog.d/pr-7123.md
  datalad/distributed/ora_remote.py
Labels: semver-patch

#7125 Unrestrict pytest and pytest-cov versions
  changelog.d/pr-7125.md
  setup.py
Labels: semver-dependencies
