Repository datalad/datalad, pull requests merged in 2022-03, with the labels that each got.

#6516 Move cast helpers out of datalad core
  tools/cast2asciinema
  tools/cast2narration
  tools/cast2rst
  tools/cast2script
  tools/cast_bash.rc
  tools/cast_live
Labels: semver-documentation

#6515 Set a minimum dependency on keyrings version 20.0
  setup.py
Labels: semver-patch

#6513 Disable internal save-result rendering in update()
  datalad/distribution/update.py
Labels: semver-patch

#6493 Relax permissions needed in RIA stores
  datalad/distributed/ora_remote.py
  datalad/distributed/tests/test_ria_basics.py
  datalad/tests/test_utils.py
  datalad/utils.py
Labels: semver-patch, team-remotes

#6505 RF copy_file() with a cleaner (cached) Repo method access
  datalad/local/copy_file.py
  datalad/local/tests/test_copy_file.py
Labels: semver-patch

#6525 ORA: discontinue use of duplicate SSHManager
  datalad/distributed/ora_remote.py
Labels: semver-patch

#6521 require_dataset() uniformly raises NoDatasetFound
  datalad/distribution/dataset.py
  datalad/distribution/tests/test_dataset.py
  datalad/local/configuration.py
Labels: semver-patch

#6529 Handle partially delivered encoded data
  datalad/dataset/gitrepo.py
  datalad/runner/exception.py
  datalad/runner/gitrunner.py
  datalad/runner/protocol.py
  datalad/runner/tests/test_utils.py
  datalad/runner/utils.py
  datalad/support/annexrepo.py
Labels: semver-internal

#6532 Stop including annex-bundle info in SSH connection socket name
  datalad/support/sshconnector.py
  datalad/support/tests/test_annexrepo.py
  datalad/support/tests/test_gitrepo.py
  datalad/support/tests/test_sshconnector.py
Labels: semver-minor, team-core

#6533 Make SSH remote annex bundle sensing configurable and off by default
  datalad/interface/common_cfg.py
  datalad/support/sshconnector.py
Labels: semver-minor, team-core

#6537 Stop forcefully disabling keyboard-interactive SSH auth
  datalad/support/sshconnector.py
Labels: platform-windows, semver-patch

#6542 BF(TST): Skip 3 tests if root -- PermissionError not raised
  datalad/distributed/tests/test_ria_basics.py
  datalad/tests/test_utils.py
Labels: semver-tests, CHANGELOG-missing

#6557 BF: account for "No such password" in addition to not found returned by keyring
  datalad/support/keyring_.py
Labels: semver-patch, CHANGELOG-missing

#6562 Make `datalad.cli.tests.test_main.run_main()` also capture UI output
  datalad/cli/tests/test_main.py
Labels: semver-internal, tests, team-core

#6563 Deduplicate top-level CLI exception handler output
  datalad/cli/main.py
Labels: team-core

#6546 Enable coverage for subprocesses
  .appveyor.yml
  .travis.yml
  tools/coverage-bin/datalad
  tools/coverage-bin/sitecustomize.py
Labels: semver-tests

#6565 Stop advertising a broken quoting solution for remote commands.
  datalad/distribution/create_sibling.py
  datalad/support/sshconnector.py
Labels: documentation, semver-internal

#6553 Enforce system ssh client usage on Windows
  datalad/interface/common_cfg.py
  datalad/support/sshconnector.py
Labels: semver-internal

#6576 Channel progress logging by AnnexSpecialRemoteProgressBar to git-annex
  datalad/customremotes/base.py
  datalad/ui/progressbars.py
Labels: semver-patch

#6588 ENH: add "short" option to @auto_repr and use for BatchedAnnex
  datalad/support/annexrepo.py
  datalad/tests/test_utils.py
  datalad/utils.py
Labels: DX, semver-patch

#6587 RF: set allowed-url/http in test HOME .git/config instead of config calls per instance
  datalad/__init__.py
  datalad/support/annexrepo.py
Labels: performance, merge-if-ok, cherry-pick-to-maint, semver-patch

#6591 Consolidate entrypoint processing on importlib.metadata
  datalad/api.py
  datalad/cli/helpers.py
  datalad/interface/test.py
  datalad/local/run_procedure.py
  datalad/local/wtf.py
  datalad/metadata/extractors/tests/test_base.py
  datalad/metadata/metadata.py
  datalad/support/entrypoints.py
  setup.py
Labels: performance, semver-performance, team-core
