Repository datalad/datalad, pull requests merged in 2022-06, with the labels that each got.

#6727 DOC: fixup of docstring for skip_ssh
  datalad/tests/utils.py
Labels: semver-documentation

#6726 BF(TST): RO operations - add test directory into git safe.directory
  datalad/support/tests/test_annexrepo.py
Labels: semver-patch, release

#6729 In addition to default (system) ssh version, report configured ssh; fix ssh version parsing on Windows
  datalad/support/external_versions.py
  datalad/support/tests/test_external_versions.py
Labels: semver-patch

#6735 More selective `unlock` progress reporting in noninteractive cases
  datalad/local/unlock.py
Labels: semver-patch

#6747 Remove unused and untested log filter helpers
  datalad/log.py
Labels: semver-minor

#6739 ENH: Improve add-archive-contents progressbar following #6735 & #6734
  datalad/local/add_archive_content.py
Labels: semver-patch

#6738 MNT: Remove ``eval_file_type()`` from code base
  datalad/core/distributed/push.py
  datalad/core/local/diff.py
  datalad/distribution/create_sibling.py
  datalad/local/copy_file.py
  datalad/support/gitrepo.py
Labels: semver-internal

#6734 Design document on progress reporting
  docs/source/design/index.rst
  docs/source/design/progress_reporting.rst
Labels: semver-documentation

#6745 MNT: Modernize export-archive
  datalad/local/export_archive.py
  datalad/support/gitrepo.py
Labels: semver-patch

#6750 BF: push to github - remove datalad-push-default-first config only in non-dry run to ensure we push default branch separately in next step
  datalad/support/gitrepo.py
Labels: semver-patch, release

#6706 MNT: Factor out helper function used in core and next from ria functionality
  datalad/distributed/create_sibling_ria.py
  datalad/distribution/utils.py
Labels: semver-internal

#6746 Polish trace back-logging and other logging aspects
  datalad/interface/common_cfg.py
  datalad/log.py
  datalad/tests/test_log.py
Labels: documentation, semver-minor

#6737 Prevent reentry of a runner instance
  datalad/runner/nonasyncrunner.py
  datalad/runner/tests/test_threadsafety.py
Labels: semver-internal

#6757 Properly include "data packages" in project
  _datalad_build_support/setup.py
Labels: semver-internal

#6756 ENH: LogProgressBar to gain "start" reporting
  datalad/ui/progressbars.py
Labels: semver-minor

#6762 BF(workaround to #6759): if saving credential failed, just log error and continue
  datalad/downloaders/credentials.py
Labels: UX, semver-patch

#6765 Prevent duplicated result rendering when searching in default datasets
  datalad/metadata/search.py
Labels: semver-internal, release

#6754 Preserve final trailing slash in ``call_git()`` output
  datalad/dataset/gitrepo.py
  datalad/tests/test_config.py
Labels: semver-patch

#6777 Fix test errors caused by updated chardet v5 release
  setup.py
Labels: semver-internal

#6772 Do not skip file-URL tests on windows
  datalad/support/tests/test_network.py
Labels: semver-internal
