Repository datalad/datalad, pull requests merged in 2022-02, with the labels that each got.

#6391 Key interface documentation
  datalad/cli/common_args.py
  datalad/cli/tests/test_exec.py
  datalad/interface/base.py
  datalad/interface/common_opts.py
  datalad/interface/utils.py
  docs/source/design/cli.rst
  docs/source/modref.rst
Labels: documentation, semver-documentation, team-core

#6392 Remove unused helpers from datalad.interface.utils
  datalad/interface/utils.py
Labels: semver-minor, team-core

#6394 Simplify result rendering, and fix #6393
  datalad/cli/main.py
  datalad/interface/utils.py
Labels: semver-patch, team-core

#6396 Update PR template with changelog template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: semver-internal

#6398 Reduce code duplication and add documentation
  datalad/support/json_py.py
Labels: semver-internal

#6402 Appveyor update
  .appveyor.yml
Labels: semver-tests

#6405 Fix fallout from CLI update
  datalad/cli/parser.py
  datalad/cmdline/main.py
Labels: semver-patch

#6332 ConfigManager supports bare repos
  datalad/config.py
  datalad/tests/test_config.py
Labels: bare-mode, semver-minor, cmd-config(urgation)

#6411 DOC: include status in Python API overview
  docs/source/modref.rst
Labels: semver-documentation

#6422 Cleanup unused imports
  datalad/interface/utils.py
Labels: semver-internal, team-core

#6429 TST: mark test_source_candidate_subdataset as @slow
  datalad/distribution/tests/test_get.py
Labels: semver-tests

#6414 RF: use parse_known_args instead of _parse_known_args
  datalad/cli/parser.py
Labels: semver-internal, team-core

#6416 DOC: run - adjust description for -i/-o to mention that it could be a directory
  datalad/core/local/run.py
Labels: semver-documentation, team-core

#6428 MNT: remove deprecated mktemp from add-archive-content
  datalad/local/add_archive_content.py
Labels: semver-internal

#6421 Prevent double-rendering of save results by run.
  datalad/core/local/run.py
Labels: semver-patch, team-core

#6413 MNT: Deprecate annexstatus
  datalad/core/local/save.py
  datalad/core/local/tests/test_save.py
  datalad/support/annexrepo.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_fileinfo.py
  datalad/support/tests/test_repo_save.py
  datalad/tests/utils.py
Labels: semver-patch, team-gitannex

#5796 git-credential interfaces (datalad's in Git and vice versa)
  .appveyor.yml
  .github/workflows/benchmarks.yml
  .github/workflows/test_crippled.yml
  .github/workflows/test_extensions.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_win2019_disabled
  .travis.yml
  datalad/downloaders/__init__.py
  datalad/downloaders/base.py
  datalad/downloaders/credentials.py
  datalad/downloaders/http.py
  datalad/downloaders/providers.py
  datalad/downloaders/tests/test_credentials.py
  datalad/interface/common_cfg.py
  datalad/local/gitcredential.py
  datalad/local/gitcredential_datalad.py
  datalad/local/tests/test_gitcredential.py
  docs/source/credentials.rst
  docs/source/design/credentials.rst
  docs/source/index.rst
  setup.py
Labels: semver-minor, team-git

#6415 Make CLI autocompletion snappy
  datalad/cli/helpers.py
  datalad/cli/main.py
  datalad/cli/parser.py
  datalad/cli/tests/test_main.py
Labels: semver-minor, team-core

#6433 Simplify pattern 'EnsureChoice(..) | EnsureNone'
  datalad/distributed/create_sibling_ria.py
  datalad/local/wtf.py
Labels: semver-internal

#6430 Enable custom "on-failure" settings and employ for `run` with `on_failure='stop'` by default
  datalad/cli/common_args.py
  datalad/core/local/run.py
  datalad/core/local/tests/test_run.py
Labels: cmd-run/rerun, semver-minor, team-core

#6425 Remove an unnecessary warning from the runner
  datalad/runner/nonasyncrunner.py
Labels: semver-internal

#6434 Tailor help message to API
  datalad/core/local/run.py
Labels: semver-patch

#6379 Fix AnnexRepo.whereis key=True mode operation, and add batch mode support
  datalad/support/annexrepo.py
  datalad/support/tests/test_annexrepo.py
Labels: merge-if-ok, semver-patch, release, CHANGELOG-missing

#6435 Use `self.repo` in `RegisterUrl`-constructor
  datalad/local/addurls.py
  datalad/local/tests/test_addurls.py
Labels: semver-internal

#6436 OPT+RF: create-sibling --since=^ -- diff to HEAD, use "^" instead of ""
  datalad/distribution/create_sibling.py
  datalad/distribution/tests/test_create_sibling.py
Labels: performance, semver-minor

#6291 Warn when saving Windows-incompatible file names
  datalad/consts.py
  datalad/core/local/tests/test_save.py
  datalad/interface/common_cfg.py
  datalad/support/gitrepo.py
Labels: semver-patch, CHANGELOG-missing

#6439 Demote BatchedCommand remaining content-warning to debug message
  datalad/cmd.py
  datalad/local/addurls.py
  datalad/support/annexrepo.py
Labels: semver-internal

#6440 Salvage parts of #5695
  datalad/core/local/run.py
  datalad/interface/tests/test_utils.py
  datalad/interface/utils.py
Labels: semver-patch

#6448 BF: define git config and GIT_ASKPASS in the setup_package instead of each CI
  .appveyor.yml
  .github/workflows/test_crippled.yml
  .github/workflows/test_extensions.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_win2019_disabled
  .travis.yml
  datalad/__init__.py
Labels: semver-tests, CHANGELOG-missing

#6446 BF/RF: Silence save result rendering in clone and download url
  datalad/core/distributed/clone.py
  datalad/distribution/install.py
  datalad/interface/utils.py
  datalad/local/download_url.py
Labels: semver-patch

#6450 Split Ubuntu CI run to prevent timeouts
  .appveyor.yml
Labels: semver-tests

#6458 Silence result rendering in run's use of drop()
  datalad/core/local/run.py
Labels: semver-patch

#6464 Issue #6461 work on `unlock()`
  datalad/local/unlock.py
Labels: semver-internal

#6466 MNT: use generator return_type in internal save call in clone
  datalad/core/distributed/clone.py
Labels: semver-patch

#6468 Update `configuration()` in the spirit of #6461
  datalad/local/configuration.py
Labels: semver-patch

#6470 MNT: Silence result rendering of copy-file's internal save() call
  datalad/local/copy_file.py
Labels: semver-patch

#6476 Unify keyword in the spirit of issue #6461
  datalad/distribution/get.py
Labels: semver-internal

#6475 Update foreach-dataset|no_annex|remove|aggregate-metadata() in the spirit of #6461
  datalad/local/foreach_dataset.py
  datalad/local/no_annex.py
  datalad/local/remove.py
  datalad/metadata/aggregate.py
Labels: semver-patch

#6465 Update `addurls()` in the spirit of #6461
  datalad/local/addurls.py
Labels: semver-patch

#6467 Update `subdatasets()` in the spirit of #6461
  datalad/local/subdatasets.py
  datalad/local/tests/test_subdataset.py
Labels: semver-patch

#6471 Update `create_sibling*()` in the spirit of #6461
  datalad/distributed/create_sibling_ghlike.py
  datalad/distributed/create_sibling_gitlab.py
  datalad/distributed/create_sibling_ria.py
  datalad/distributed/tests/test_create_sibling_ria.py
Labels: semver-patch, team-services

#6481 Bring back the standard CLI interface for special remotes
  datalad/cli/tests/test_main.py
  datalad/customremotes/archives.py
  datalad/customremotes/datalad.py
  datalad/customremotes/main.py
Labels: merge-if-ok, semver-patch

#6472 MNT: Silence internal command calls in install
  datalad/distribution/install.py
Labels: semver-patch

#6424 `run` improvements towards #6401
  datalad/core/local/run.py
  datalad/core/local/tests/test_run.py
  docs/source/design/index.rst
  docs/source/design/provenance_capture.rst
Labels: cmd-run/rerun, semver-patch, team-core

#6484 Replace custom entrypoint with standard for special remotes
  datalad/distributed/ora_remote.py
Labels: semver-patch

#6469 MNT: Silence internal command calls' result rendering in add-readme
  datalad/local/add_readme.py
Labels: semver-patch

#6501 DOC: Add remark to old credential env vars
  datalad/support/keyring_.py
Labels: semver-documentation

#6457 Restore the previous result rendering of ``create -c <proc>`` and ``run-procedure``
  datalad/core/local/create.py
  datalad/local/run_procedure.py
  datalad/resources/procedures/cfg_metadatatypes.py
  datalad/resources/procedures/cfg_noannex.py
  datalad/resources/procedures/cfg_text2git.py
  datalad/resources/procedures/cfg_yoda.py
Labels: semver-patch

#6502 Replace left-over (unused) mode label in CLI parser
  datalad/cli/parser.py
Labels: semver-patch

#6495 BF: No object tree in RIA w/o special remote
  datalad/customremotes/ria_utils.py
  datalad/distributed/create_sibling_ria.py
  datalad/distributed/tests/test_create_sibling_ria.py
  datalad/distributed/tests/test_ria_git_remote.py
Labels: semver-patch, team-gitannex, team-remotes

#6500 Guard RI-type determination
  datalad/core/distributed/clone.py
  datalad/support/network.py
Labels: semver-patch, team-core

#6473 Unify interface keyword args of metadata commands according to issue #6461
  datalad/metadata/aggregate.py
  datalad/metadata/extractors/datalad_core.py
  datalad/metadata/search.py
  datalad/metadata/tests/test_search.py
Labels: semver-internal

#6507 BF: do not use BaseDownloader instance wide InterProcessLock - resolves stalling or errors during parallel installs
  datalad/downloaders/base.py
Labels: semver-patch, release
