Repository datalad/datalad, pull requests merged in 2022-01, with the labels that each got.

#6336 Install all data files under `datalad/`
  MANIFEST.in
  setup.py
Labels: semver-patch

#6319 BF(Q&D): do not crash - issue warning - if template fails to format
  datalad/distribution/get.py
  datalad/distribution/tests/test_get.py
Labels: semver-patch

#6341 Make version detection robust to GIT_DIR specification
  datalad/_version.py
Labels: semver-patch

#6343 Warn just once about incomplete git config
  datalad/config.py
Labels: UX, semver-patch

#6346 Docs, infra: Attempt to fix missing bullet points by pinning Sphinx and RTD theme versions
  setup.py
Labels: semver-documentation

#6353 BF(workaround,TST): mark two tests as @known_failure_githubci_win
  datalad/core/distributed/tests/test_push.py
  datalad/distribution/tests/test_install.py
Labels: semver-patch

#6317 BF: When download-url gets Pathobject as path convert it to a string
  datalad/local/download_url.py
Labels: semver-patch

#6358 Remove code duplication
  datalad/support/constraints.py
Labels: DX, semver-internal

#6361 BF(TST): add another condition to skip under http_proxy set
  datalad/local/tests/test_download_url.py
Labels: cherry-pick-to-maint, semver-patch

#6374 Remove two(!) copies of a test
  datalad/cmdline/tests/test_main.py
Labels: semver-tests

#6363 BF: python 3.10 compatibility fixes
  .travis.yml
  datalad/cmdline/helpers.py
  datalad/cmdline/tests/test_main.py
  datalad/support/tests/test_annexrepo.py
Labels: semver-patch

#6364 Drop python 3.6 support, remove some no longer needed kludges, merge of maint
  .appveyor.yml
  .github/workflows/test_crippled.yml
  .travis.yml
  CONTRIBUTING.md
  datalad/cmdline/helpers.py
  datalad/cmdline/tests/test_main.py
  datalad/distribution/tests/test_create_sibling.py
  datalad/support/network.py
  datalad/support/tests/test_annexrepo.py
  datalad/support/tests/test_network.py
  datalad/tests/utils.py
  setup.py
Labels: semver-minor

#6371 Allow multiple threads in ProducerConsumer with python <= 3.7
  datalad/support/parallel.py
  datalad/support/tests/test_parallel.py
Labels: cherry-pick-to-maint, semver-internal

#6359 BF(TST): clean command should be invoked within a dataset
  datalad/cmdline/tests/test_main.py
Labels: semver-tests

#6360 BF: condition access to isatty to have stream eval to True
  datalad/utils.py
Labels: semver-patch

#6355 BF: ORA over HTTP tried to check archive
  datalad/distributed/ora_remote.py
  datalad/distributed/tests/test_ora_http.py
  tools/coverage-bin/git-annex-remote-ora
Labels: semver-patch

#6387 MNT/RF: Retire get_refds_path and replace its usages with require_dataset()
  datalad/distribution/get.py
  datalad/distribution/install.py
  datalad/distribution/tests/test_get.py
  datalad/interface/base.py
  datalad/metadata/aggregate.py
  datalad/metadata/metadata.py
Labels: semver-internal, team-core

#6306 Migrate configuration command from mihextras extention
  datalad/interface/__init__.py
  datalad/interface/common_cfg.py
  datalad/local/configuration.py
  datalad/local/tests/test_configuration.py
  docs/source/cmdline.rst
  docs/source/modref.rst
Labels: semver-minor, cmd-config(urgation), team-core
