Repository datalad/datalad, pull requests merged in 2022-04, with the labels that each got.

#6543 UX: Make export-to-figshare yield an impossible result instead of a RunTimeError in dirty ds
  datalad/distributed/export_to_figshare.py
Labels: semver-patch

#6604 Wrong variable name in conditional code path
  datalad/api.py
Labels: semver-internal

#6608 Add datalad-metalad to tested extensions
  .github/workflows/test_extensions.yml
Labels: semver-tests

#6550 Fixing test failures with recent annex
  datalad/core/local/tests/test_save.py
  datalad/core/local/tests/test_status.py
  datalad/distributed/drop.py
  datalad/distributed/tests/test_drop.py
  datalad/support/annex_utils.py
  datalad/support/annexrepo.py
  datalad/support/tests/test_annexrepo.py
Labels: cherry-pick-to-maint, semver-patch, team-gitannex

#6601 NF: register_config()
  datalad/__init__.py
  datalad/cli/main.py
  datalad/coreapi.py
  datalad/interface/common_cfg.py
  datalad/support/entrypoints.py
  datalad/support/extensions.py
  datalad/support/tests/test_extensions.py
  docs/source/modref.rst
Labels: semver-minor

#6594 Enable loading select extensions on CLI startup or API import
  datalad/cli/main.py
  datalad/coreapi.py
  datalad/interface/common_cfg.py
  datalad/support/entrypoints.py
Labels: semver-minor, team-core

#6610 RF/OPT: do not call get_git_environ_adjusted twice for BatchedCommand
  datalad/cmd.py
Labels: semver-internal

#6535 UX: Better message when ORA does not find store via HTTP
  datalad/customremotes/__init__.py
  datalad/distributed/ora_remote.py
Labels: UX, semver-patch, team-remotes

#6609 Don't use download_url in ORA
  datalad/distributed/ora_remote.py
Labels: semver-patch, team-remotes

#6540 DOC: sshconnector - remove duplicate docstrings in subclasses
  datalad/support/sshconnector.py
Labels: semver-documentation

#6581 BF+OPT: allow to save change where file becomes a folder, and avoid multiple traversals in _save
  datalad/core/local/tests/test_save.py
  datalad/support/annexrepo.py
  datalad/support/gitrepo.py
Labels: performance, semver-patch

#6603 BF/RF: create-sibling follow diff with constant_refs=False + operate on committed subds
  datalad/distribution/create_sibling.py
  datalad/distribution/tests/test_create_sibling.py
Labels: semver-minor

#6616 BF: Wrong annex version tested
  datalad/core/local/tests/test_status.py
  datalad/support/annex_utils.py
  datalad/support/annexrepo.py
  datalad/support/tests/test_annexrepo.py
Labels: semver-tests

#6606 Sanitize AppVeyor's known_hosts
  .appveyor.yml
Labels: semver-tests

#6580 Use yielding annex record calls for `drop`
  datalad/distributed/drop.py
  datalad/support/annexrepo.py
  datalad/support/tests/test_annexrepo.py
Labels: semver-internal

#6631 MNT: Require importlib-metadata >=3.6 for Python < 3.10 for entry_points taking kwargs
  setup.py
Labels: semver-patch

#6628 ENH: include version of datalad in tests teardown Versions: report
  datalad/__init__.py
Labels: DX, merge-if-ok, semver-tests

#6618 Factor out actual data transfer in push
  datalad/core/distributed/push.py
  datalad/distributed/create_sibling_ghlike.py
  datalad/tests/test_utils.py
  datalad/utils.py
Labels: semver-internal

#6635 Demote (to level 1 from DEBUG) and speed-up API doc logging (parseParameters)
  datalad/dochelpers.py
Labels: semver-internal, release

#6637 Remove unsupported parameter create_sibling_ria(existing=None)
  datalad/distributed/create_sibling_ria.py
Labels: semver-patch

#6638 Remove two too prominent create() INFO log message that duplicate DEBUG log and harmonize some other log messages
  datalad/core/distributed/clone.py
  datalad/core/distributed/push.py
  datalad/core/local/create.py
  datalad/core/local/status.py
  datalad/customremotes/base.py
  datalad/dataset/gitrepo.py
Labels: semver-internal

#6648 RF: get rid of asyncio import by defining few noops from SubprocessProtocol
  datalad/runner/protocol.py
Labels: semver-performance

#6661 Fix `GitRepo.get_branch_commits_()` to handle branch names conflicts with paths
  datalad/support/gitrepo.py
  datalad/support/tests/test_gitrepo.py
Labels: semver-patch, team-git

#6625 Change a key-value pair in drop result record
  datalad/distributed/drop.py
  datalad/distributed/tests/test_drop.py
Labels: semver-patch

#6663 BF: Sanitize keys before checking content availability
  datalad/distributed/ora_remote.py
  datalad/support/annex_utils.py
  datalad/support/annexrepo.py
  datalad/support/tests/test_fileinfo.py
Labels: semver-patch
