Repository datalad/datalad, pull requests merged in 2022-12, with the labels that each got.

#7210 Let CLI report on exception causes
  changelog.d/pr-7210.md
  datalad/cli/main.py
  datalad/support/exceptions.py
  datalad/support/tests/test_captured_exception.py
Labels: semver-patch

#7215 Reorder commands in ORA get via SSH
  changelog.d/pr-7215.md
  datalad/distributed/ora_remote.py
Labels: semver-patch

#7218 Fix setup.py for type-check action
  setup.py
Labels: semver-internal

#7221 Install Singularity 3 from official DEB
  .github/workflows/test_extensions.yml
Labels: semver-tests

#7209 Use MemoryKeyring in test
  changelog.d/pr-7209.md
  datalad/conftest.py
Labels: semver-tests

#7213 NF: make extra_remote_settings configurable in git config
  .zenodo.json
  changelog.d/pr-7213.md
  datalad/distributed/create_sibling_ghlike.py
  datalad/distributed/create_sibling_gin.py
  datalad/distributed/create_sibling_gitea.py
  datalad/distributed/create_sibling_github.py
  datalad/distributed/create_sibling_gitlab.py
  datalad/distributed/create_sibling_gogs.py
Labels: semver-minor

#7217 Don't be scary when failing to annex-enable
  changelog.d/pr-7217.md
  datalad/distribution/siblings.py
Labels: UX, semver-patch

#6682 RF special remote base classes
  datalad/customremotes/__init__.py
  datalad/customremotes/archives.py
  datalad/customremotes/base.py
  datalad/customremotes/main.py
  datalad/customremotes/tests/test_main.py
Labels: semver-internal

#7226 Allow for brackets in PY&CMD doc markups
  changelog.d/pr-7226.md
  datalad/cli/interface.py
  datalad/cli/tests/test_interface.py
  datalad/interface/base.py
  datalad/interface/tests/test_docs.py
Labels: semver-patch, release

#7231 Move timeout processing out of exception handler processing
  datalad/tests/test_cmd.py
Labels: semver-internal

#7220 RF: get_modules_ - avoid O(N^2) if paths provided via use of get_limited_paths
  benchmarks/api.py
  changelog.d/pr-7189.md
  datalad/support/gitrepo.py
  datalad/support/path.py
  datalad/support/tests/test_gitrepo.py
  datalad/support/tests/test_path.py
  tox.ini
Labels: semver-performance

#7230 Use --include=* or --anything instead of --copies 0 to speed up get_content_annexinfo
  changelog.d/pr-7230.md
  datalad/support/annexrepo.py
Labels: semver-performance

#7235 RF ORA
  changelog.d/pr-7235.md
  datalad/core/distributed/clone_utils.py
  datalad/customremotes/ria_remote.py
  datalad/customremotes/ria_utils.py
  datalad/distributed/ora_remote.py
  datalad/distributed/tests/test_ria_basics.py
  datalad/distributed/tests/test_ria_git_remote.py
  setup.py
Labels: semver-minor
