Repository datalad/datalad, pull requests merged in 2023-07, with the labels that each got.

#7445 DOC: clarify description of the "install" interface to reflect its convoluted behavior
  changelog.d/pr-7445.md
  datalad/distribution/install.py
Labels: release, semver-documentation

#7403 Type annotate get_status_dict and note that we can pass Exception or CapturedException which is not subclass
  changelog.d/pr-7403.md
  datalad/core/local/save.py
  datalad/interface/results.py
  datalad/support/gitrepo.py
  datalad/support/tests/test_repo_save.py
  docs/source/design/result_records.rst
  tox.ini
Labels: semver-patch

#7431 Increase minimal Git version to 2.25
  changelog.d/pr-7431.md
  datalad/core/local/tests/test_diff.py
  datalad/core/local/tests/test_save.py
  datalad/support/gitrepo.py
Labels: semver-minor

#7463 Pass branch option into recursive call within Install - for the cases whenever install is invoked with URL(s)
  changelog.d/pr-7463.md
  datalad/distribution/install.py
  datalad/distribution/tests/test_install.py
Labels: semver-patch
