Repository datalad/datalad, pull requests merged in 2023-02, with the labels that each got.

#7272 Compact badges
  README.md
Labels: semver-documentation

#7273 create-sibling: Use C.UTF-8 locale instead of C
  changelog.d/pr-7273.md
  datalad/distribution/create_sibling.py
Labels: semver-patch

#7275 sphinx: do not call build_schema
  docs/source/conf.py
Labels: semver-internal

#7271 Codespell more (CHANGELOGs etc) and remove custom CLI options from tox.ini
  .codespell-ignorewords
  .codespellrc
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  changelog.d/pr-7271.md
  docs/design.rst
  docs/source/basics.rst
  docs/source/changelog.rst
  docs/source/design/drop.rst
  docs/source/design/exception_handling.rst
  tools/ci/install-annex.sh
  tox.ini
Labels: semver-internal

#7305 BF: declare string r-aw for the \. escape
  datalad/distributed/ora_remote.py
Labels: semver-patch
