Repository datalad/datalad, pull requests merged in 2023-04, with the labels that each got.

#7368 ENH: push - delist hint if there is only one value
  datalad/core/distributed/push.py
Labels: UX

#7367 BF: do not include (by default) dead special remotes in get_special_remotes
  datalad/core/distributed/clone_utils.py
  datalad/support/annexrepo.py
Labels: semver-patch

#7341 Type-annotate `datalad/support/gitrepo.py`
  changelog.d/pr-7341.md
  datalad/support/gitrepo.py
  datalad/support/path.py
  datalad/typing.py
  setup.cfg
  setup.py
  tox.ini
Labels: semver-internal

#7361 ENH(TST): add DATALAD_TESTS_CREDENTIALS=system for known credentials to be used during tests
  CONTRIBUTING.md
  datalad/conftest.py
  datalad/interface/common_cfg.py
Labels: semver-tests
