Repository datalad/datalad, pull requests merged in 2023-03, with the labels that each got.

#7280 BF: path from .gitmodules could not be used with source candidate template
  changelog.d/pr-7280.md
  datalad/distribution/get.py
  datalad/distribution/tests/test_get.py
  datalad/support/gitrepo.py
Labels: semver-patch

#7289 Api docs patch
  changelog.d/pr-7289.md
  datalad/distributed/create_sibling_ria.py
  docs/source/modref.rst
Labels: semver-documentation

#7314 Add scriv to devel-utils
  setup.py
Labels: semver-internal

#7321 MNT: remove leftover distutils import
  datalad/distribution/create_sibling.py
Labels: semver-internal

#7322 Do not render (empty) WTF report on other records
  changelog.d/pr-7322.md
  datalad/local/tests/test_wtf.py
  datalad/local/wtf.py
Labels: UX, semver-patch

#7335 Fix pytest_util with_tempfile example
  datalad/tests/utils_pytest.py
Labels: semver-documentation

#7331 Skip or xfail some currently failing or stalling tests
  changelog.d/pr-7331.md
  datalad/core/distributed/tests/test_clone.py
  datalad/distribution/tests/test_siblings.py
  datalad/support/tests/test_annexrepo.py
  datalad/tests/test_archives.py
  datalad/tests/utils_pytest.py
Labels: DX, tests, semver-tests

#7327 Type-annotate `datalad/support/globbedpaths.py`
  changelog.d/pr-7327.md
  datalad/support/globbedpaths.py
  tox.ini
Labels: semver-internal

#7330 Remove reset() kludge for tqdm, add version requirement
  changelog.d/pr-7330.md
  datalad/ui/progressbars.py
  setup.py
Labels: semver-minor

#7312 BF: GitRepo.merge do not allow merging unrelated unconditionally
  changelog.d/pr-7312.md
  datalad/distribution/tests/test_update.py
  datalad/support/gitrepo.py
Labels: semver-patch

#7323 Adopt call_annex_success helper from next
  datalad/support/annexrepo.py
Labels: semver-internal

#7339 Type-annotate some more files in `datalad/support/`
  changelog.d/pr-7339.md
  datalad/support/annex_utils.py
  datalad/support/ansi_colors.py
  datalad/support/cookies.py
  datalad/support/digests.py
  tox.ini
Labels: semver-internal

#7333 Fix datalad special remote error reporting
  changelog.d/pr-7333.md
  datalad/customremotes/datalad.py
Labels: semver-patch

#7308 BF: Don't skip subds underneath paths in reckless & recursive drop
  datalad/distributed/drop.py
  datalad/distributed/tests/test_drop.py
Labels: semver-patch

#7238 ENH(TST): add a test for assert_raises since concern was raised
  datalad/tests/test_tests_utils_pytest.py
Labels: semver-tests

#7329 Allow stderr for git-annex subprocess with records generator
  changelog.d/pr-7329.md
  datalad/support/annexrepo.py
Labels: semver-patch

#7353 Fix testing assumption - do create pure GitRepo superdataset and test against it
  changelog.d/pr-7353.md
  datalad/support/tests/test_repo_save.py
  datalad/tests/utils_pytest.py
Labels: semver-tests

#7337 Type-annotate various things in `datalad/runner/`
  changelog.d/pr-7337.md
  datalad/cmd.py
  datalad/runner/coreprotocols.py
  datalad/runner/exception.py
  datalad/runner/nonasyncrunner.py
  datalad/runner/protocol.py
  datalad/runner/runnerthreads.py
  datalad/runner/tests/test_exception.py
  datalad/runner/tests/test_generatormixin.py
  datalad/runner/tests/test_gitrunner.py
  datalad/runner/tests/test_nonasyncrunner.py
  datalad/runner/tests/test_threadsafety.py
  datalad/runner/tests/test_utils.py
  datalad/runner/tests/test_witless_runner.py
  datalad/runner/tests/utils.py
  datalad/runner/utils.py
Labels: semver-internal

#7301 Improve uptodateness of config reports across manager instances
  changelog.d/pr-7301.md
  datalad/config.py
  datalad/distribution/dataset.py
  datalad/tests/test_base.py
  datalad/tests/test_config.py
Labels: semver-patch

#7342 Skip with_sameas_remote when rsync and annex are incompatible
  changelog.d/pr-7342.md
  datalad/distribution/tests/test_siblings.py
  datalad/support/external_versions.py
  datalad/tests/utils_pytest.py
Labels: semver-tests

#7359 Set minimal version of typing_extensions to be 3.10.0.0
  setup.py
Labels: semver-internal
