Repository datalad/datalad, pull requests merged in 2023-06, with the labels that each got.

#7392 Discontinue ConfigManager abuse for Git identity warning
  changelog.d/pr-7392.md
  datalad/__init__.py
  datalad/config.py
  datalad/tests/test_base.py
Labels: semver-internal

#7309 WTF - bring back and extend information on metadata extractors etc
  changelog.d/pr-7309.md
  datalad/local/wtf.py
Labels: cmd-wtf, semver-patch

#7405 Fix documentation link to python-gitlab
  datalad/distributed/create_sibling_gitlab.py
Labels: semver-documentation

#7413 Boost python to 3.8 during extensions testing
  .github/workflows/test_extensions.yml
  changelog.d/pr-7413.md
Labels: semver-tests

#7412 Use `sphinx_autodoc_typehints`
  changelog.d/pr-7412.md
  docs/source/conf.py
  setup.py
  tox.ini
Labels: semver-documentation

#7388 ENH: minor tune up of addurls to be more tollerant and "informative"
  changelog.d/pr-7388.md
  datalad/local/addurls.py
Labels: UX, semver-patch

#7407 Address gitlab API special character restrictions
  changelog.d/pr-7407.md
  datalad/distributed/create_sibling_gitlab.py
  datalad/distributed/tests/test_create_sibling_gitlab.py
Labels: semver-minor

#7418 Do not map (leave as is) trailing / or \ in github URLs.
  changelog.d/pr-7418.md
  datalad/core/distributed/tests/test_clone.py
  datalad/interface/common_cfg.py
Labels: semver-patch

#7377 OPT: parse_gitconfig_dump() origin path processing
  datalad/config.py
Labels: semver-performance

#7050 More correct summary reporting for relaxed (no size) --annex
  changelog.d/pr-7050.md
  datalad/core/local/status.py
Labels: UX, cmd-status, semver-patch

#7410 BF: Remove create-sibling-gitlab's hierarchy layout, make collection the default
  changelog.d/pr-7410.md
  datalad/distributed/create_sibling_gitlab.py
  datalad/distributed/tests/test_create_sibling_gitlab.py
Labels: semver-minor, release

#7428 Merge master into maint for a release
  .all-contributorsrc
  .github/workflows/test-nose.yml
  .github/workflows/test_extensions.yml
  .github/workflows/test_win2019_disabled
  .tributors
  .zenodo.json
  README.md
  changelog.d/pr-7261.md
  changelog.d/pr-7309.md
  changelog.d/pr-7310.md
  changelog.d/pr-7330.md
  changelog.d/pr-7398.md
  changelog.d/pr-7407.md
  changelog.d/pr-7410.md
  datalad/distributed/create_sibling_gitlab.py
  datalad/distributed/drop.py
  datalad/distributed/tests/test_create_sibling_gitlab.py
  datalad/distributed/tests/test_drop.py
  datalad/local/wtf.py
  datalad/support/gitrepo.py
  datalad/tests/test_tests_utils.py
  datalad/tests/utils.py
  datalad/ui/progressbars.py
  docs/source/design/index.rst
  docs/source/design/result_records.rst
  docs/source/design/user_messaging.rst
  setup.py
Labels: semver-patch, release

#7372 Address recent changes in behavior of git-annex
  .travis.yml
  changelog.d/pr-7372.md
  datalad/dataset/gitrepo.py
  datalad/distributed/create_sibling_ria.py
  datalad/distributed/export_archive_ora.py
  datalad/support/annexrepo.py
  datalad/support/tests/test_annexrepo.py
  datalad/support/tests/test_fileinfo.py
  tools/find-hanged-tests
  tox.ini
Labels: semver-patch, release

#7443 Remove surrounding quotes in output filenames even for newer version of annex
  changelog.d/pr-7443.md
  datalad/support/annexrepo.py
Labels: annex, semver-patch
