Repository datalad/datalad, pull requests merged in 2023-10, with the labels that each got.

#7495 add RRID to package metadata
  changelog.d/pr-7495.md
  setup.py
Labels: semver-internal

#7502 Fix time_diff* and time_remove benchmarks to account for long RFed interfaces
  benchmarks/api.py
  changelog.d/pr-7502.md
  tools/ci/benchmark-travis-pr.sh
Labels: semver-internal

#7501 Fix documentation syntax, add files for doc-string parsing
  datalad/runner/nonasyncrunner.py
  docs/source/modref.rst
Labels: semver-documentation, CHANGELOG-missing

#7500 improve threaded-runner documentation
  changelog.d/pr-7500.md
  docs/source/design/threaded_runner.rst
Labels: semver-documentation

#7505 Inform asv that there should be no warmup runs for time_remove benchmark
  benchmarks/api.py
  changelog.d/pr-7505.md
Labels: semver-tests

#7471 Cache value of the has_symlink_capability to spare some cycles
  changelog.d/pr-7471.md
  datalad/core/distributed/tests/test_clone.py
  datalad/tests/utils_pytest.py
Labels: merge-if-ok, semver-tests

#7513 Copy script to install singularity from datalad-container and use it in the workflow
  .github/workflows/test_extensions.yml
  tools/ci/install-singularity.sh
Labels: semver-tests

#7525 Add a missing space into example code_cmd
  datalad/distribution/update.py
Labels: semver-documentation

#7522 Robustify update target detection for adjusted mode datasets
  changelog.d/20231025_194118_michael.hanke_bf_7507.md
  datalad/distribution/update.py
Labels: adjusted-branches, semver-patch
