Repository datalad/datalad, pull requests merged in 2023-05, with the labels that each got.

#7379 Fix failing testing on CI: Use sample S3 url DANDI archive, our copy of old .deb, specific miniconda installer for py 3.7
  .appveyor.yml
  .travis.yml
  changelog.d/pr-7379.md
  datalad/tests/test_s3.py
Labels: semver-tests

#7383 ENH: add a debug msg while setting/changing specialremote of UnderAnnexUI
  datalad/ui/dialog.py
Labels: semver-internal

#7310 DOC: Add a "User messaging" design doc
  changelog.d/pr-7310.md
  docs/source/design/index.rst
  docs/source/design/result_records.rst
  docs/source/design/user_messaging.rst
Labels: semver-documentation

#7385 docs: add workaround for theme issues (search not working)
  changelog.d/pr-7385.md
  docs/source/conf.py
Labels: semver-documentation

#7386 Clarify treatment of subdataset modifications by `run`
  datalad/core/local/run.py
Labels: release, semver-documentation

#7390 Bug fix for runner timeout handling
  changelog.d/pr-7390.md
  datalad/cmd.py
  datalad/runner/nonasyncrunner.py
Labels: semver-patch

#7378 Discontinue ConfigManager abuse for Git identity warning
  datalad/__init__.py
  datalad/config.py
Labels: semver-internal
