Repository datalad/datalad, pull requests merged in 2024-04, with the labels that each got.

#7559 adjust for new error message in git cat-file
  datalad/support/annexrepo.py
Labels: semver-major

#7577 Merging maint to make the first major release
  .github/workflows/test_extensions.yml
  .github/workflows/test_macos.yml
  .github/workflows/update-contributors.yml
  changelog.d/pr-7577.md
  datalad/support/annexrepo.py
Labels: semver-major, release

#7580 Load extensions in annex remote entrypoint
  changelog.d/20240416_194511_michael.hanke_remote_extension.md
  datalad/customremotes/main.py
Labels: annex, semver-patch, release

#7581 Relax condition in `test_force_checkdatapresent` to avoid flaky test failures
  changelog.d/pr-7581.md
  datalad/core/distributed/tests/test_push.py
Labels: annex, release, semver-tests

#7585 Stop testing on Python 3.7
  .appveyor.yml
  .github/workflows/benchmarks.yml
  .github/workflows/docbuild.yml
  .github/workflows/lint.yml
  .github/workflows/test_crippled.yml
  .github/workflows/test_macos.yml
  .github/workflows/typing.yml
  changelog.d/pr-7585.md
Labels: tests, semver-tests
