Repository datalad/datalad, pull requests merged in 2024-06, with the labels that each got.

#7603 Fix add-archive-content for patool>=2.0
  changelog.d/pr-7603.md
  datalad/support/archive_utils_patool.py
Labels: semver-patch

#7610 Fixup minor typos in documentation/comments using fresh codespell
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  changelog.d/pr-7610.md
  datalad/core/local/tests/test_save.py
  datalad/distributed/create_sibling_github.py
  datalad/local/remove.py
  datalad/local/tests/test_gitcredential.py
  datalad/local/tests/test_rerun.py
  datalad/support/locking.py
  docs/source/changelog.rst
Labels: semver-internal

#7575 RF: Drop boto for boto3
  changelog.d/pr-7340.md
  datalad/downloaders/base.py
  datalad/downloaders/providers.py
  datalad/downloaders/s3.py
  datalad/downloaders/tests/test_s3.py
  datalad/support/external_versions.py
  datalad/support/s3.py
  setup.py
  tox.ini
Labels: semver-minor, release

#7619 test_gracefull_death: raise test_gracefull_death threshold to 300 from 100
  changelog.d/pr-7619.md
  datalad/support/tests/test_parallel.py
Labels: merge-if-ok, semver-tests

#7620 Replace 3.7 with 3.8 in ASV, contributing docs, and matrix for GitHub CI
  CONTRIBUTING.md
  asv.conf.json
  setup.py
  tools/ci/test-jobs.yml
Labels: merge-if-ok, semver-internal

#7617 For appveyor ssh setup, setup MaxSessions 100 to avoid 'channel 22: open failed: connect failed: open failed'
  .appveyor.yml
  changelog.d/pr-7617.md
Labels: merge-if-ok, semver-tests

#7616 Address github cronjob CI runs issues: inability to build/install old git (wrong version/tag, absent build-depends)
  .github/workflows/test.yml
  datalad/support/gitrepo.py
Labels: merge-if-ok, semver-tests

#7550 Update README.md: improve wording
  README.md
  changelog.d/pr-7550.md
Labels: semver-documentation

#7622 Make test for presence of max_path in partitions not run for current psutil 6.0.0
  changelog.d/pr-7622.md
  datalad/local/tests/test_wtf.py
Labels: semver-tests
