Repository datalad/datalad, pull requests merged in 2024-08, with the labels that each got.

#7633 INFRA: Add RTD-recommended configuration ahead of deprecations
  docs/source/conf.py
Labels: semver-documentation

#7640 Account for the fix in git-annex behavior in test_add_delete_after_and_drop_subdir
  changelog.d/pr-7640.md
  datalad/local/tests/test_add_archive_content.py
Labels: release, semver-tests

#7645 Declare minimal compat version of pytest to be 7.0
  changelog.d/pr-7645.md
  setup.py
Labels: semver-tests

#7649 BF: replace url for codecov uploader for macos to versioned one with two archs
  .appveyor.yml
  changelog.d/pr-7649.md
Labels: semver-tests

#7590 Make github workflow which would ensure that PR against master would have everything from maint merged
  .github/workflows/test-label.yml
  changelog.d/pr-7590.md
Labels: semver-internal

#7641 Exit with the original non-0 exit code if underlying functionality, in particular "datalad run", returned incomplete result record with a non-0 exit code
  changelog.d/pr-7641.md
  datalad/cli/main.py
  datalad/cli/tests/test_main.py
Labels: semver-patch
