Repository datalad/datalad, pull requests merged in 2024-02, with the labels that each got.

#7553 Add manual triggering support/documentation for release workflow
  .github/workflows/release.yml
  CONTRIBUTING.md
  changelog.d/pr-7553.md
Labels: semver-internal, release automation

#7554 Update also version: field in CITATION.cff upon release
  .github/workflows/release.yml
Labels: semver-internal, release automation

#7552 Escape the \ in a docstring
  datalad/distribution/install.py
Labels: semver-documentation

#7551 Add the "http_token" authentication mechanism which provides 'Authentication: Token {TOKEN}' header
  changelog.d/pr-7551.md
  datalad/downloaders/http.py
  datalad/downloaders/providers.py
  datalad/downloaders/tests/test_http.py
Labels: semver-patch, release

#7562 add singularity dependency to installation script
  tools/ci/install-singularity.sh
Labels: semver-tests
