Repository datalad/datalad, pull requests merged in 2024-07, with the labels that each got.

#7625 Also apt install build-dependencies for "upstream-git" run (cron only)
  .github/workflows/test.yml
Labels: semver-tests

#7626 Relax test to allow now for 2 commits from git-annex for addurl on archive urls
  datalad/local/tests/test_add_archive_content.py
Labels: annex, semver-tests, team-gitannex

#7450 Ensure timestamps of files in ZIP archives are within years 1980-2107
  changelog.d/pr-7450.md
  datalad/local/export_archive.py
Labels: semver-patch, release

#7529 Generic issue -> Report a Bug template, Add a "Report a Generic Issue", disable "Open a blank"
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue_template.yml
  .github/ISSUE_TEMPLATE/issue_template_bug.yml
  .github/ISSUE_TEMPLATE/issue_template_gooey.yml
Labels: semver-internal

#7549 Make ORA remote more aware of the remote OS when using SSH
  changelog.d/pr-7549.md
  datalad/distributed/ora_remote.py
Labels: semver-patch

#7638 Adjust Gitea demo URL to reenable create-sibling-gitea test in datalad-next
  datalad/distributed/tests/test_create_sibling_gitea.py
Labels: semver-tests

#7636 Allow only one thread in S3 downloader's progress report callback
  changelog.d/pr-7636.md
  datalad/downloaders/s3.py
Labels: semver-patch, release
