Repository datalad/datalad, pull requests merged in 2025-05, with the labels that each got.

#7710 chore: for github tests CI - py 3.13 matrix should also (as for 3.12) use most recent available git-annex
  changelog.d/pr-7710.md
  tools/ci/test-jobs.yml
Labels: semver-tests

#7703 Enhance tributors with some detected ORCID entries
  .tributors
Labels: semver-patch

#7697 DOC: add recent-ish funding to acknowledgements
  docs/source/acknowledgements.rst
Labels: semver-documentation

#7716 enh: update acknowledgments with additional grants
  changelog.d/pr-7716.md
  docs/source/acknowledgements.rst
Labels: documentation, semver-documentation

#7723 BF: import from distutils.errors directly if no longer in setuptools
  .github/workflows/docbuild.yml
  _datalad_build_support/setup.py
  pyproject.toml
Labels: semver-patch, release

#7714 Resolve datetime library warnings
  _datalad_build_support/formatters.py
  changelog.d/pr-7714.md
Labels: semver-patch

#7731 BF: Prevent infinite recursion in clone when a remote points to itself
  changelog.d/pr-7731.md
  datalad/core/distributed/clone.py
  datalad/core/distributed/tests/test_clone.py
Labels: semver-patch
