Repository datalad/datalad, pull requests merged in 2025-07, with the labels that each got.

#7734 DOC: clarify in config documentation that we log to stderr not stdout
  CONTRIBUTING.md
  changelog.d/pr-7734.md
  datalad/interface/common_cfg.py
Labels: semver-documentation

#7730 Remove absolute path specification from `/bin/ls` invocation while interrogating remote path
  changelog.d/pr-7730.md
  datalad/distribution/create_sibling.py
Labels: semver-patch

#7720 foreach-dataset: add common usage options of {ds} and {refds} to datalad help
  datalad/local/foreach_dataset.py
Labels: semver-documentation, cmd-foreach-dataset
